# ESTADÍSTICA DESCRIPTIVA

::: part-intro
Captar la información que contienen los datos solo a base de irlos mirando es, desde luego, misión imposible. No hace falta que el conjunto sea muy grande, nuestra mente no es hábil para realizar esa tarea. Cuando miramos un número se nos olvida otro y no somos capaces –aunque nos cueste reconocerlo– de hacernos una idea clara de todos los aspectos relevantes.

Sí somos buenos detectando patrones y analizando imágenes –en esto somos incluso mejores que los ordenadores, que nos piden que interpretemos una imagen para confirmar que somos personas y no máquinas–, por lo que analizar los datos a través de representaciones gráficas es una excelente forma de hacerlo.

También podemos resumir los datos en unos pocos valores que den una buena visión de los aspectos que interesa conocer. Es lo que llamamos *síntesis numérica*.

Tanto representaciones gráficas como valores de síntesis numérica los hay de varios tipos. Existen gráficos que son adecuados para representar la evolución de una variable, otros para mostrar su dispersión o su relación con otras variables. Respecto a la síntesis numérica hay medidas que fijan su atención en los diferentes aspectos que son de interés, entre los cuales no hay que olvidar la variabilidad.

En el siguiente capítulo tratamos la síntesis numérica de datos, dando un repaso a las medidas de mayor interés. A continuación, presentamos los gráficos de uso más habitual, indicando cuáles conviene usar en cada caso y cuáles es mejor evitar.
:::
