# ESTADÍSTICAMENTE SIGNIFICATIVO

Solemos usar la palabra *significativo* como sinónimo de relevante, grande o importante. Sin embargo, en el contexto de los análisis estadísticos tiene un significado muy concreto que no tiene nada que ver con esas acepciones. Decimos que una diferencia es estadísticamente significativa cuando no la explica el azar. No importa si es grande o pequeña, si es importante o si no tiene ninguna relevancia. Si la variabilidad aleatoria de los datos no explica esa diferencia, entonces es estadísticamente significativa.

Lo que hacen los test estadísticos es analizar si las diferencias son estadísticamente significativas, porque diferencias siempre las hay. Si en un proceso de envasado tomamos una muestra, seguramente la media de sus pesos no coincidirá exactamente con el valor nominal, pero eso no implica que el proceso esté desajustado. De la misma forma, si a un grupo de pacientes se le administra un nuevo fármaco y a otro grupo similar se le da un placebo, lo más probable es que los resultados no serán idénticos en los dos grupos, aunque el nuevo fármaco sea totalmente ineficaz. 

Realizamos un test estadístico para analizar si la diferencia observada puede ser atribuida a la variabilidad aleatoria que presentan los datos o si es más razonable considerar que existe una causa que la provoca. El test cuantifica el nivel de duda y nos ayuda a tomar una decisión. 

Dedicamos esta parte a comentar la filosofía que hay detrás de los test estadísticos y a detallar cómo se realizan los más habituales.