# Síntesis numérica de datos

Qué es. Símil del retrato robot.

## Medidas de tendencia central

Aquí texto sobre la importancia de no pretender describir datos solo con medidas de tendencia central.

### Media aritmética {.unnumbered}

Tanto el cálculo como el significado de la media aritmética son bien conocidos por los estudiantes. Además de que la idea es sencilla, su cálculo tiene interés para saber si se aprobará una asignatura a la vista de las notas del curso. \[*pretendo empezar con un toque de humor pero no sé si se entiende*\]

Cuando los datos se presentan tabulados no hay que olvidar que cada uno se repite tantas veces como indica su **frecuencia absoluta**. En la @tbl-hijosFamilia, la variable considerada es el número de hijos por familia ($x$) y el número de familias para cada uno de esos valores es la frecuencia absoluta ($n$).

|                           |     |     |     |     |     |     |
|---------------------------|:---:|:---:|:---:|:---:|:---:|:---:|
| Número de hijos ($x$):    |  0  |  1  |  2  |  3  |  4  |  5  |
| Número de familias ($n$): | 13  | 21  | 15  |  8  |  1  |  2  |

: Número de hijos por familia {#tbl-hijosFamilia}

El valor medio ($\bar{x}$) del número de hijos por famila es igual a:

$$ \bar{x} = \frac{\sum_{i} n_i \, x_i }{N} \:  = \:  1,48 $$

Donde $N$ es el número total de datos (en este caso $N=60$) e $i$ es el índice que aquí va de 1 a 6 para valores de $x$ de 0 a 5.

Para cada valor de $x_i$ su **frecuencia relativa** es $f_i = n_i/N$. También podemos calcular la media usando la expresión:

$$ \bar{x} = \sum_{i} f_i \, x_i   =  1,48 $$ Esta expresión es análoga a la de la esperanza matemática (solo hay que cambiar frecuencia relativa por probabilidad) que veremos más adelante,

::: callout-note
## Media (*mean*), promedio (*average*) y esperanza matemática (*expected value*)

Aquí texto
:::

::: callout-note
## La media de la edad

Aquí texto
:::

### Mediana {.unnumbered}

Se ordenan los valores y el que queda en centro es la mediana. Si el número de valores es par se toma como mediana el promedio de los dos centrales.

La mediana tiene unas propiedades de las que carece la media, por lo que es un buen complemento informativo e incluso puede ser más útil en algunos casos. Sus ventajas respecto a la media son:

-   Es más robusta frente a la presencia de valores anómalos. Supongamos que nuestros datos son:\
    $$2, \, 5, \, 6, \,7 \,\text{ y  }\, 9$$ La media es 5,6 y la mediana es 6. Si al introducir los datos al ordenador nos equivocamos y en último lugar en vez de 9 introducimos 99, la media pasa a ser 23,8 mientras que la mediana sigue siendo 6. Esto hace que la mediana sea útil cuando nos enfrentamos a un conjunto de datos que puede contener valores anómalos (posibles errores, problemas con la importación...) ya que da una idea menos contaminada por esos valores anomálos, del valor en torno al cual se mueven los datos.

-   Por su propia definición, la mediana deja un 50% de las observaciones por debajo y otro 50% por encima y esto le da unas ventajas que la media no tiene. Si queremos saber si en nuestra empresa estamos entre los que cobran más o entre los que cobran menos, debemos comparar nuestro salario con la mediana, no con la media. Si sólo hay 10 trabajadores y los salarios son (en las unidades que corresponda):\
    $$8, \, 8, \, 9, \,9, \, 10, \, 10, \, 11, \,11, \, 12 \,\text{ y  }\, 100$$ todos menos uno (en este caso el 90%) están por debajo de la media, que es 18,8. Esto no pasa nunca con la mediana: si estamos por encima de la mediana, estamos con el 50% de los que más cobra. Otro ejemplo. Si en un examen las notas van de 0 a 10 y se aprueba sacando una nota igual o superior a 5, si la nota media es 5 no sabemos cuántos han aprobado. Si se han examinado 50 estudiantes, puede ser que 41 hayan suspendido con un 4; 8 hayan sacado un 10 y uno haya obtenido un 6. Esto da media 5, aunque el 82 % ha suspendido. Si la mediana es 5, seguro que la mitad han aprobado.

Si la distribución de los datos es simétrica, la media y la mediana coinciden y entonces todo son ventajas. Por ejemplo, en una distribución Normal la media y la mediana son iguales, por tanto, si los valores que tenemos provienen de una Normal, la media y la mediana no andarán muy lejos una de otra. En cualquier caso, siempre podemos calcular las dos y aprovechar lo mejor de cada una.

Según publicó el diario El País [@ElPAisEjecutivo], el ejecutivo de las empresas cotizadas en la bolsa española mejor pagado en 2023 tuvo unos ingresos de 23,77 millones de euros. Esta empresa tenía ese año 2299 empleados en España, suponiendo que ese ejecutivo formara parte de la plantilla y que todos menos él cobraran solo el salario mínimo (15.120 €/año), se podría decir que en promedio cobran 25.453 €/año, un 68 % más de lo que cobrarían todos menos uno. \[*no sé si poner este párrafo, quizá se podría poner ejercicio y que busquen los datos*\]

### Moda {.unnumbered}

Dado un conjunto de valores, la moda es el que más se repite. A difencia de la media y la mediana puede no ser única y se puede aplicar también a varibles cualitativas (no numéricas). Si realizamos sobre el método de transporte que usan los estudiantes para ir a su centro de estudio la moda puede ser el autobús o ir andando. No es una medida muy relevante. Siempre aparece en los libros pero rara vez en los resúmenes estadísticos.

A modo de resumen de este apartado, la figura [-@fig-salariosINE] muestra la distribución de los salarios en España en 2021. Tiene dos "Salarios más frecuentes" (observe que se evita el término "moda", quizá porque se puede prestar a malas interpretaciones). Cuando se da esta circunstancia se dice que la distribución es bimodal. El salario medio es mayor que el mediano porque los salarios muy altos tiran de la media pero apenas afectan a la mediana. <br><br>

![Distribución de los salarios en España en 2021. [Fuente: @salariosINE2021].](Figuras/distribucionSalariosINE.png){#fig-salariosINE fig-align="center" width="80%"}

## Medidas de dispersión

Quizá lo más importante de este capítulo -y de todo el libro- es interiorizar la importancia de considerar la variabilidad para para describir datos, para analizarlos y para tomar decisiones. Veamos las formas más habituales de medirla.

### Rango {.unnumbered}

Es la diferencia entre los valores máximo y mínimo. Si el rango de edades de los asistentes a un concierto es de 5 años significa que todos son de edades similares, pero si es de 50 años es que ese tipo de música interesa a personas de varias generaciones.

+--------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **PROS** <i class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></i>   | -   Muy fácil de entender y de calcular.                                                                  |
+--------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **CONS** <i class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333;"></i> | -   Solo cuentan los valores extremos, que pueden ser anómalos o no representativos del conjunto de datos |
+--------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

: Ajuste a ojo. Ventajas e inconvenientes {#tbl-letters} : {tbl-colwidths="\[10,90\]"}

### Desviación media {.unnumbered}

Interesa una medida de dispersión en la que todos los valores tengan algo que decir, tal como ocurre con la media aritmética. En esta línea, una medida de dispersión podría ser el promedio de las distancias de cada valor respecto a la media, Pero una de las propiedades de la media aritmética es que equibra esas distancias de manera que esa expresión siempre será igual a cero. No importa que hay mucha o poca dispersión, siempre vale lo mismo, por tanto, está claro que no sirve para nada.

Existen dos formas de resolver ese problema. Una de ellas es usar las distancias en valor aboluto. En este caso tenemos lo que llamamos Distancia Media, que sí es una medida de variabilidad (a más variabilidad, mayor desviación media). Si nuestros valores son: $x_1,\, x_2, \, \dotsc \, x_N$ y su valor medio es $\bar{x}$, tendremos:

$$ DM = \frac{\sum_{i=1}^N |x_i - \bar{x}|}{N} $$ Es interesante observar que la distancia media está relacionada de forma más natural con la mediana que con la media aritmética. Consideremos la función:

$$ f(a) =  \frac{\sum_{i=1}^N |x_i -a|}{N} $$ Como la distancia promedio solo depende de $a$ le hemos llamado $f(a)$. El valor que minimiza esta función y que, por tanto, puede considerarse el mejor representate de los datos con el criterio aplicado no es la media sinó la mediana.

La otra forma de resolver el problema de la anulación de las diferencias es elevándolas al cuadrado. Parece una complicación innecesaria pero tiene muchas ventajas, es lo que llamamos varianza.

### Varianza {.unnumbered}

::: callout-note
## ¿Varianza o variancia?

Las dos son válidas según el diccionario de la Real Academia Española. Nosotros usaremos *varianza*.
:::

Simplemente elevamos las diferencias al cuadrado en vez de usar el valor absoluto. Le llamaremos $\sigma^2$:

$$ \sigma^2 = \frac{\sum_{i=1}^N ( x_i - \bar{x} )^2}{N} $$ Repitiendo el análisis que hemos hecho para la DM, vamos a elegir el valor de $a$ que minimiza la función:

$$g(a) =  \frac{\sum_{i=1}^N ( x_i - a )^2}{N} $$ En este caso lo podemos deducir derivando $g(a)$ con respecto a $a$, igualando a cero y despejando su valor. Veamos:

$$\frac{\partial g(a)}{\partial a} = \frac{-2}{N} \sum_{i=1}^{N}(x_i-a) = 0$$ Por tanto $\sum_{i=1}^{N}(x_i-a) = 0$, de donde se deduce que $\sum x_i =N \cdot a$ y despejando $a$ tenemos:

$$ a = \sum_{i=1}^{N} \frac{x_i}{N} $$ En este caso el valor de $a$ sí coincide con la media aritmética (le llamamos ($\mu$). Si hacemos la segunda derivada vemos que siempre es positiva, lo cual confirma que el punto crítico es $a=\mu$ y que el valor mínimo de $g(a)$ es la varianza de $X$ (le llamamos $\sigma^2$).

###### **¿Por qué se prefiere usar la varianza en vez de la distancia media?** {.unnumbered}

Elevar al cuadrado las diferencias pudiendo trabajar con su valor absoluto parece una complicación innecesaria, pero la varianza tienes unas ventajas que la $DM$ no tiene, veamos algunas:

-   En los desarrollos anteriores hemos visto que la media, medida descriptiva por excelencia, está asociada de forma más natural con la varianza que con la $DM$.

-   La $DM$ incluye en su expresión la función “valor absoluto” que se comporta mal desde un punto de vista matemático, mientras que la función cuadrática es muy fácilmente tratable. Observe, por ejemplo, que la demostración de que la media hace mínimo el promedio de los cuadrados se ha realizado de forma casi inmediata, mientras que probar que la mediana hace mínima la media de las distancias es bastante más complejo.

-   La desviación estándar $\sigma$ de la población es usada para definir la distribución más famosa y útil, como es la Normal. Esto posibilita la construcción de intervalos de confianza para estimar, por ejemplo, la media de la población, lo que sería mucho más complejo si se usara la $DM$.

-   La varianza es una suma de cuadrados que se puede descomponer en diversos sumandos dando origen al llamado \`\`Análisis de la Varianza''\index{análisis de la varianza}. El desarrollo de la teoría de los modelos lineales está basado en gran parte en el criterio de los mínimos cuadrados, que es el mismo en que está basada la varianza. Cuando la población origen de los datos es Normal, el cociente de varianzas muestrales sigue una distribución conocida, llamada $F$ de Snedecor.

-   La varianza de una suma de variables aleatorias se calcula de una forma muy fácil, especialmente si las variables son independientes. Por ejemplo, en un proceso de envasado, si el peso del envase tiene una varianza $V(X)$ y la varianza del contenido es $V(Y)$, la varianza del conjunto es $V(X+Y) = V(X) + V(Y)$.

### Desviación típica {.unnumbered}

texto

texto

texto

texto

texto

texto

texto

texto

### El coeficiente de variación {.unnumbered}

texto

texto

## Medidas de posición

texto

texto

### Cuartiles {.unnumbered}

Formas de calcular los cuartiles

https://mathworld.wolfram.com/Quartile.html

::: callout-note
## Los cuartiles como zona

Aunque un cuartil es un número y no una zona, a veces se dice que un valor pertenece al primer o al tercer cuartil y lo que eso significa no siempre está claro. Podria pensarse que pertenece al primer cuartil cuando es menor que Q1 y al tercero cuando es mayor que la mediana y menor que Q3, pero no siempre es así. La relevancia de las revistas científicas se mide por su "factor de impacto", un número relacionado con las citas en otras revistas de los artículos que publican. Para cada ámbito de conocimiento se realizan rankins de revistas según su factor de impacto y todos queremos publicar en las que lo tienen más alto, que no son las del cuarto, seguido por las del tercer cuartil, sino en del primero y el segundo. El ranking se hace de más a menos.
:::

### Deciles. Percentiles {.unnumbered}

texto

texto

## Porcentajes

texto

texto

texto

::: callout-note
## La paradoja de las patatas

Aunque un cuartil es un número y no una zona, a veces se dice que un valor pertenece al primer o al tercer cuartil y lo que eso significa no siempre está claro. Podria pensarse que pertenece al primer cuartil cuando es menor que Q1 y al tercero cuando es mayor que la mediana y menor que Q3, pero no siempre es así. La relevancia de las revistas científicas se mide por su "factor de impacto", un número relacionado con las citas en otras revistas de los artículos que publican. Para cada ámbito de conocimiento se realizan rankins de revistas según su factor de impacto y todos queremos publicar en las que lo tienen más alto, que no son las del cuarto, seguido por las del tercer cuartil, sino en del primero y el segundo. El ranking se hace de más a menos.
:::

texto

texto

texto

texto

texto

texto

texto

texto

texto

texto

texto

texto

texto

¿Qué hace esto aquí?

## Apéndice 1.1: Otras medias {.unnumbered}

### Media geométrica {.unnumbered}

Si una población tenía 10.000 habitantes en el año cero, creció el primer año a una tasa del 5 %, el segundo a una tasa del 20 % y el tercer año al 50 % ¿A que tasa promedio ha crecido en estos tres años?

+-------------+-------------------+---------------------+---------------------+----------------------------+
| Año         | Población inicial | Tasa de crecimiento | Factor de expansión | Población al final del año |
+:===========:+:=================:+:===================:+:===================:+:==========================:+
| 1           | 10.000            | 0,05                | 1,05                | 10.500                     |
+-------------+-------------------+---------------------+---------------------+----------------------------+
| 2           | 10.500            | 0,20                | 1,20                | 12.600                     |
+-------------+-------------------+---------------------+---------------------+----------------------------+
| 3           | 12.600            | 0,50                | 1,50                | 18.900                     |
+-------------+-------------------+---------------------+---------------------+----------------------------+

: Evolución de la población {#tbl-evolucionPoblacion1} : {tbl-colwidths="\[10,20,20,20\]"}

\noindent Si calculamos la media aritmética de la tasa de crecimiento \index{tasa de crecimiento} tenemos: $(0,05 + 0,20 + 0,50)/3 = 0,25$ y el factor medio de expansión sería $1,25$. Pero si la población hubiera crecido los tres años de esta forma, no se llegaría al mismo resultado final:

+-------------+-------------------+---------------------+---------------------+----------------------------+
| Año         | Población inicial | Tasa de crecimiento | Factor de expansión | Población al final del año |
+:===========:+:=================:+:===================:+:===================:+:==========================:+
| 1           | 10.000            | 0,25                | 1,25                | 12.500                     |
+-------------+-------------------+---------------------+---------------------+----------------------------+
| 2           | 12.500            | 0,25                | 1,25                | 15.625                     |
+-------------+-------------------+---------------------+---------------------+----------------------------+
| 3           | 15.625            | 0,25                | 1,25                | 19.531                     |
+-------------+-------------------+---------------------+---------------------+----------------------------+

: Evolución de la población {#tbl-evolucionPoblacion1} : {tbl-colwidths="\[10,20,20,20\]"} :{.hover}

\noindent Por tanto, la media aritmética no es un buen indicador de la tasa media de crecimiento.

Si la población crece a una tasa constante $i$, para que al final del tercer año tenga el mismo efecto que las tasas del ejemplo, se debe verificar que:

$$ 10\,000(1+i)(1+i)(1+i)=10\,000(1+0,05)(1+0,20)(1+0,50) $$ \noindent De donde:

$$(1+i)= \sqrt[3]{1,05 \cdot 1,20 \cdot 1,50}=1,2364$$

\noindent Si se hubiera tenido este factor de expansión cada año (nótese que es la media geométrica), hubiera conducido a una población final igual a la que tenemos.

::: callout-note
## Curiosidades sobre la media geométrica

-   A diferencia de la media aritmética, la media geométrica sólo se define para números positivos.

-   La media geométrica nunca es mayor que la media aritmética. La demostración para el caso de 2 valores es fácil por reducción al absurdo. Supongamos que: $\sqrt{ab} > (a+b)/2$, entonces $ab > (a^2+2ab+b^2)/4$, de donde: $0 >a^2-2ab+b^2$. Como $a^2-2ab+b^2=(a-b)^2$ es imposible que este valor sea negativo, luego es imposible que $\sqrt{ab}>(a+b)/2$.
:::

### Media armónica {.unnumbered}

Se define la media armónica de $x_1, x_2, ..., x_N$ como:

$$Mh = \frac{N}{\large{\frac{1}{x_1}+\frac{1}{x_2}+...+\frac{1}{x_N}}}$$

Parece que esto sea un retorcimiento sin ningún interés, pero no. Si un coche recorre cierta distancia a una velocidad de 100 km/h y vuelve por el mismo camino a 120 km/h, la velocidad media a que ha realizado el viaje es:

$$Mh = \frac{2}{\large{\frac{1}{100}+\frac{1}{120}}} = 109,1 \text{ km/h}$$

y no 110 km/h como en principio se podría pensar.

Observe que la velocidad es igual a la distancia recorrida dividida por el tiempo tardado en recorrerla, es decir $v=d/t$ y por tanto $t=d/v$. En nuestro caso, si la distancia a recorrer es $d$, el tiempo tardado en la ida es $t_1 =d/100$ y el tiempo tardado en el regreso es $t_2 =d/120$. De esta manera el tiempo total invertido en todo el recorrido $(2d)$ será $t=t_1+t_2$ y la velocidad media se calcula de la forma:

$$ \text{Velocidad media} = \frac{\text{Distancia total recorrida}}{\text{Tiempo total empleado}} = \frac{2d}{\large{\frac{d}{100}+\frac{d}{120}}} $$ Otro ejemplo: Un avión recorre 3000 km. Los 1000 primeros a 700 km/h, los 1000 siguientes a 800 km/h, y los 1000 restantes a 900 km/h ¿Cuál ha sido su velocidad media? No ha sido 800 km/h sino 791,6 km/h.
