# Representaciones gráficas

Empezamos planteando un reto: El dueño de una panadería sospecha que las barras de pan que está vendiendo tienen un peso demasiado variable, de forma que algunas pueden estar por debajo del límite que marca la ley. Se elaboran en dos máquinas que son utilizadas por dos operarios, uno por la mañana y otro por la tarde. La tabla [-@tbl-panaderia] contiene los pesos (en gramos) de muestras que se han ido recogiendo durante 20 días.

::: {style="font-size:15px"}
+:-----------:+:---------------------------:+:------------------------------------------:+:------------------------------------------:+
| Día         | Operario                    | Máquina 1                                  | Máquina 2                                  |
+-------------+-----------------------------+--------------------------------------------+--------------------------------------------+
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| []{}\       | []{}\                       | []{}\                                      | []{}\                                      |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| []{}\       | []{}\                       | []{}\                                      | []{}\                                      |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| []{}\       | []{}\                       | []{}\                                      | []{}\                                      |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
| 2\          | A\                          | 220,3       215,5       219,1       219,2\ | 220,3       215,5       219,1       219,2\ |
+-------------+-----------------------------+--------------------------------------------+--------------------------------------------+

: Peso de barras de pan elaboradas en una panadería {#tbl-panaderia} : {tbl-colwidths="\[5, 15, 40, 40\]"}
:::

El peso debe ser de 210 $\pm$ 10 g. Las preguntas que nos planteamos son: ¿Existe algún problema? ¿Qué está pasando? ¿qué hay que hacer para resolver el problema, si es que existe?

Si trata de sacar conclusiones mirando los números seguramente se equivocará. Aunque en este caso solo hay 160 valores, analizarlos "a ojo" siempre es arriesgado. Tampoco es una buena idea empezar calculado medias y desviaciones típicas o, peor todavía, emnpezar planteando test estadísticos más o menos sofisticados.

Cuando queremos analizar datos, lo primero que siempre conviene hacer es representarlos gráficamente. Así tenemos una primera idea --muchas veces ya suficiente-- de lo que está pasando. 

En la figura +++++ por máquina y operario.

