# DESCRIBIR LO ALEATORIO

Cuando se hacen afirmaciones sobre un todo --la población-- analizando solo una parte --una muestra-- se debe asumir que los resultados estarán afectados por una cierta **variabilidad aleatoria**. Es posible que el 30 % de los consultados en una muestra manifiesten su intención de votar a un determinado partido, pero que en otra muestra de las mismas características ese porcentaje sea del 28 o del 33 %.

Para saber si el uso de un abono aumentará la cosecha no se pueden tomar solo dos plantas, aplicarlo a una de ellas, y si esa produce mayor cosecha considerar que el abono es eficaz. No se puede hacer de esta forma porque dos plantas que han crecido en las mismas condiciones no dan exactamente la misma cosecha. Puede ser que el abono no sea eficaz y que --por causalidad-- la planta que lo tiene dé mayor producción. Hay que comparar la diferencia entre la producción de ambas plantas con la **variabilidad** que presenta la cosecha en las condiciones habituales.

Por último, todos sabemos que cuando se prueba una vacuna o un nuevo medicamento no se hace con una sola persona (¡que fácil y rápido sería!) porque existe **variabilidad** entre personas --no todos reaccionamos igual-- y eso complica bastante las cosas.

La variabilidad y el azar juegan un papel fundamental en los análisis estadísticos. Necesitamos manejar un lenguaje y unos conceptos que nos permitan ordenar las ideas y movernos con seguridad en este terreno. A este tema dedicamos los dos capítulos de esta parte. Lo que se explica son matemáticas que nos serán muy útiles en nuestros razonamientos para sacar conclusiones a partir de los datos disponibles.
