project:
  type: book
  output-dir: docs
lang: es

book: 
  title: "Estadística a vista de pájaro"
  subtitle: "Estoy haciendo pruebas"
  date: today
  date-format: medium
  author: "Pere Grima"
  site-url: https://peregrima.github.io/VistaDePajaro/

  chapters:
    - index.qmd
    - conceptosGenerales.qmd
    
    - part: Parte_Descriptiva.qmd
      chapters: 
        - sintesisNumerica.qmd
        - graficos.qmd
        
    - part: Parte_Variabilidad.qmd
      chapters: 
        - variablesAleatorias.qmd
        - distribucionesProbabilidad.qmd
        
    - part: Parte_Estimacion.qmd
      chapters: 
        - Proporciones.qmd
        - tamañoPoblacion.qmd
        
    - part: Parte_Experimentos.qmd
      chapters: 
        - floresAspirina.qmd
        - duracionPilas.qmd   
        
    - part: Parte_Corre_Regre.qmd
      chapters:
        - correlacion.qmd
        - regresionSimple.qmd
        - regresionMultiple.qmd
        - references.qmd

bibliography: references.bib

# Fuentes ----------------------------
mainfont: Calibri
monofont: Verdana
mathfont: CambriaMath
fontfamily: baskervald    # -> Solo en PDF
fontsize: 13pt
# systemfonts::system_fonts(): Lista de fuentes disponibles en el ordenador.


format:
  html:
    theme: cosmo
    code-fold: true
    css: styles.css
    header-includes:
      <script src="https://kit.fontawesome.com/98a945d90a.js" crossorigin="anonymous"></script>
  pdf:
    documentclass: scrreprt

editor: visual

