project:
  type: book
  output-dir: docs
lang: es

book: 
  title: |
      <span style="font-size: 1.5em;">Estadística</span><br>
      <span style="font-size: 1em;">Entender - Aplicar - Enseñar</span>
  subtitle:
      De momento son pruebas  #  <span style="font-size: 1em;">Entender - Aplicar - Enseñar</span>
  # date: today
  # date-format: medium
  # author: "Roberto Behar G. / Pere Grima"
  sidebar:
      collapse-level: 0
  cover-image: cover.jpg
  #site-url: https://peregrima.github.io/VistadePajaro/
  #repo-url: https://github.com/PereGrima/VistadePajaro/
  #repo-actions: [issue] # 'issue' adds the report link

  chapters:
    - index.qmd
    
    - part: 00_Prologo.qmd
      chapters:
        - 01_Introduccion.qmd
     
    - part: 0_01_tapaDescriptiva.qmd                  # I ESTADÍSTICA DESCRIPTIVA
      chapters: 
        - 02_sintesisNumerica.qmd               # 2. Síntesis numérica de datos
        - 03_Graficos.qmd                       # 3. Representaciones gráficas
        
    - part: 0_02_tapaVariabilidad.qmd                 # II DESCRIBIR LO ALEATORIO
      chapters:
        - 04_variablesAleatorias.qmd            # 4. Variables aleatorias    
        - 05_distribucionesProbabilidad.qmd     # 5. Distribuciones de probabilidad
        
    - part: 0_03_tapaMuestraPoblacion.qmd            # III DE LA MUESTRA A LA POBLACIÓN
      chapters: 
        - 06_muestreo.qmd                       # 6. Muestreo. Encuestas
        - 07_estimacion.qmd                     # 7. Estimación de características de la población
        
    - part: 0_04_tapaSignificativo.qmd                # IV ESTADÍSTICAMENTE SIGNIFICATIVO
      chapters: 
        - 08_contrasteHipotesis.qmd             # 8. Contraste de hipótesis
        - 09_algunosTest.qmd                    # 9. Algunos test clásicos

    - part: 0_05_tapaCorrelacion.qmd                  # V CORRELACIÓN Y REGRESIÓN
      chapters: 
        - 10_relacionLineal.qmd                 # 10. Medidas de relación lineal
        - 11_regreSimple.qmd                    # 11. Regresión simple
        - 12_regreMultiple.qmd                  # 12. Regresión múltiple
    
    - part: 0_06_tapaEpilogo.qmd                  # V CORRELACIÓN Y REGRESIÓN
      chapters: 
        - 13_Epilogo.qmd                         # EPÍLOGO
      
# Fuentes ----------------------------
mainfont: Calibri
monofont: Verdana
mathfont: CambriaMath
fontsize: 13pt
# systemfonts::system_fonts(): Lista de fuentes disponibles en el ordenador.

format:
  html:
    preview:
        serve: false
    theme: cosmo
    code-fold: true
    allow-html: true
    css: styles.css
    include-in-header:
      - text: |
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
execute:
  daemon: false
  
editor: visual
