# Regresión

## Definiciones

Residuos

Normalidad de la respuesta

Estimación de los parámetros

Modelo, no ecuación

## Cálculo de los coeficientes

Se realiza con el objetivo de minimizar la suma de los cuadrados de los residuos. Pero existen otros métodos. Veamos algunos.

### A ojo {.unnumbered}

Se traza la recta directamente sobre el papel o se identifican dos puntos de paso y a partir de ellos se calculan los coeficientes del modelo.

+-----------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| **PROS**                                                              | - Intuitivo. Muy fácil de entender                                                   |
|<i class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></i>    | - No se comenten errores de mucho bulto                                              | 
+-----------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| **CONS**                                                              | - No se logra el ajuste "perfecto" de acuerdo con el criterio establecido            |
|<i class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333;"></i>  | - No se tienen medidas de calidad del ajuste ni de significación de los coeficientes |
|                                                                       | - Solo sirve para regresión simple                                                   |
+-----------------------------------------------------------------------+--------------------------------------------------------------------------------------+
: {tbl-colwidths="[10,90]"}


A pesar de sus evidentes limitaciones, si solo se trata de tener la recta no es un método tan malo como parece. Con un poco de práctica el ajuste no será muy distinto del "perfecto" y no se cometeran errores de mucho bulto debido a la presencia de valroes anómalos, cosa que sí puede ocurrir si se tratan los datos de forma automática sin mnirarlos.   


### Método de Ishikawa {.unnumbered}

+-----------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| **PROS**                                                              | - Fácil de entender                                                                  |
|<i class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></i>    | - Robusto frente a la presencia de valores anómalos o con excesiva influencia        | 
+-----------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| **CONS**                                                              | - No se tienen medidas de calidad del ajuste                                         |
|<i class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333;"></i>  |  - Solo sirve para regresión simple                                                  |
+-----------------------------------------------------------------------+--------------------------------------------------------------------------------------+
: {tbl-colwidths="[10,90]"}

### Minimizando la suma de los residuos {.unnumbered}

Entendemos que se trata de minimizar la suma en valor absoluto, ya que un valor muy grande con signo negativo se logra simplemente aumentando los valores de $b_0$ y de $b_1$. Por tanto, se trata de minimizar $\sum [\, Y_i - (b_0 - b_1 X_i)]\,$. haciendo esta expresión igual a cero (mínimo valor posible), tenemos:

$$ n\bar{Y} - nb_0 - b_1 n \bar{X} = 0$$
Por tanto, con cualquier par de valores $b_0$ y $b_1$ que verifiquen la expresión $\bar{Y} = b_0 + b_1 \bar{X}$ tendremos una suma de residuos en valor absoluto igual a cero. 

Que haya infinitas rectas que cumplan esa condición ya es mala señal, porque seguro que no todas son la más adecuada. Para los valores representados en la figura X tenemos que $\bar{X}= 3\frac{1}{3}$ y $\bar{Y}= 8\frac{2}{3}$. Rectas que cumplen la condicion de minimizar la suma de los residuos son, por ejemplo, la que tiene coeficientes $b_0=8\frac{2}{3}$ y $b_1=0$, es decir: $Y = 8\frac{2}{3}$, o también $b_0 = 12$ y $b_1 = -1$

AQUÍ GRÁFICO

### Minimizando la suma de los residuos en valor absoluto {.unnumbered}

<i class="fa-solid fa-thumbs-down" style="color: #ec1809;"></i>

### Minizando la suma de los cuadrados de los residuos {.unnumbered}

### Con fuerza bruta {.unnumbered}

Curiosidad con el redondeo

See @knuth84 for additional discussion of literate programming.
