<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Variables aleatorias – &lt;span style="font-size: 1.5em;"&gt;Estadística&lt;/span&gt;&lt;br&gt;
&lt;span style="font-size: 1em;"&gt;Entender - Aplicar - Enseñar&lt;/span&gt;</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_distribucionesProbabilidad.html" rel="next">
<link href="./0_02_tapaVariabilidad.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2cf3c65c5b6db5ec86e992953759863e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0_02_tapaVariabilidad.html">DESCRIBIR LO ALEATORIO</a></li><li class="breadcrumb-item"><a href="./04_variablesAleatorias.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variables aleatorias</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"><span style="font-size: 1.5em;">Estadística</span><br> <span style="font-size: 1em;">Entender - Aplicar - Enseñar</span></a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PRESENTACIÓN</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./00_Prologo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prólogo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_01_tapaDescriptiva.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ESTADÍSTICA DESCRIPTIVA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_sintesisNumerica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Síntesis numérica de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Graficos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Representaciones gráficas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_02_tapaVariabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DESCRIBIR LO ALEATORIO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_variablesAleatorias.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variables aleatorias</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_distribucionesProbabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Distribuciones de probabilidad</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_03_tapaMuestraPoblacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DE LA MUESTRA A LA POBLACIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_muestreo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Muestreo. Encuestas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_estimacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estimación de características de la población</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_04_tapaSignificativo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ESTADÍSTICAMENTE SIGNIFICATIVO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_contrasteHipotesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Contraste de hipótesis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_algunosTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Algunos test clásicos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_05_tapaCorrelacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CORRELACIÓN Y REGRESIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_relacionLineal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Medidas de relación lineal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_regreSimple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regresión simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_regreMultiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Regresión Múltiple</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_06_tapaEpilogo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EPÍLOGO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_Epilogo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Datos frente a opiniones</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#variables-aleatorias-discretas" id="toc-variables-aleatorias-discretas" class="nav-link active" data-scroll-target="#variables-aleatorias-discretas"><span class="header-section-number">4.1</span> Variables aleatorias discretas</a></li>
  <li><a href="#variables-aleatorias-continuas" id="toc-variables-aleatorias-continuas" class="nav-link" data-scroll-target="#variables-aleatorias-continuas"><span class="header-section-number">4.2</span> Variables aleatorias continuas</a>
  <ul class="collapse">
  <li><a href="#de-la-frecuencia-a-la-densidad-de-frecuencia" id="toc-de-la-frecuencia-a-la-densidad-de-frecuencia" class="nav-link" data-scroll-target="#de-la-frecuencia-a-la-densidad-de-frecuencia">De la frecuencia a la densidad de frecuencia</a></li>
  <li><a href="#de-la-densidad-de-frecuencia-a-la-densidad-de-probabilidad" id="toc-de-la-densidad-de-frecuencia-a-la-densidad-de-probabilidad" class="nav-link" data-scroll-target="#de-la-densidad-de-frecuencia-a-la-densidad-de-probabilidad">De la densidad de frecuencia a la densidad de probabilidad</a></li>
  </ul></li>
  <li><a href="#esperanza-matemática-y-varianza-de-una-variable-aleatoria" id="toc-esperanza-matemática-y-varianza-de-una-variable-aleatoria" class="nav-link" data-scroll-target="#esperanza-matemática-y-varianza-de-una-variable-aleatoria"><span class="header-section-number">4.3</span> Esperanza matemática y varianza de una variable aleatoria</a>
  <ul class="collapse">
  <li><a href="#esperanza-matemática" id="toc-esperanza-matemática" class="nav-link" data-scroll-target="#esperanza-matemática">Esperanza matemática</a></li>
  <li><a href="#moda-y-mediana" id="toc-moda-y-mediana" class="nav-link" data-scroll-target="#moda-y-mediana">Moda y mediana</a></li>
  </ul></li>
  <li><a href="#operaciones-con-variables-aleatorias" id="toc-operaciones-con-variables-aleatorias" class="nav-link" data-scroll-target="#operaciones-con-variables-aleatorias"><span class="header-section-number">4.4</span> Operaciones con variables aleatorias</a>
  <ul class="collapse">
  <li><a href="#no-es-lo-mismo-sumar-k-veces-que-multiplicar-por-k" id="toc-no-es-lo-mismo-sumar-k-veces-que-multiplicar-por-k" class="nav-link" data-scroll-target="#no-es-lo-mismo-sumar-k-veces-que-multiplicar-por-k">No es lo mismo sumar <span class="math inline">\(k\)</span> veces que multiplicar por <span class="math inline">\(k\)</span></a></li>
  </ul></li>
  <li><a href="#cálculo-de-probabilidades" id="toc-cálculo-de-probabilidades" class="nav-link" data-scroll-target="#cálculo-de-probabilidades"><span class="header-section-number">4.5</span> Cálculo de probabilidades</a>
  <ul class="collapse">
  <li><a href="#casos-favorables-partido-por-casos-posibles-sí-pero-no-siempre" id="toc-casos-favorables-partido-por-casos-posibles-sí-pero-no-siempre" class="nav-link" data-scroll-target="#casos-favorables-partido-por-casos-posibles-sí-pero-no-siempre">Casos favorables partido por casos posibles: Sí pero no siempre</a></li>
  <li><a href="#probabilidad-de-que-ocurra-un-suceso-y-otro.-regla-de-la-y" id="toc-probabilidad-de-que-ocurra-un-suceso-y-otro.-regla-de-la-y" class="nav-link" data-scroll-target="#probabilidad-de-que-ocurra-un-suceso-y-otro.-regla-de-la-y">Probabilidad de que ocurra un suceso <em>y</em> otro. (Regla de la <em>y</em>)</a></li>
  <li><a href="#probabilidad-de-que-ocurra-un-suceso-u-otro.-regla-de-la-o" id="toc-probabilidad-de-que-ocurra-un-suceso-u-otro.-regla-de-la-o" class="nav-link" data-scroll-target="#probabilidad-de-que-ocurra-un-suceso-u-otro.-regla-de-la-o">Probabilidad de que ocurra un suceso <em>u</em> otro. (Regla de la <em>o</em>)</a></li>
  <li><a href="#cálculo-a-través-del-complementario" id="toc-cálculo-a-través-del-complementario" class="nav-link" data-scroll-target="#cálculo-a-través-del-complementario">Cálculo a través del complementario</a></li>
  <li><a href="#tres-ejercicios-no-triviales-para-practicar" id="toc-tres-ejercicios-no-triviales-para-practicar" class="nav-link" data-scroll-target="#tres-ejercicios-no-triviales-para-practicar">Tres ejercicios (no triviales) para practicar</a></li>
  </ul></li>
  <li><a href="#apéndice-4.a-variabilidad-en-resistencias-eléctricas-consecuencias-inesperadas" id="toc-apéndice-4.a-variabilidad-en-resistencias-eléctricas-consecuencias-inesperadas" class="nav-link" data-scroll-target="#apéndice-4.a-variabilidad-en-resistencias-eléctricas-consecuencias-inesperadas">Apéndice 4.A: Variabilidad en resistencias eléctricas: Consecuencias inesperadas</a></li>
  <li><a href="#apéndice-4.b-esperanza-matemática-para-reparto-justo" id="toc-apéndice-4.b-esperanza-matemática-para-reparto-justo" class="nav-link" data-scroll-target="#apéndice-4.b-esperanza-matemática-para-reparto-justo">Apéndice 4.B: Esperanza matemática para reparto justo</a></li>
  <li><a href="#apéndice-4.c-probabilidades-y-paradojas" id="toc-apéndice-4.c-probabilidades-y-paradojas" class="nav-link" data-scroll-target="#apéndice-4.c-probabilidades-y-paradojas">Apéndice 4.C: Probabilidades y paradojas</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0_02_tapaVariabilidad.html">DESCRIBIR LO ALEATORIO</a></li><li class="breadcrumb-item"><a href="./04_variablesAleatorias.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variables aleatorias</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variables aleatorias</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Decimos que una variable es aleatoria cuando el valor que toma está afectado –en mayor o menor medida– por el azar<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>Cuando queremos poner un ejemplo de este tipo de variables los primeros que se nos ocurren son los relacionados con los juegos de azar: la suma de los resultados al lanzar dos dados o el número de caras al lanzar cinco veces una moneda al aire, pero el azar no solo está en el mundo del juego.</p>
<p>En el contexto de los análisis estadísticos, cuando estimamos las características de una población a través de una muestra, los valores obtenidos presentan variabilidad ya que dependen de los elementos que –por casualidad– hayan caído en la muestra. En este terreno siempre nos movemos entre variables aleatorias y debemos conocer sus características y las reglas que nos permiten trabajar con ellas.</p>
<p>Para describir su comportamiento, vamos a dividirlas en dos grandes tipos que estudiaremos por separado: las variables aleatorias discretas y las continuas.<br> <span style="display:block; margin-top:35px;"></span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Notación
</div>
</div>
<div class="callout-body-container callout-body">
<p>En general, las variables aleatorias se designan con letras mayúsculas y los valores que pueden tomar se designan esa misma letra en minúscula. En la expresión <span class="math inline">\(P(X&gt;x)\)</span>, la <span class="math inline">\(X\)</span> mayúscula representa una variable aleatoria –podría ser el número de correos electrónicos que recibimos en un día– y la <span class="math inline">\(x\)</span> minúscula, un número concreto –por ejemplo, 10–.</p>
</div>
</div>
<div style="height: 18px;">

</div>
<section id="variables-aleatorias-discretas" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="variables-aleatorias-discretas"><span class="header-section-number">4.1</span> Variables aleatorias discretas</h2>
<p>Una variable aleatoria es discreta cuando solo puede tomar valores aislados, de manera que, fijados dos valores consecutivos no puede haber ningún otro entre ellos. Ejemplos de variables aleatorias discretas son:</p>
<ul>
<li><p>El número de pasajeros que tienen billete pero no se presentan a la salida de su vuelo. Si se han vendido <span class="math inline">\(n\)</span> billetes, los valores que puede tomar son: <span class="math inline">\(0, 1, \cdots, n\)</span>, aunque a partir de un cierto número, la probabilidad de que se dé ese valor es prácticamente igual a cero.</p></li>
<li><p>El número de personas que se declaran &lt;<de izquierdas="">&gt; en una muestra de 100. Puede tomar valores desde 0 hasta 100, aunque serán muy poco probables los valores muy pequeños o muy grandes dentro de ese rango.</de></p></li>
<li><p>El número de veces que una línea de producción se para por causas imprevistas durante una semana. Puede ir desde cero hasta un máximo que no está definido.</p></li>
<li><p>El número de pasas que aparecen en una cucharada de muesli. También puede tomar valores desde cero hasta un máximo no definido.</p></li>
<li><p>La suma de los valores que se obtienen al lanzar dos dados. Puede ir de 2 a 12 y serán más probables los valores centrales.</p></li>
</ul>
<p>En este último ejemplo es muy fácil calcular las probabilidades asociadas a cada valor, son las que se indican en la <a href="#tbl-sumaDados">Tabla 4.1</a>.</p>
<div id="tbl-sumaDados" class="tabla-wrapper35b anchored">

<table class="tabla-0401 caption-top table">
<caption>Tabla 4.1: Valores que puede tomar la variable aleatoria <em>S</em>: suma de resultados al lanzar dos dados, con su probabilidad de aparición.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Valores de (<em>s</em>):</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">11</th>
<th data-quarto-table-cell-role="th">12</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P(<em>S</em> = <em>s</em>):</td>
<td><sup>1</sup>/<sub>36</sub></td>
<td><sup>2</sup>/<sub>36</sub></td>
<td><sup>3</sup>/<sub>36</sub></td>
<td><sup>4</sup>/<sub>36</sub></td>
<td><sup>5</sup>/<sub>36</sub></td>
<td><sup>6</sup>/<sub>36</sub></td>
<td><sup>5</sup>/<sub>36</sub></td>
<td><sup>4</sup>/<sub>36</sub></td>
<td><sup>3</sup>/<sub>36</sub></td>
<td><sup>2</sup>/<sub>36</sub></td>
<td><sup>1</sup>/<sub>36</sub></td>
</tr>
</tbody>
</table>

</div>
<p>Una variable aleatoria discreta se puede definir mediante una tabla como la que acabamos de ver o –de una manera más compacta pero no siempre más clara– dando la función que relaciona cada uno de estos valores con sus respectivas probabilidades. Esta función se llama <strong>función de probabilidad</strong>. En nuestro caso podemos escribir: <span class="math display">\[ P(S = s) = \frac {6 \, - \lvert s - 7 \rvert} {36}  \;\;\; \text {para} \;\; s = 2, 3, 4, \dotsb, 12.\]</span></p>
<p>Observe que si la variable puede tomar <span class="math inline">\(n\)</span> valores distintos seguro que: <span class="math display">\[\sum_{i=1}^{n} P(X=x_i)=1\]</span></p>
<p>Si esta igualdad no se cumple es que la variable no está bien definida.</p>
<div style="height: 3px;">

</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Una variable aleatoria discreta también puede tomar infinitos valores
</div>
</div>
<div class="callout-body-container callout-body">
<p>En teoria, claro, porque en la práctica no hay infinitos. Podemos pensar en una variable aleatoria definida para todos los números naturales de manera que al número <span class="math inline">\(n\)</span> le correspoponda una probabilidad <span class="math inline">\(P(n) = 1/2^n\)</span> puesto que <span class="math inline">\(\sum_{n=1}^{\infty}\frac {1}{2^n}=1\)</span>.</p>
</div>
</div>
<div style="height: 12px;">

</div>
<p>Una forma clara de visualizar las características de una variable aleatoria discreta es representar su función de probabilidad. En la <a href="#fig-ejemplosFuncionProbabilidad" class="quarto-xref">Figura&nbsp;<span>4.1</span></a>) (izquierda), la variable aleatoria es el número de pasajeros que no se presentan a la salida de su vuelo si se han vendido <span class="math inline">\(n=180\)</span> billetes y la probabilidad de que un pasajero no se presente es <span class="math inline">\(p=0.01\)</span>. En la figura de la derecha, la variable es el número de paradas por causas imprevistas que se producen en una línea de producción durante una semana laboral (5 días) sabiendo que, por esas causas, se para en promedio una vez cada dos días.</p>
<div id="fig-ejemplosFuncionProbabilidad" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ejemplosFuncionProbabilidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0401_ejemplosFuncionProbabilidad.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ejemplosFuncionProbabilidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.1: Representación de funciones de probabilidad de variables discretas.
</figcaption>
</figure>
</div>
<p>En el siguiente capítulo veremos que calcular estas probabilidades es mucho más fácil de lo que parece.</p>
</section>
<section id="variables-aleatorias-continuas" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="variables-aleatorias-continuas"><span class="header-section-number">4.2</span> Variables aleatorias continuas</h2>
<p>Decimos que una variable aleatoria es continua cuando puede tomar cualquier valor dentro de un intervalo. Son variables aleatorias continuas:</p>
<ul>
<li><p>La duración de un componente electrónico.</p></li>
<li><p>El peso de los frutos que da un árbol en una cosecha.</p></li>
<li><p>La longitud de una pieza que debe ensamblarse con otras para formar un mecanismo.</p></li>
<li><p>El tiempo que transcurre entre la llegada de dos personas a la cola del cajero de un supermercado.</p></li>
<li><p>El valor que da una hoja de cálculo cuando se le pide un número aleatorio.</p></li>
</ul>
<p>Podemos decir que –en general– el valor de las variables aleatorias discretas “se cuenta”, mientras que el de las continuas “se mide”.</p>
<p>La caracterización de una variable aleatoria continua no se puede realizar como en las discretas, asignando una probabilidad a cada uno de los valores que puede tomar, ya que en este caso la probabilidad de que tome un valor concreto –con infinitos decimales– siempre es igual a cero, tal como veremos más adelante<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p>Las variables aleatorias continuas se definen utilizando la llamada <strong>función densidad de probabilidad</strong>. Para ver cómo se construye y cómo se utiliza esta función vamos a recorrer el camino que va desde el histograma de unos datos hasta la representación de la población de la que provienen.</p>
<section id="de-la-frecuencia-a-la-densidad-de-frecuencia" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="de-la-frecuencia-a-la-densidad-de-frecuencia">De la frecuencia a la densidad de frecuencia</h3>
<p>Al construir un histograma lo habitual es colocar la frecuencia –absoluta o relativa– en el eje vertical, pero también se puede usar la <strong>densidad de frecuencia</strong><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<p>Para cada intervalo <span class="math inline">\(i\)</span> la densidad de frecuencia <span class="math inline">\(f_i^*\)</span> es igual a la frecuencia relativa <span class="math inline">\(f_i\)</span> dividida por la anchura del intervalo <span class="math inline">\(c_i\)</span>. Es decir: <span class="math inline">\(f_i^\ast= f_i/c_i\)</span>. De esta forma el área de cada barra (base<span class="math inline">\(\times\)</span>altura: <span class="math inline">\(c_i\cdot f_i/c_i\)</span>) es igual a la frecuencia relativa correspondiente a su intervalo.</p>
<p>Supongamos que tenemos una muestra de 5000 valores de una variable aleatoria <span class="math inline">\(X\)</span>. En el lado izquierdo de la <a href="#fig-densidadDeFrecuencia" class="quarto-xref">Figura&nbsp;<span>4.2</span></a>) hemos representado su histograma “clásico”, con la frecuencia absoluta en el eje de ordenadas. Si tuviera una escala más detallada podríamos ver que, por ejemplo, entre 0,5 y 0,6 tenemos 295 observaciones. La frecuencia relativa en este intervalo es igual a 295/5000 = 0,059.</p>
<p>En el lado derecho tenemos el mismo histograma pero con la densidad de frecuencia. Es inmediato deducir que su valor entre 0,5 y 0,6 es igual a 0,59, que multiplicado por la anchura del intervalo (0,1) nos da la frecuencia relativa y también el área de esa barra. La suma de las frecuencias relativas debe ser igual a 1 y, por tanto, también la suma de las áreas de todas las barras.</p>
<div id="fig-densidadDeFrecuencia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-densidadDeFrecuencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0402_densidadDeFrecuencia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-densidadDeFrecuencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.2: Histograma con frecuencias absolutas (izquierda) y con densidad de frecuencia (derecha).
</figcaption>
</figure>
</div>
</section>
<section id="de-la-densidad-de-frecuencia-a-la-densidad-de-probabilidad" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="de-la-densidad-de-frecuencia-a-la-densidad-de-probabilidad">De la densidad de frecuencia a la densidad de probabilidad</h3>
<p>Está claro que si en el eje de ordenadas tenemos la densidad de frecuencia, el cálculo de la frecuencia relativa se convierte en un cálculo de áreas. En la <a href="#fig-areasProbabilidades" class="quarto-xref">Figura&nbsp;<span>4.3</span></a> (izquierda), el área de la zona sombreada es igual a la frecuencia relativa entre 0,5 y 1,5. En la derecha hemos superpuesto dos líneas que parece razonable considerar que representan a la población de la que provienen esos datos. La función que describe esas líneas es la . Respecto a las muestras hablamos de <strong>frecuencia</strong>, mientras que en el contexto de las poblaciones, usamos el término <strong>probabilidad</strong>.</p>
<div id="fig-areasProbabilidades" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-areasProbabilidades-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0403_areasProbabilidades.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-areasProbabilidades-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.3: Histograma con frecuencias absolutas (izquierda) y con densidad de frecuencia (derecha).
</figcaption>
</figure>
</div>
<p>En este caso, la función densidad de probabilidad <span class="math inline">\(f(x)\)</span> es: <span class="math display">\[\begin{equation*}
    f(x) = \left \{
    \begin{aligned}
        x\;\; &amp; \quad\text{para}\;\; 0&lt;x \leq 1 \\
        2-x &amp; \quad\text{para}\;\; 1&lt;x \leq 2
    \end{aligned}
    \right.
\end{equation*}\]</span></p>
<p>En la muestra, la frecuencia relativa entre 0,5 y 1,5 es igual al área de las barras que se encuentran entre esos valores. Para la población, la probabilidad de que $ X $ se encuentre en ese intervalo es igual al área que definida en el triángulo. Esta área se puede calcular haciendo: <span class="math display">\[P(0,5 \leq x \leq 1,5) = \int_{0,5}^1 x \; dx + \int_1^{1,5}(2-x) \; dx =\frac{3}{4}\]</span></p>
<p>Si la función densidad de probabilidad tiene una forma tan sencilla como la que acabamos de ver, podemos calcular las áreas haciendo integrales o también aplicando reglas de geometría. La probabilidad de tener valores mayores de 1,5 es: <span class="math display">\[P(X &gt; 1.5) = \int_{1.5}^{2}(2-x) \; dx = 0.125\]</span></p>
<p>Pero también, observando que la altura del triángulo para <span class="math inline">\(x=1.5\)</span> es igual a 0,5, el área entre 1,5 y 2 será: <span class="math inline">\(0.5 \times 0.5/2 = 0.125\)</span>.</p>
<p>Si la expresión de <span class="math inline">\(f(x)\)</span> es más complicada –que es lo que suele ocurrir en la práctica–, el cálculo de las áreas puede ser más laborioso, pero el planteamiento es exactamente el mismo.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Función densidad de probabilidad
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para que una función pueda ser considerada debe cumplir dos condiciones: que tome únicamente valores no negativos (es decir, positivos o cero) y que la integral en el intervalo en que está definida sea igual a 1.</p>
</div>
</div>
</section>
</section>
<section id="esperanza-matemática-y-varianza-de-una-variable-aleatoria" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="esperanza-matemática-y-varianza-de-una-variable-aleatoria"><span class="header-section-number">4.3</span> Esperanza matemática y varianza de una variable aleatoria</h2>
<p>De la misma forma que la media y la desviación típica (o la varianza) son un buen resumen de las características de un conjunto de datos, en el caso de las variables aleatorias tenemos unos valores análogos: la esperanza matemática y la varianza. Vamos a ver cómo se calculan y cuáles son sus características, primero para las variables discretas y después para las continuas.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Promedio, media y esperanza matemática
</div>
</div>
<div class="callout-body-container callout-body">
<p>A la <em>media</em> aritmética de un conjunto de datos también le podemos llamar <em>promedio</em>. Respecto a una variable aleatoria, los términos <em>media</em> y <em>esperanza matemática</em> son equivalentes. <em>Media</em> sirve en los dos casos.</p>
</div>
</div>
<section id="esperanza-matemática" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="esperanza-matemática">Esperanza matemática</h3>
<section id="variables-aleatorias-discretas-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="variables-aleatorias-discretas-1">Variables aleatorias discretas</h4>
<p>Recordemos que si tenemos una muestra con <span class="math inline">\(k\)</span> valores distintos, cada uno de ellos con una frecuencia relativa <span class="math inline">\(f_i\)</span> podemos calcular su media mediante la expresión: <span class="math display">\[\bar{x} = \sum_{i=1}^k x_i \, f_i\]</span> Si lo que tenemos es una variable aleatoria <span class="math inline">\(X\)</span>, su media o esperanza matemática <span class="math inline">\(\text{E}(X)\)</span> tiene una expresión similar a la anterior, pero en este caso no hablamos de frecuencias sino de probabilidades:</p>
<p><span class="math display">\[\text{E}(X) = \sum_{i=1}^k  x_i \, p(x_i)\]</span> En el caso que habíamos comentado de la variable aleatoria <span class="math inline">\(S\)</span>: suma de los resultados obtenidos al lanzar dos dados (<a href="#tbl-sumaDados">Tabla 4.1</a>) su esperanza matemática es: <span class="math display">\[ \text{E}(S) = \sum_{i=1}^{11} s_i \, p(s_i)   = 2 \cdot \frac{1}{36} + 3\cdot\frac{2}{36} + \dotsm + 11\cdot\frac{2}{36} + 12\cdot\frac{1}{36} = 7\]</span> En un juego de azar, la esperanza matemática de beneficio es el que se obtendría en promedio si se jugara muchas veces. Si el que organiza el juego no se ha equivocado, esa esperanza matemática seguro que será negativa. Supongamos que se realiza una rifa con 10.000 boletos numerados que se venden a un euro y con los siguientes premios:</p>
<div class="tabla-wrapper00">

<table class="tabla-02Ape2D_1 caption-top table">
<tbody>
<tr class="odd">
<td>1º: 400 €</td>
</tr>
<tr class="even">
<td>2º: 200 €</td>
</tr>
<tr class="odd">
<td>3º: 100 €</td>
</tr>
</tbody>
</table>

</div>
<p>¿Cuál es la esperanza matemática de beneficio si se compra uno de estos boletos? Los valores que puede tomar la variable aleatoria “beneficio” (es una variable aleatoria puesto que su valor depende del azar) son los que se indican en la <a href="#tbl-Juego">Tabla 4.2</a>.</p>
<div id="tbl-Juego" ;="" class="tabla-wrapper42 anchored">

<table class="tabla-0212 caption-top table">
<caption>Tabla 4.2: Valores para el cálculo de la esperanza matemática del beneficio</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Beneficio (<em>x</em>)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Probabilidad (<em>P(x)</em>)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th"><em>x · P(x)</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">399 €<br>
199 €<br>
99 €<br>
-1 €</td>
<td style="text-align: center;">0,0001<br>
0,0001<br>
0,0001<br>
0.9997</td>
<td style="text-align: center;">0,0399 €<br>
0.0199 €<br>
0.0099 €<br>
-0,9997 €</td>
</tr>
<tr class="total even">
<td style="text-align: center;">Suma...</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0,93 €</td>
</tr>
</tbody>
</table>

</div>
<p>Tenemos que <span class="math inline">\(\text{E}(X) = -0.93\)</span> € por tanto, en promedio, perderemos 0,93 € por cada boleto que compremos. Si los compráramos todos nos costarían 10.000 € y nos tocarán 700, habríamos perdido 9.300 €, exactamente 0,93 por boleto.</p>
</section>
<section id="variables-aleatorias-continuas-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="variables-aleatorias-continuas-1">Variables aleatorias continuas</h4>
<p>Se calcula mediante una expresión análoga a la que hemos visto para las variables discretas, cambiando el sumatorio por una integral y la probabilidad <span class="math inline">\(p(x)\)</span> por <span class="math inline">\(f(x)\,\mathrm{d}x\)</span>. Tenemos: <span class="math display">\[\text{E}(X) = \int_{-\infty}^{\infty} x \, f(x) \, \mathrm{d}x\]</span> Observe que <span class="math inline">\(f(x)\)</span> no es una probabilidad (es una densidad de probabilidad) pero multiplicada por <span class="math inline">\(\mathrm{d}x\)</span> ya pasa a serlo. Si la distribución es simétrica, la esperanza matemática coincide con el valor de <span class="math inline">\(X\)</span> situado en el eje de simetría. En el caso de la distribución triangular que hemos visto anteriormente (<a href="#fig-areasProbabilidades" class="quarto-xref">Figura&nbsp;<span>4.3</span></a>), podemos asegurar que <span class="math inline">\(\text{E}(X)=1\)</span> sin necesidad de hacer ningún cálculo.</p>
<p>Si la distribución no es simétrica, como en la figura <a href="#fig-ejercicio" class="quarto-xref">Figura&nbsp;<span>4.4</span></a>, el cálculo ya no es tan inmediato.</p>
<div id="fig-ejercicio" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ejercicio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0404_ejercicio.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ejercicio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.4: Función densidad de probabilidad con forma triangular.
</figcaption>
</figure>
</div>
<p>Esta función se puede escribir de la forma:</p>
<span class="math display">\[\begin{equation*}
    f(x) = \left \{
    \begin{aligned}
        \frac{x}{10}\;\; &amp; \quad\text{para}\;\; 0&lt;x \leq 4 \\
        2-0.4x &amp; \quad\text{para}\;\; 4&lt;x \leq 5
    \end{aligned}
    \right.
\end{equation*}\]</span>
<p>Podemos comprobar que está bien definida: siempre toma valores positivos y el área que define es igual a 1. Su esperanza matemática es: <span class="math display">\[\text{E}(X) = \int_{0}^{4} x \frac{x}{10} \,\mathrm{d}x + \int_{4}^{5} x (2 -0.4x) \,\mathrm{d}x = 3\]</span></p>
<div style="height: 3px;">

</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Esperanza matemática en una distribución triangular
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si una variable aleatoria <span class="math inline">\(X\)</span> tiene distribución triangular definida en el intervalo <span class="math inline">\((a, b)\)</span> y su valor máximo está en <span class="math inline">\(c\)</span>, su esperanza matemática es <span class="math inline">\(\text{E}(X) = \frac{a+b+c}{3}\)</span>. Así de sencillo. Si tiene tiempo puede entretenerse en demostrarlo<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
</div>
</div>
<div style="height: 3px;">

</div>
</section>
<section id="varianza" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="varianza">Varianza</h4>
<p>También se calcula con una expresión similar a la que usamos para calcular la varianza de una muestra. Si se trata de una variable aleatoria discreta, solo cambiamos la media de la muestra por la esperanza matemática de la población y la frecuencia relativa por la probabilidad, es decir: <span class="math display">\[\text{V}(X) = \sum_{i=1}^k  [x_i - \text{E}(X)]^2 \, p(x_i)\]</span> Para el cálculo de la varianza del beneficio tenemos los valores de la tabla <span class="math inline">\(\ref{varBeneficio}\)</span>:</p>
<div id="tbl-Juego" ;="" class="tabla-wrapper42 anchored">

<table class="tabla-0402 caption-top table">
<caption>Tabla 4.3: Valores para el cálculo de la varianza del beneficio</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">$$x$$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$$P(x)$$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$$[x - \text{E}(x)]^2$$</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">$$[x - \text{E}(x)]^2 \cdot P(x)$$</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">399 €<br>
199 €<br>
99 €<br>
-1 €</td>
<td style="text-align: center;">0,0001<br>
0,0001<br>
0,0001<br>
0.9997</td>
<td style="text-align: center;">159944,005<br>
39972,0049<br>
9986,0049 €<br>
0,0049</td>
<td style="text-align: center;">15,9944 €<sup>2</sup><br>
3,9972 €<sup>2</sup><br>
0,9986 €<sup>2</sup><br>
0,0049 €<sup>2</sup></td>
</tr>
<tr class="total even">
<td style="text-align: center;">Suma...</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">20,9951 €<sup>2</sup></td>
</tr>
</tbody>
</table>

</div>
<p>El resultado, V(<i>X</i>)=20.9951 €<sup>2</sup>, es la varianza de los valores del beneficio que se obtendría con cada boleto si los compramos todos.</p>
<p>De forma análoga, para las variables aleatorias continuas tenemos: <span class="math display">\[\text{V}(X) = \int_{-\infty}^{\infty} [x - \text{E}(X)]^2 \, f(x) \, \mathrm{d}x\]</span> En la distribución de la <a href="#fig-ejercicio" class="quarto-xref">Figura&nbsp;<span>4.4</span></a> tenemos:</p>
<p><span class="math display">\[ \text{V}(X) = \int_{0}^{4} (x-3)^2 \frac{x}{10} \, \mathrm{d}x + \int_{4}^{5} (x-3)^2  (2 -0.4x) \, \mathrm{d}x = \frac{7}{6}\]</span> Ciertamente, este valor de la varianza no nos dice nada<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>, pero lo podemos comparar con el que se obtiene para la distribución de la <a href="#fig-areasProbabilidades" class="quarto-xref">Figura&nbsp;<span>4.3</span></a> que deberá ser menor, al ser también menor el rango en que se mueve. En este caso, como <span class="math inline">\(E(X)=1\)</span>, tenemos:</p>
<p><span class="math display">\[\text{V}(X) = \int_{0}^{1} (x-1)^2 x \, \mathrm{d}x + \int_{1}^{2} (x-1)^2  (2 -x) \, \mathrm{d}x = \frac{1}{6}\]</span> Efectivamente es menor, exactamente siete veces menor.</p>
</section>
</section>
<section id="moda-y-mediana" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="moda-y-mediana">Moda y mediana</h3>
<p>A veces nos referimos a la moda, la mediana, los cuartiles o, en general, los percentiles de una variable aleatoria. Es más habitual usarlo para las continuas, por lo que solo nos referimos a estas.</p>
<p>La moda es el valor de <span class="math inline">\(x\)</span> para el cual <span class="math inline">\(f(x)\)</span> tiene un máximo. Si existen dos máximos, se dice que es una distribución bimodal. En los ejemplos que hemos visto, las modas son 1 (<a href="#fig-areasProbabilidades" class="quarto-xref">Figura&nbsp;<span>4.3</span></a>) y 4 (<a href="#fig-ejercicio" class="quarto-xref">Figura&nbsp;<span>4.4</span></a>).</p>
<p>La mediana es el valor que tiene una probabilidad del 50% de ser superado. Si la distribución es simétrica, la mediana coincide con la esperanza matemática; así pues, en el primer ejemplo la mediana es igual a 1.</p>
<p>En el segundo ejemplo no es evidente cuál es ese valor, pero a la vista de la geometría de la distribución podemos asegurar que será menor que 4 y por tanto nos centramos en la primera parte de la expresión. Podemos escribir: <span class="math display">\[\int_{0}^{Me} \frac{x}{10} \, \mathrm{d}x = 0.5\]</span> Y de esta expresión despejamos el valor de la mediana, obteniendo <span class="math inline">\(Me = \sqrt{10}\)</span>.</p>
<p>Si la forma de la distribución de probabilidad es geométricamente sencilla, este cálculo también se puede realizar aplicando reglas de geometría. Por ejemplo, el primer cuartil <span class="math inline">\(Q_1\)</span> verificará: <span class="math display">\[ \frac{Q_1 \cdot f(Q_1)}{2} = 0.25 \]</span> Es decir, <span class="math inline">\(Q_1 \cdot \frac{Q_1}{10} = 0.5\)</span>, luego <span class="math inline">\(Q_1 = \sqrt{5}\)</span>.</p>
</section>
</section>
<section id="operaciones-con-variables-aleatorias" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="operaciones-con-variables-aleatorias"><span class="header-section-number">4.4</span> Operaciones con variables aleatorias</h2>
<p>Vamos a dar algunas reglas que nos serán útiles para realizar cálculos o para justificar algunas de las expresiones que utilizaremos más adelante. No importa si la variable es discreta o continua. Si <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span> son constantes y <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span> son variables aleatorias, se verifica:</p>
<ul>
<li><p><span class="math inline">\(\text{E}(a+bX) = a+b \cdot \text{E}(X)\)</span></p></li>
<li><p><span class="math inline">\(\text{V}(a+bX) = b^2 \cdot \text{V}(X)\)</span></p></li>
<li><p><span class="math inline">\(\text{E}(X+Y) = \text{E}(X) + \text{E}(Y)\)</span></p></li>
<li><p><span class="math inline">\(\text{V}(X+Y) = \text{V}(X) + \text{V}(Y) + 2\,\text{Cov}(X,Y)\)</span></p></li>
<li><p><span class="math inline">\(\text{V}(X-Y) = \text{V}(X) + \text{V}(Y) - 2\,\text{Cov}(X,Y)\)</span> <br> <span style="display:block; margin-top:35px;"></span></p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Si X e Y son independientes: V(X+Y) = V(X-Y)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Puede comprobarlo generando números aleatorios en una columna de una hoja de cálculo; en la columna de al lado, genere otros tantos de la misma o de otra distribución. Puede comprobar que la varianza de la suma de esas dos columnas es muy parecida a la varianza de la diferencia. Será tanto más parecida cuanto más números haya generado. En la mayoría de las hojas de cálculo pulsando F9, se renuevan los números aleatorios.</p>
</div>
</div>
<p><br> <span style="display:block; margin-top:-35px;"></span></p>
<section id="no-es-lo-mismo-sumar-k-veces-que-multiplicar-por-k" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="no-es-lo-mismo-sumar-k-veces-que-multiplicar-por-k">No es lo mismo sumar <span class="math inline">\(k\)</span> veces que multiplicar por <span class="math inline">\(k\)</span></h3>
<p>El resultado es el mismo cuando las cantidades a que nos referimos son magnitudes constantes. Para saber cuántos huevos hay en 8 docenas, como el número de huevos en una docena es una constante, podemos sumar 12 huevos 8 veces o multiplicar 12 por 8 (¡evidente!). Pero, si lo que tenemos es una variable aleatoria, como el peso de un huevo, esto ya no es verdad.</p>
<p>No es lo mismo el peso de una docena de huevos que el peso de un huevo multiplicado por 12 porque, aunque estas dos variables tienen la misma media, no tienen la misma variabilidad y, por tanto, no podemos decir que son iguales.</p>
<p>Para entender por qué esto es así, aclararemos en primer lugar el significado de la notación que vamos a utilizar. Llamaremos <span class="math inline">\(X\)</span> a la variable aleatoria que consideramos (en nuestro ejemplo es el peso de un huevo). Si tomamos una docena, designaremos los pesos como <span class="math inline">\(X_1, X_2, \ldots, X_{12}\)</span>. Cada una de las <span class="math inline">\(X_i\)</span> es una variable aleatoria con la misma distribución que <span class="math inline">\(X\)</span>. En realidad, son extracciones de la misma población, el subíndice sólo indica el orden en que se extraen.</p>
<p>Echando mano de las fórmulas correspondientes y suponiendo que los 12 pesos son independientes, tendremos que la esperanza matemática y la varianza del peso de una docena serán:</p>
<span class="math display">\[\begin{equation*}
    \begin{split}
        \text{E}(X_1+X_2+\ldots+X_{12}) &amp;= \text{E}(X_1)+ \ldots + \text{E}(X_{12})=12 \cdot \text{E}(X) \\[3pt]
        \text{V}(X_1+X_2+\ldots+X_{12}) &amp;= \text{V}(X_1)+ \ldots + \text{V}(X_{12})=12 \cdot \text{V}(X)
        \end{split}
\end{equation*}\]</span>
<p>Pensemos ahora en la variable “peso de un huevo multiplicado por 12”, es decir, la variable <span class="math inline">\(12X\)</span>. Ahora tendremos:</p>
<p><span class="math inline">\(\qquad \qquad \qquad \qquad \qquad \qquad \text{E}(12X)=12 \cdot \text{E}(X)\)</span> <span class="math inline">\(\qquad \qquad \qquad \qquad \qquad \qquad \text{V}(12X)=12^2 \cdot \text{V}(X)=144 \cdot \text{V}(X)\)</span></p>
<p>Vamos a ver que estas fórmulas reflejan lo que ocurre en la realidad a través de una mirada intuitiva al problema. Cuando formamos una docena de huevos, aunque tomemos uno singularmente pequeño, no hay que temer que esta docena salga con un peso muy por debajo del valor medio, ya que seguramente también habrá otros con un peso por encima de lo normal, de manera que los grandes compensarán el peso de los pequeños y viceversa (<a href="#fig-huevos1" class="quarto-xref">Figura&nbsp;<span>4.5</span></a>).</p>
<div id="fig-huevos1" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-huevos1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0405_huevos1.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-huevos1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.5: Una docena de huevos (exagerando las diferencias).
</figcaption>
</figure>
</div>
<p>Sin embargo, en la variable &lt;&lt;peso de un huevo multiplicado por 12&gt;&gt;, si el huevo elegido resulta ser pequeño, es como tener una docena de huevos pequeños, y si es grande sería como una docena de huevos grandes, con lo que tendremos pesos totales con más dispersión que en el caso anterior, ya que en este caso no se compensan los grandes con los pequeños (<a href="#fig-huevos2" class="quarto-xref">Figura&nbsp;<span>4.6</span></a>).</p>
<div id="fig-huevos2" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-huevos2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0406_huevos2.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-huevos2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.6: Un huevo multiplicado por 12. Si es pequeño es como tener una docena de huevos pequeños. Igual si es grande.
</figcaption>
</figure>
</div>
<p>Por tanto, tiene más dispersión la variable aleatoria “peso de un huevo multiplicado por 12” que la variable “peso de una docena”. Y si la variabilidad es distinta, las variables son distintas.</p>
</section>
</section>
<section id="cálculo-de-probabilidades" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="cálculo-de-probabilidades"><span class="header-section-number">4.5</span> Cálculo de probabilidades</h2>
<p>El cálculo de probabilidades es un terreno apasionante que permite entender las leyes que regulan los patrones que se presentan en el mundo del azar, o que pasen con más frecuencia unas cosas que otras sin razón aparente, observar curiosas paradojas y entender por qué ocurren. También es verdad que no sirve para aumentar las probabilidades de que nos toque la lotería y que, para muchas personas, resulta un tema enredado y muy poco intuitivo.</p>
<p>Si usted está entre estos últimos, no se preocupe. Para tener una visión general de la estadística y para manejar los conceptos y las técnicas más habituales no hace falta ser un experto en cálculo de probabilidades. Basta con tener algunas ideas claras. A continuación comentamos las que nos parecen más importantes.</p>
<section id="casos-favorables-partido-por-casos-posibles-sí-pero-no-siempre" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="casos-favorables-partido-por-casos-posibles-sí-pero-no-siempre">Casos favorables partido por casos posibles: Sí pero no siempre</h3>
<p>Esta famosa regla funciona cuando todos los casos tienen la misma probabilidad de ocurrir. Por ejemplo:</p>
<ul>
<li><p>Se realiza un sorteo para el que se venden 1000 boletos numerados. Si alguien ha comprado 5 de esos boletos, la probabilidad de que le toque es 5/1000 (todos los números tienen la misma probabilidad de salir).</p></li>
<li><p>En una oficina donde trabajan 40 personas van a elegir a 3 al azar para realizar una cierta actividad. La probabilidad de que le toque a un trabajador cualquiera es 3/40 (todos tienen la misma probabilidad de ser elegidos).</p></li>
<li><p>En una caja que contiene 50 piezas hay 3 defectuosas, si elegimos una al azar, la probabilidad de que sea la defectuosa es 3/50 (todas las piezas tienen la misma probabilidad de ser defectuosas).</p></li>
</ul>
<p>Pero si la probabilidad no es la misma para todos los casos posibles entonces no se puede aplicar esta regla, por ejemplo:</p>
<ul>
<li><p>Lanzamos dos dados: ¿cuál es la probabilidad de que la suma sea igual a 5? Antes hemos visto que existen 11 resultados posibles y 5 es uno de ellos, pero no todos tienen la misma probabilidad de ocurrir. Hemos visto en la tabla <span class="math inline">\(\ref{sumaDosDados}\)</span> que esta probabilidad es 1/9, no 1/11.</p></li>
<li><p>Una máquina produce un 40% de unidades defectuosas, si se toma una muestra de 10 unidades ¿cuál es la probabilidad de que se encuentren 3 defectos? Hay 11 casos posibles (encontrar 0, 1, 2,…, 10 unidades defectuosas) pero la probabilidad no es 1/11 sino 0,215, tal como veremos en el siguiente capítulo.</p></li>
<li><p>Hemos comprobado que el número de coches que llegan cada día a una gasolinera entre las 9 y las 10 de la mañana está entre 25 y 75, ¿cuál es la probabilidad de que un día lleguen entre 50 y 60? No es razonable considerar que todos los valores son igualmente probables. También en el capítulo siguiente veremos que –bajo unas hipótesis muy razonables– esa probabilidad está en torno a 0,45.</p></li>
</ul>
</section>
<section id="probabilidad-de-que-ocurra-un-suceso-y-otro.-regla-de-la-y" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="probabilidad-de-que-ocurra-un-suceso-y-otro.-regla-de-la-y">Probabilidad de que ocurra un suceso <em>y</em> otro. (Regla de la <em>y</em>)</h3>
<p>Es igual al producto de las probabilidades de que ocurra cada uno de ellos si la ocurrencia de uno no altera la probabilidad de ocurrencia del otro (decimos que son <strong>independientes</strong>). Veamos algunos ejemplos:</p>
<ul>
<li><p>Si el 40% de la población está a favor de una determinada política del gobierno y elegimos a 3 personas al azar, la probabilidad de que las tres estén a favor será igual a la probabilidad de que lo esté el primero <strong>y</strong> el segundo <strong>y</strong> el tercero, es decir: <span class="math inline">\(0.4^3 = 0.064\)</span>, <strong>pero</strong> si elegimos a tres personas del mismo grupo familiar esta regla ya no funciona porque los resultados no se pueden considerar independientes. Si uno está a favor es más probable que los otros también lo estén, porque los grupos familiares suelen tener un mismo perfil ideológico.</p></li>
<li><p>La probabilidad de que al lanzar dos veces una moneda salga cara y cara es <span class="math inline">\(0,5 \cdot 0,5\)</span> porque la probabilidad de que la segunda sea cara no está afectada por el resultado obtenido en la primera, pero si la probabilidad de sacar un as de una baraja es 1/12, la probabilidad de sacar dos ases no es <span class="math inline">\((1/12)^2\)</span> porque la probabilidad de que la segunda sea un as depende de si lo ha sido la primera.</p></li>
<li><p>En una zona llueve el 40% de los días. La probabilidad de que llueva dos días tomados al azar es <span class="math inline">\(0.4^2\)</span>, pero esa no es la probabilidad de que llueva dos días seguidos, porque la probabilidad de que llueva un día seguramente es mayor si ha llovido el día anterior.</p></li>
</ul>
</section>
<section id="probabilidad-de-que-ocurra-un-suceso-u-otro.-regla-de-la-o" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="probabilidad-de-que-ocurra-un-suceso-u-otro.-regla-de-la-o">Probabilidad de que ocurra un suceso <em>u</em> otro. (Regla de la <em>o</em>)</h3>
<p>Es la suma de las probabilidades de ocurrencia de cada uno de ellos, siempre y cuando no puedan ocurrir los dos a la vez, en cuyo caso habrá que restar esa probabilidad. Ejemplos:</p>
<ul>
<li><p>Un producto puede tener dos tipos de defecto, el A y el B, con <span class="math inline">\(P(A)=0.08\)</span> y <span class="math inline">\(P(B)=0.07\)</span>. Si ambos defectos son incompatibles (por ejemplo, o pesa mucho o pesa poco), la probabilidad de que una unidad sea defectuosa (tenga el defecto A o el B) es <span class="math inline">\(P(A)+P(B) = 0.15\)</span>. Supongamos ahora que sí puede tener los dos tipos de defecto (por ejemplo, sucio y rallado) y supongamos que las probabilidades son <span class="math inline">\(P(A)=0.6\)</span> y <span class="math inline">\(P(B)=0.7\)</span>. En este caso, la probabilidad de que un producto sea defectuoso es igual a <span class="math inline">\(P(A)+P(B) - P(A y B)= 0.88\)</span>. Con los números que hemos puesto no se nos puede olvidar restar la probabilidad de que ocurran los dos sucesos a la vez, porque si no lo hacemos la probabilidad saldría mayor que 1.</p></li>
<li><p>Elegimos una carta de la baraja, ¿cuál es la probabilidad de que sea de copas o de espadas? La probabilidad de que sea de copas es 1/4 y la misma que sea de espadas. Como no puede ser las dos cosas a la vez, la probabilidad de que sea de copas o de espadas es: 1/4 + 1/4 = 1/2. Pero, ¿cuál es la probabilidad de que sea un as o del palo de copas? La probabilidad de que sea un as es 1/12 y de que sea de copas 1/4, pero también puede ser las dos cosas a la vez con una probabilidad 1/48. Por tanto, la probabilidad buscada es: <span class="math inline">\(1/12 + 1/4 -1/48 = 15/48\)</span></p></li>
</ul>
</section>
<section id="cálculo-a-través-del-complementario" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="cálculo-a-través-del-complementario">Cálculo a través del complementario</h3>
<p>Si el conjunto de resultados posibles se puede dividir en dos grupos y la probabilidad de que esté es un grupo es <span class="math inline">\(p\)</span>, la probabilidad de que esté en el otro, al que llamamos complementario, es <span class="math inline">\(1-p\)</span>.</p>
<p>A veces es mucho más fácil calcular la probabilidad del complementario. Por ejemplo, ¿cuál es la probabilidad de que al lanzar 5 veces una moneda al aire salga alguna cara? Se podría calcular la probabilidad de que salga una, dos, tres, cuatro y cinco caras y sumar esos resultados, pero es más rápido calcular la probabilidad de que solo salgan cruces, que es <span class="math inline">\(0.5^5 = 0.03124\)</span>, por lo que la probabilidad buscada es: <span class="math inline">\(1-0,03124 = 0,96875\)</span>.</p>
<p>La probabilidad de que, siguiendo un cierto tratamiento, un enfermo se cure antes de un mes es del 10%. Si se aplica el tratamiento a un grupo de 10 enfermos, ¿cuál es la probabilidad de que alguno se cure antes de un mes? De forma análoga al ejemplo anterior, lo más fácil es calcular la probabilidad de que ninguno se cure: <span class="math inline">\(0.9^{10}\)</span> y el valor que buscamos será <span class="math inline">\(1 - 0,9^{10} = 0.65\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>El valor de la probabilidad
</div>
</div>
<div class="callout-body-container callout-body">
<p>La probabilidad se expresa como un número entre 0 y 1 (malas noticias si sus cálculos dan un número negativo o mayor que 1), aunque también se puede multiplicar por 100 y expresarlo en porcentaje.</p>
</div>
</div>
</section>
<section id="tres-ejercicios-no-triviales-para-practicar" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="tres-ejercicios-no-triviales-para-practicar">Tres ejercicios (no triviales) para practicar</h3>
<p>Una cosa es conocer las reglas y otra es identificar cuándo hay que aplicarlas.</p>
<p>Es muy fácil plantear ejercicios sobre estos temas y no nos hemos podido resistir a poner alguno. Si se entretiene en resolverlos le ayudarán a consolidar las ideas que hemos comentado. Encontrará las soluciones en las notas finales.</p>
<p><span style="color: #0038CF;"><strong>Ejercicio 1</strong></span>: La probabilidad de que una pieza sea defectuosa es 0,01, ¿cuál es la probabilidad de que en un lote de 100 piezas haya alguna defectuosa?<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>.</p>
<p><span style="color: #0038CF;"><strong>Ejercicio 2</strong></span>: Un juguete electrónico sale defectuoso con una probabilidad de 0,001. También existe una falsificación que ocupa una cuota de mercado del 10%, y la probabilidad de que la falsificación sea defectuosa es del 50%, ¿cuál es la probabilidad de que si se compra uno de estos juguetes salga defectuoso?<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
<p><span style="color: #0038CF;"><strong>Ejercicio 3</strong></span>: Una pieza puede tener dos tipos de defecto: el A con una probabilidad de 0,2 y el B con probabilidad 0,05. Ambos defectos son independientes, es decir, la ocurrencia de uno no afecta a la probabilidad de ocurrencia del otro. ¿Cuál es la probabilidad de que en un conjunto de 20 piezas haya alguna defectuosa (tenga el defecto A, el B o los dos)?<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>.</p>
</section>
</section>
<section id="apéndice-4.a-variabilidad-en-resistencias-eléctricas-consecuencias-inesperadas" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-4.a-variabilidad-en-resistencias-eléctricas-consecuencias-inesperadas">Apéndice 4.A: Variabilidad en resistencias eléctricas: Consecuencias inesperadas</h2>
<p>Estamos acostumbrados a considerar que las magnitudes con las que trabajamos toman el valor exacto que se les asigna o el que se deduce aplicando las fórmulas adecuadas. En el terreno de la física, la intensidad de la corriente <span class="math inline">\(I\)</span> que circula por un circuito formado por una fuente de alimentación <span class="math inline">\(V\)</span> y una resistencia <span class="math inline">\(R\)</span> es <span class="math inline">\(I=V/R\)</span> (ley de Ohm). Si nos dicen que <span class="math inline">\(V= 100\)</span> voltios y que <span class="math inline">\(R=10\)</span> ohmios, la intensidad será <span class="math inline">\(I= 10\)</span> amperios. No hay discusión.</p>
<p>Sin embargo, en la práctica no podemos evitar una cierta variabilidad añadida a los resultados que dan las fórmulas. Cuando tomamos una resistencia de una caja cuya etiqueta indica que son de 10 <span class="math inline">\(\Omega\)</span>, puede tener un valor real de 9,7 o de 10,4 <span class="math inline">\(\Omega\)</span> y, por tanto, la intensidad que circulará por nuestro circuito ya no será de 10 <span class="math inline">\(A\)</span>, sino de 10<span class="math inline">\(\,\pm \,\varepsilon\)</span> siendo <span class="math inline">\(\varepsilon\)</span> un valor que tiene que ver con el valor real de las variables que intervienen en la fórmula y quizá con el de otras variables que también influyen y que no se han tenido en cuenta. Puede ser que el valor de <span class="math inline">\(\varepsilon\)</span> sea irrelevante a efectos prácticos, pero también puede tener consecuencias importantes.</p>
<p>Supongamos que debemos construir muchos circuitos como el que hemos comentado y que la fuente de alimentación será siempre de 100 voltios, pero la resistencia para cada circuito la tomaremos de una caja donde el valor real de cada una de ellas será igual a <span class="math inline">\(R_n \pm 3\)</span> ohmios, siendo <span class="math inline">\(R_n\)</span> su valor nominal. Serán defectuosos los circuitos por los que circule una intensidad que esté fuera del intervalo 10 <span class="math inline">\(\pm\)</span> 3 amperios, ¿qué valor debemos elegir para <span class="math inline">\(R_n\)</span>?</p>
<p>Parece que si el objetivo es <span class="math inline">\(I = 10\,A\)</span> y tenemos <span class="math inline">\(V = 100\,V\)</span>, recordando la ley de Ohm, deberemos pedir las resistencias de <span class="math inline">\(R_n = V/I = 100V/10A = 10\,\Omega\)</span>, pero no es así. Para minimizar el número de defectos debemos pedir las resistencias con <span class="math inline">\(R_n = 11\,\Omega\)</span>.</p>
<p>El valor de <span class="math inline">\(R\)</span> que hace que circulen 7<span class="math inline">\(\,A\)</span> es <span class="math inline">\(R = V/I = 100V/7A = 14.3\,\Omega\)</span>, y para que circulen 13<span class="math inline">\(\,A\)</span> debe ser: <span class="math inline">\(R = V/I = 100V/13\,A = 7.7\,\Omega\)</span>. Si colocamos una resistencia de más de 14,3<span class="math inline">\(\,\Omega\)</span> pasarán menos de 7<span class="math inline">\(\,A\)</span> y el circuito será defectuoso. Por otro lado, si colocamos una de menos de 7,7<span class="math inline">\(\,\Omega\)</span> pasarán más de 13 <span class="math inline">\(A\)</span> y también será defectuoso. Debemos alejarnos de esos dos extremos y para ello lo mejor es pedir las resistencias con un valor nominal que esté en el centro de ese intervalo, es decir: <span class="math inline">\((7.7\,\Omega + 14.3\,\Omega)/2 = 11\,\Omega\)</span>.</p>
<div id="fig-circuito" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-circuito-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0407_circuito.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-circuito-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.7: El valor de <span class="math inline">\(R_n\)</span> no debe ser de 10 sino de 11<span class="math inline">\(\,\Omega\)</span>.
</figcaption>
</figure>
</div>
</section>
<section id="apéndice-4.b-esperanza-matemática-para-reparto-justo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-4.b-esperanza-matemática-para-reparto-justo">Apéndice 4.B: Esperanza matemática para reparto justo</h2>
<p>Una de las primeras discusiones sobre cálculo de probabilidades manejando conceptos matemáticos se encuentra en la correspondencia que mantuvieron Pascal y Fermat acerca de un problema planteado por el Chevalier de Méré, que trata sobre cómo repartir un premio entre dos jugadores si se lo debía llevar el primero en ganar un cierto número de partidas, pero hubiera que interrumpir el juego sin que ninguno de los dos hubiera llegado a ese valor<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>.</p>
<p>Supongamos que el premio es de 40 monedas, que se lo lleva el primero en ganar 3 partidas y que deben interrumpir el juego cuando el jugador A ha ganado dos partidas y el B solo una. ¿Cuál es la forma más razonable de repartir las monedas?</p>
<p>Una solución podría ser que se lo quede todo el que va ganando, o que se lo repartan a partes iguales, o de forma proporcional al número de partidas que ha ganado cada uno, pero supongamos que pueden seguir jugando y que la probabilidad de ganar una partida es la misma para los dos jugadores. El juego acabará de uno de los siguientes modos:</p>
<ol type="1">
<li><p>La siguiente partida la gana A. Como ya irán 3 a 1 el juego se acaba y A se lleva las 40 monedas. La probabilidad de que esto ocurra es de 0,5.</p></li>
<li><p>La siguiente partida la gana B, de manera que quedan 2 a 2 y siguen jugando. A continuación gana A, con lo que se ponen 3 a 2 a favor de A y termina el juego. La probabilidad de ir por este camino es 0,5·0,5 = 0,25 (gane B y gane A).</p></li>
<li><p>La siguiente partida la gana B y a continuación vuelve a ganar B. En este caso acaban 2 a 3 y B gana el juego. La probabilidad de que esto ocurra también es: 0,5·0,5 = 0,25.</p></li>
</ol>
<div id="fig-partida" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-partida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0408_partida.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-partida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.8: Posibles resultados si se siguiera jugando.
</figcaption>
</figure>
</div>
<p>Por tanto, si pudieran seguir jugando, la probabilidad de que ganara A sería 0,75 (0,50 + 0,25), mientras que para B sería 0,25. Podemos considerar que el premio es una variable aleatoria que puede tomar solo dos valores: 0 y 40. Si pudieran seguir jugando, la esperanza matemática del premio para cada jugador sería:</p>
<p><span class="math display">\[\begin{equation*}
    \begin{split}
        \text{para A}:\;\;\text{E}(P_A) &amp;= 40 \cdot 0.75 + 0 \cdot 0.25 = 30 \\
        \text{para B}:\;\;\text{E}(P_B) &amp;= 0 \cdot 0.75 + 40 \cdot 0.25 = 10
    \end{split}
\end{equation*}\]</span></p>
<p>Dicho de otro modo, si pudieran jugar muchas veces partiendo del resultado de <span class="math inline">\(2 - 1\)</span> a favor de A, en promedio A ganaría 30 monedas por partida y B solo 10. Es razonable que el reparto se haga de acuerdo con esas proporciones.</p>
</section>
<section id="apéndice-4.c-probabilidades-y-paradojas" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-4.c-probabilidades-y-paradojas">Apéndice 4.C: Probabilidades y paradojas</h2>
<p>Cuando debemos estudiar un tema del que no sabemos nada, decimos que partimos de cero. Este no es el caso del cálculo de probabilidades: partimos de un valor negativo.</p>
<p>Nuestra intuición nos sugiere respuestas que nos parecen muy claras pero que son falsas. Aprender a calcular probabilidades exige también hacer un esfuerzo para dejarse llevar por esa intuición. Daniel Kahneman, que fue premio nobel de economía, en su <em>bestselle</em>r* “Pensar rápido, pensar despacio” explica cómo a través de numerosos experimentos (que tienen mucho que ver con la estadística) realizados con su colega Amos Tversky pusieron de manifiesto como, ante la incertidumbre, nuestro cerebro no calcula probabilidades de una forma “racional” sino que aplica unas reglas o “atajos mentales” que a menudo conducen a evaluaciones erróneas.</p>
<p>Quizá su ejemplo más famoso es el que describe un personaje ficticio (Linda) y a continuación se plantea una pregunta sobre su ocupación actual:</p>
<blockquote class="blockquote">
<p>Linda estudió economía y siempre fue muy sensible a las injusticias sociales. En su época universitaria formó parte activa de la delegación de estudiantes y lideró varias protestas. Pasó varias temporadas realizando trabajos de voluntariado en países en vías de desarrollo.</p>
<p>Ahora Linda ronda los 40 años y lo más probable es que:</p>
<ol type="a">
<li>Trabaje en un banco.</li>
<li>Trabaje en un banco y sea activista en el movimiento feminista.</li>
</ol>
</blockquote>
<p>Ante esta pregunta un alto porcentaje de personas elige la opción b), aunque sabemos que la probabilidad de que ocurra una cosa otra es el producto de las probabilidades individuales y ese producto nunca puede ser mayor que ellas. Visto de otra forma, la opción b) exige que se cumpla la opción a) y que sea activista.</p>
<p>Otro ejemplo, debido al psicólogo Peter Watson y que recoge John Allen Paulos en “Un matemático lee el periódico”, dice:</p>
<blockquote class="blockquote">
Tenemos cuatro tarjetas con los símbolos A, D, 3 y 7 en una cara, y sabemos que todas ellas tienen un número en una cara y una letra en la otra. ¿Que tarjetas se deben girar para verificar que se cumple la regla: <em>si una tarjeta tiene una A en una cara, entonces tiene un 3 en la otra</em>?
</blockquote>
<p>La mayoría responde que la A y la 3, pero la 3 no hace falta girarla, porque no importa la letra que haya al otro lado. La que debe girarse es el 7 porque si en la otra cara tiene una A no se cumple la regla. En este caso el “atajo” nos hace confundir la implicación en un sentido (si tiene una A en una cara debe tener un 3 en la otra) con la implicación en sentido contrario (si tiene un 3 en una cara debe tener una A en la otra), pero esto último no es lo que se dice.</p>
<p>Una de las paradojas más conocidas es la llamada paradoja del cumpleaños: ¿Cuál es la probabilidad de que en un grupo de, pongamos, <span class="math inline">\(n =\)</span> 30 personas, dos o más celebren su cumpleaños el mismo día?</p>
<p>Este problema tiene un resultado mucho mayor del que intuitivamente se espera. Con <span class="math inline">\(n =\)</span> 23 ya está ligeramente por encima del 50%, con <span class="math inline">\(n =\)</span> 30 es del 71%, y con <span class="math inline">\(n =\)</span> 40 alcanza el 90%.</p>
<p>Para realizar los cálculos consideramos que un año tiene 365 días (ignoramos los bisiestos) y que la probabilidad de nacer es la misma para todos los días del año. Empezaremos calculando la probabilidad de que todos los integrantes de un grupo de <span class="math inline">\(n = 2, 3, \cdots\)</span> personas hayan nacido en días diferentes ((<a href="#tbl-Tabulacion">Tabla 4.1</a>)).</p>
<div id="tbl-Tabulacion" class="tabla-wrapper42 anchored">

<table class="tabla-0404 caption-top table">
<caption>Tabla 4.4: Probabilidad (<em>Q</em>) de que <em>n</em> personas hayan nacido en días diferentes.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Número de personas <em>n</em></th>
<th data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Probabilidad de haber nacido en días diferentes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>$$Q(2) = \frac{365}{365} \cdot \frac{364}{365} = 0.9973$$</td>
</tr>
<tr class="even">
<td></td>
<td>La primera ha podido nacer cualquier día del año (365 casos favorables sobre 365 casos posibles) y la segunda también cualquier día menos el día que nació la primera.</td>
</tr>
<tr class="odd">
<td>3</td>
<td>$$Q(3) = \frac{365}{365} \cdot \frac{364}{365} \cdot \frac{363}{365} = 0.9918$$</td>
</tr>
<tr class="even">
<td></td>
<td>El tercero ha podido nacer cualquier día menos los días que nacieron los otros dos.</td>
</tr>
<tr class="odd">
<td>4</td>
<td>$$Q(4) = \frac{365}{365} \cdot \frac{364}{365} \cdot \frac{363}{365} \cdot \frac{362}{365} = 0.9836$$</td>
</tr>
<tr class="even">
<td></td>
<td>De forma análoga a los casos anteriores.</td>
</tr>
<tr class="odd">
<td>$$\cdots$$</td>
<td>$$\cdots$$</td>
</tr>
<tr class="even">
<td>30</td>
<td>$$Q(30) = \frac{365}{365} \cdot \frac{364}{365} \cdot \frac{363}{365} \cdot \frac{362}{365} \cdots \frac{336}{365} = 0.2937$$</td>
</tr>
</tbody>
</table>

</div>
<p>En un grupo de 30 personas solo se pueden dar dos situaciones: todos han nacido en días diferentes o, como mínimo, dos han nacido el mismo día, no pueden haber situaciones intermedias. Por tanto, si la probabilidad de que todos hayan nacido en días diferentes es <span class="math inline">\(Q(30) = 0.2937\)</span>, la de que dos o más hayan nacido el mismo día será: <span class="math display">\[ P(30) = 1- Q(30) = 1-0.2937 = 0.7063 \]</span></p>
<p>Es inmediato deducir que la expresión general para <span class="math inline">\(P(n)\)</span> es: <span class="math display">\[P(n) = 1-Q(n) = 1- \frac{365!}{365^n(365-n)!} \]</span></p>
<p>Con ayuda de una hoja de cálculo se puede contruir la curva que relaciona la probabilidad de coincidencia con el número de personas (<a href="#fig-probabilidadCoincidencia" class="quarto-xref">Figura&nbsp;<span>4.9</span></a>).</p>
<div id="fig-probabilidadCoincidencia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-probabilidadCoincidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0409_probabilidadCoincidencia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-probabilidadCoincidencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.9: Construcción de la curva que relaciona la probabilidad de coincidencia en la fecha del cumpleaños y el número de personas en un grupo.
</figcaption>
</figure>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>También podríamos añadir que esa influencia del azar es relevante a efectos prácticos, porque todas las mediciones de magnitudes físicas están afectadas por un cierto error de medida.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Un argumento falaz, pero muchas veces convincente haciendo mención a aquello de los casos favorables partido por los casos posibles, es considerar que si la variable puede tomar infinitos valores, la probabilidad de que tome uno en concreto es cero. Esto es falso porque la regla de casos favorables partido por casos posibles solo vale cuando todos los sucesos tienen la misma probabilidad de ocurrir y este no es nuestro caso. Por otra parte, es perfectamente posible que una variable pueda tomar infinitos valores y que ninguno de ellos tenga probabilidad cero, tal como se ha visto para las variables aleatorias discretas.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Usar la densidad de frecuencia es la mejor opción cuando no todos los intervalos tienen la misma anchura.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Sean <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span> los extremos del intervalo y <span class="math inline">\(c\)</span> la moda. La función densidad de probabilidad es: <span class="math display">\[\begin{equation*}
    f(x) = \left \{
    \begin{aligned}
        \frac{2(x-a)}{(b-a)(c-a)}\;\; &amp; \quad\text{para}\;\; a \leq x \leq c \\
        \frac{2(b-x)}{(b-a)(b-c)}\;\;  &amp; \quad\text{para}\;\; c \leq x \leq b
    \end{aligned}
    \right.
\end{equation*}\]</span> La integral es inmediata, pero la simplificación de la expresión obtenida exige un poco de paciencia y alguna idea feliz. <span class="math display">\[\begin{equation*}
\begin{split}
    \text{E}(X) &amp;=\int_a^c x \frac{2(x-a)}{(b-a)(c-a)} \mathrm{d}x + \int_c^b x \frac{2(b-x)}{(b-a)(b-c)} \mathrm{d}x = \\[5pt]
    &amp;= \frac{2}{(b-a)(c-a)} \left(\frac{c^3}{3} - \frac{a^3}{3} - \frac{ac^2}{2} + \frac{a^3}{2} \right) + \frac{2}{(b-a)(b-c)} \left(\frac{b^3}{2} - \frac{bc^2}{2} - \frac{b^3}{3} + \frac{c^3}{3} \right) = \\[5pt]
    &amp;= \frac{ac^3-bc^3-a^3c+b^3c-ab^3+a^3b}{3(b-c)(b-a)(c-a)} = \frac{(b-c)(b-a)(c-a)(a+b+c)}{3(b-c)(b-a)(c-a)} = \frac{a+b+c}{3}
\end{split}
\end{equation*}\]</span><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Aunque algo sí que dice. Existe una curiosa propiedad denominada desigualdad de Chebyshev, que afirma que la probabilidad de que una variable aleatoria (con varianza finita, para ser rigurosos) se encuentre en el intervalo <span class="math inline">\(\mu \pm k\sigma\)</span> es como mínimo de <span class="math inline">\(1-1/k^2\)</span>. Por tanto, en nuestro caso, a la vista del valor de la varianza y tomando <span class="math inline">\(k=\sqrt{2}\)</span>, podemos afirmar que la probabilidad de que la variable se encuentre en el intervalo $3 $ (es decir: <span class="math inline">\(3 \pm 1.5275\)</span>) es, como mínimo, del 50%. Haciendo el cálculo exacto resulta ser del 84,7%.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Probabilidad de que todas sean correctas (la 1ª y la 2ª y la 3ª y …) = 0,99<sup>100</sup> = 0,37. Probabilidad de que alguna sea defectuosa: 1-0,37=0,63<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Probabilidad de original y defectuoso o falsificado y defectuoso: 0,9·0,001 + 0,1·0,5 = 0,0509<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Probabilidad de que una pieza sea defectuosa: 0,2 + 0,5 - 0,2·0,05 = 0,24. Todas buenas: (1-0,24)<sup>20</sup> = 0,76<sup>20</sup>. Alguna defectuosa: 1-0,76<sup>20</sup> = 0,9958.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Para más información, puede consultar la Wikipedia: “Problema de la partida interrumpida”&gt;&gt;“.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./0_02_tapaVariabilidad.html" class="pagination-link" aria-label="DESCRIBIR LO ALEATORIO">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">DESCRIBIR LO ALEATORIO</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05_distribucionesProbabilidad.html" class="pagination-link" aria-label="Distribuciones de probabilidad">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Distribuciones de probabilidad</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>