<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Estimación de características de la población – &lt;span style="font-size: 1.5em;"&gt;Estadística&lt;/span&gt;&lt;br&gt;
&lt;span style="font-size: 1em;"&gt;Entender - Aplicar - Enseñar&lt;/span&gt;</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./0_04_tapaSignificativo.html" rel="next">
<link href="./06_muestreo.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2cf3c65c5b6db5ec86e992953759863e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0_03_tapaMuestraPoblacion.html">DE LA MUESTRA A LA POBLACIÓN</a></li><li class="breadcrumb-item"><a href="./07_estimacion.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estimación de características de la población</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"><span style="font-size: 1.5em;">Estadística</span><br> <span style="font-size: 1em;">Entender - Aplicar - Enseñar</span></a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PRESENTACIÓN</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./00_Prologo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prólogo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_01_tapaDescriptiva.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ESTADÍSTICA DESCRIPTIVA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_sintesisNumerica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Síntesis numérica de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Graficos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Representaciones gráficas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_02_tapaVariabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DESCRIBIR LO ALEATORIO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_variablesAleatorias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variables aleatorias</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_distribucionesProbabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Distribuciones de probabilidad</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_03_tapaMuestraPoblacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DE LA MUESTRA A LA POBLACIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_muestreo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Muestreo. Encuestas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_estimacion.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estimación de características de la población</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_04_tapaSignificativo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ESTADÍSTICAMENTE SIGNIFICATIVO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_contrasteHipotesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Contraste de hipótesis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_algunosTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Algunos test clásicos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_05_tapaCorrelacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CORRELACIÓN Y REGRESIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_relacionLineal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Medidas de relación lineal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_regreSimple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regresión simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_regreMultiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Regresión Múltiple</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_06_tapaEpilogo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EPÍLOGO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_Epilogo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Datos frente a opiniones</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#estimador-puntual" id="toc-estimador-puntual" class="nav-link active" data-scroll-target="#estimador-puntual"><span class="header-section-number">7.1</span> Estimador puntual</a></li>
  <li><a href="#intervalo-de-confianza" id="toc-intervalo-de-confianza" class="nav-link" data-scroll-target="#intervalo-de-confianza"><span class="header-section-number">7.2</span> Intervalo de confianza</a></li>
  <li><a href="#estimación-de-la-media" id="toc-estimación-de-la-media" class="nav-link" data-scroll-target="#estimación-de-la-media"><span class="header-section-number">7.3</span> Estimación de la media</a>
  <ul class="collapse">
  <li><a href="#estimación-puntual" id="toc-estimación-puntual" class="nav-link" data-scroll-target="#estimación-puntual">Estimación puntual</a></li>
  <li><a href="#intervalo-de-confianza-para-la-media" id="toc-intervalo-de-confianza-para-la-media" class="nav-link" data-scroll-target="#intervalo-de-confianza-para-la-media">Intervalo de confianza para la media</a></li>
  </ul></li>
  <li><a href="#estimación-de-una-proporción" id="toc-estimación-de-una-proporción" class="nav-link" data-scroll-target="#estimación-de-una-proporción"><span class="header-section-number">7.4</span> Estimación de una proporción</a>
  <ul class="collapse">
  <li><a href="#estimación-puntual-1" id="toc-estimación-puntual-1" class="nav-link" data-scroll-target="#estimación-puntual-1">Estimación puntual</a></li>
  <li><a href="#intervalo-de-confianza-1" id="toc-intervalo-de-confianza-1" class="nav-link" data-scroll-target="#intervalo-de-confianza-1">Intervalo de confianza</a></li>
  </ul></li>
  <li><a href="#cálculo-del-tamaño-de-muestra" id="toc-cálculo-del-tamaño-de-muestra" class="nav-link" data-scroll-target="#cálculo-del-tamaño-de-muestra"><span class="header-section-number">7.5</span> Cálculo del tamaño de muestra</a>
  <ul class="collapse">
  <li><a href="#para-estimar-la-media" id="toc-para-estimar-la-media" class="nav-link" data-scroll-target="#para-estimar-la-media">Para estimar la media</a></li>
  <li><a href="#para-estimar-una-proporción" id="toc-para-estimar-una-proporción" class="nav-link" data-scroll-target="#para-estimar-una-proporción">Para estimar una proporción</a></li>
  </ul></li>
  <li><a href="#otras-estimaciones-tamaño-de-la-población" id="toc-otras-estimaciones-tamaño-de-la-población" class="nav-link" data-scroll-target="#otras-estimaciones-tamaño-de-la-población"><span class="header-section-number">7.6</span> Otras estimaciones: Tamaño de la población</a>
  <ul class="collapse">
  <li><a href="#cuántos-peces-hay-en-un-lago" id="toc-cuántos-peces-hay-en-un-lago" class="nav-link" data-scroll-target="#cuántos-peces-hay-en-un-lago">¿Cuántos peces hay en un lago?</a></li>
  <li><a href="#cuántos-taxis-hay-en-una-ciudad" id="toc-cuántos-taxis-hay-en-una-ciudad" class="nav-link" data-scroll-target="#cuántos-taxis-hay-en-una-ciudad">¿Cuántos taxis hay en una ciudad?</a></li>
  </ul></li>
  <li><a href="#apéndice-7.a-distribución-de-la-media-muestral-visión-intuitiva" id="toc-apéndice-7.a-distribución-de-la-media-muestral-visión-intuitiva" class="nav-link" data-scroll-target="#apéndice-7.a-distribución-de-la-media-muestral-visión-intuitiva">APÉNDICE 7.A: Distribución de la media muestral: Visión intuitiva</a></li>
  <li><a href="#apéndice-7.b-número-de-taxis-análisis-de-la-calidad-de-la-estimación-usando-una-hoja-de-cálculo" id="toc-apéndice-7.b-número-de-taxis-análisis-de-la-calidad-de-la-estimación-usando-una-hoja-de-cálculo" class="nav-link" data-scroll-target="#apéndice-7.b-número-de-taxis-análisis-de-la-calidad-de-la-estimación-usando-una-hoja-de-cálculo">APÉNDICE 7.B: Número de taxis: Análisis de la calidad de la estimación usando una hoja de cálculo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0_03_tapaMuestraPoblacion.html">DE LA MUESTRA A LA POBLACIÓN</a></li><li class="breadcrumb-item"><a href="./07_estimacion.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estimación de características de la población</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estimación de características de la población</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Rara vez es posible conocer con exactitud las características de una población. Esto puede deberse a que resulta inviable observar todos sus elementos —como en el caso de los sondeos electorales— o a que la población es, en realidad, un modelo teórico. Por ejemplo, cuando se pone en marcha una máquina y se fabrican algunas unidades para evaluar su funcionamiento, tenemos una muestra con la que valoramos si serán adecuadas las características de todas las unidades que se podrían fabricar en esas condiciones. Todas esas unidades son la población, pero es una población teórica, no existe físicamente.</p>
<p>En cualquier caso, sea la población real o teórica, lo que hacemos es “estimar” (hacernos una idea de) las características de interés de esa población a partir de los valores obtenidos en la muestra.</p>
<section id="estimador-puntual" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="estimador-puntual"><span class="header-section-number">7.1</span> Estimador puntual</h2>
<p>Un estimador puntual, o simplemente estimador, es un número que se calcula a partir de los valores de una muestra y que nos sirve para hacernos una idea de una determinada característica de la población. Si queremos estimar el valor de la media de la población, la media de una muestra representativa de esa población es un buen estimador. Pero no siempre es tan fácil, hemos visto que la varianza de una muestra –aplicando la fórmula &lt;<natural>&gt; de dividir por <span class="math inline">\(n\)</span> la suma de cuadrados–, es un estimador sesgado de la varianza de la población.</natural></p>
<p>Las cualidades de un estimador se valoran por el cumplimiento de unas determinadas propiedades. Las más importantes son:</p>
<ul>
<li><p>Que sea insesgado, es decir, que no dé errores sistemáticos ni por exceso ni por defecto. Si tomamos muchas muestras y con cada una de ellas calculamos el valor del estimador, como los elementos en las muestras serán distintos (serán los que hayan caído por azar en cada muestra) los valores de ese estimador también serán distintos, pero si es insesgado se situarán en torno al verdadero valor que tiene en la población. Si existe un error sistemático, por exceso o por defecto, a ese error se le denomina (<a href="#fig-dianas" class="quarto-xref">Figura&nbsp;<span>7.1</span></a>).</p></li>
<li><p>Que sea preciso. Significa que si calculamos muchos valores de ese estimador, cada uno a partir de una muestra distinta, esos valores presentarán poca variabilidad. Si además el estimador es insesgado esa poca variabilidad estará distribuida en torno al verdadero valor de la magnitud estimada.</p></li>
</ul>
<div id="fig-dianas" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dianas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0701_dianas.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dianas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.1: {Analogía de las propiedades de los estimadores con los impactos en una diana.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>¿Por qué nos creemos el resultado obtenido de una muestra sabiendo que si tomáramos otra sería distinto?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Porque sería distinto pero no “muy distinto”. Para informar sobre la variabilidad que cabe esperar se da el intervalo de confianza.</p>
</div>
</div>
</section>
<section id="intervalo-de-confianza" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="intervalo-de-confianza"><span class="header-section-number">7.2</span> Intervalo de confianza</h2>
<p>El estimador puntual apuesta por un valor concreto y sabemos que el verdadero valor andará por ahí, pero no informa sobre si estará muy cerca o si también podría estar bastante lejos.</p>
<p>Un intervalo de confianza ofrece una información más rica, nos dice que el valor que estamos estimando se encuentra –con una probabilidad conocida y que nosotros podemos elegir– dentro de ese intervalo. Típicamente, en un intervalo de confianza intervienen tres valores:</p>
<ul>
<li><p><span style="color: #0038CF;"><strong>Estimación! puntual</strong></span>: Siempre está dentro del intervalo. Cuando las desviaciones por encima y por debajo de ese valor son igualmente probables se encuentra justo en el centro del intervalo.</p></li>
<li><p><span style="color: #0038CF;"><strong>Margen de error</strong></span>: Es el valor que se suma y se resta al estimador puntual para construir el intervalo. En algunos casos, puede ocurrir que el margen de error no sea el mismo por encima y por debajo del estimador puntual.</p></li>
<li><p><span style="color: #0038CF;"><strong>Nivel de confianza</strong></span>: Es la probabilidad<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> de que el intervalo incluya el verdadero valor del parámetro estimado.</p></li>
</ul>
<p>Que el nivel de confianza sea del 95 % significa que el intervalo se ha construido con un procedimiento que “acierta” (incluye el verdadero valor del parámetro estimado) el 95 % de las veces.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>¿Qué es un intervalo de confianza?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Es un intervalo construido a partir de los valores de una muestra. En la práctica solo tenemos una muestra y un intervalo, pero si pudiéramos construir muchos intervalos, cada uno a partir de una muestra distinta, un porcentaje de ellos igual al nivel de confianza incluiría el verdadero valor del parámetro estimado.</p>
</div>
</div>
<p>Si generamos muestras aleatorias de una población Normal y, a partir de cada una de ellas, calculamos un intervalo de confianza del 95 % para la media de la población (<span class="math inline">\(\mu\)</span>) resultará que alrededor del 95 % de esos intervalos incluirá el verdadero valor de <span class="math inline">\(\mu\)</span>. Si el intervalo de confianza fuera del 50 %, solo la incluirían aproximadamente la mitad.</p>
<p>Nosotros tendremos una sola muestra y nos será imposible saber si el intervalo de confianza construido a partir de sus valores incluye el valor estimado o si lo deja fuera. Si supiéramos que está dentro, podríamos decir que es un intervalo de confianza del 100 %, y si supiéramos que está fuera sería del 0 %. Pero no lo sabemos. Un intervalo de confianza del 95 % es como recibir información de una persona que dice la verdad el 95 % de las veces: sabemos que su fiabilidad global es alta, pero nunca podemos estar seguros de si una afirmación concreta es correcta (<a href="#fig-diceLaVerdad" class="quarto-xref">Figura&nbsp;<span>7.2</span></a>).</p>
<div id="fig-diceLaVerdad" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diceLaVerdad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0702_diceLaVerdad.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diceLaVerdad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.2: Concepto de intervalo de confianza.
</figcaption>
</figure>
</div>
<p>Hemos dicho que el nivel de confianza lo elegimos nosotros, entonces ¿por qué nos conformamos con el 95 % si podemos establecer el 99 % o incluso el 99,99 %? La respuesta es sencilla: cuanto mayor es el nivel de confianza –cuanto más seguros queremos estar de que el intervalo contiene el valor del parámetro estimado– más ancho será el intervalo. Esto es lógico, dada una cantidad de información (tamaño de la muestra) la mayor seguridad solo se consigue aumentando la anchura del intervalo, el problema es que si queremos mucha seguridad el intervalo sale tan ancho que la información que aporta es irrelevante.</p>
<p>Supongamos que para estimar la proporción de celíacos en una comunidad se toma una muestra de 100 individuos y que entre ellos se encuentra un celíaco. El estimador puntual es igual al valor en la muestra, en nuestro caso el 1 %. Los intervalos de confianza del 50, 95 y 99,99 % son los que se indican en la <a href="#fig-anchuraIntervalos" class="quarto-xref">Figura&nbsp;<span>7.3</span></a>. El intervalo de confianza del 99,99 % es tan ancho que no aporta información relevante. No hacía falta realizar ningún estudio para saber que el porcentaje está entre 0,00 % (exactamente 0,00005 %) y el 11,8 %.</p>
<div id="fig-anchuraIntervalos" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anchuraIntervalos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0703_anchuraIntervalos.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anchuraIntervalos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.3: Intervalos con distinto nivel de confianza para la estimación de una proporción a partir de una muestra de 100 observaciones y un solo positivo.
</figcaption>
</figure>
</div>
<p>Los intervalos de confianza del 95 % son una buena solución de compromiso entre el nivel de confianza y la anchura del intervalo. Si se desea aumentar el nivel de confianza manteniendo la anchura del intervalo no hay más remedio que aumentar el tamaño de la muestra.</p>
</section>
<section id="estimación-de-la-media" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="estimación-de-la-media"><span class="header-section-number">7.3</span> Estimación de la media</h2>
<p>Pesamos 6 paquetes de café a la salida de la línea de envasado. Esos paquetes se pueden considerar representativos de la producción general y sus pesos, en gramos, son: 995, 987, 1008, 995, 991 y 1007. ¿Qué podemos decir sobre el valor medio con que se están llenando?</p>
<section id="estimación-puntual" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="estimación-puntual">Estimación puntual</h3>
<p>Si tenemos que dar un valor para el peso medio con que están saliendo los paquetes de café, nuestra mejor apuesta es el peso medio de la muestra obtenida: <span class="math inline">\(\bar{x} = 997.17 \text{g}\)</span>. Así de fácil.</p>
<p>Para justificarlo podemos plantear que si <span class="math inline">\(X \sim N(\mu; \sigma)\)</span> y <span class="math inline">\(X_1, X_2, \cdots, X_n\)</span> es una muestra aleatoria de esa población, cada valor de la muestra está tomado de esa misma población y, por tanto, tendrá una esperanza matemática <span class="math inline">\(\text{E}(X_i) = \mu\)</span>. Designando la media de la muestra como <span class="math inline">\(\bar{X}\)</span> y usando las propiedades de la esperanza matemática, tenemos:</p>
<span class="math display">\[\begin{equation*}
    \begin{split}
        \text{E}(\bar{X}) &amp;=\text{E} \left( \frac{X_1+X_2+ \cdots + X_n}{n}\right) =\\[5pt]
        &amp; = \frac{1}{n} \left[\text{E}(X_1)+\text{E}(X_2)+ \cdots +  \text{E}(X_n) \right] =\\[5pt]
        &amp; = \frac{1}{n} \cdot n \cdot \mu= \mu
    \end{split}
\end{equation*}\]</span>
<p>También podemos comprobar que esto es así usando una población “de prueba” como hicimos en el Apéndice 2.D. Supongamos que la población está formada por solo 5 elementos, cada uno de ellos con el valor que se indica:</p>
<div class="tabla-wrapper_T0700">

<table class="tabla-02Ape2D_1 caption-top table">
<tbody>
<tr class="odd">
<td>(A)</td>
<td>(B)</td>
<td>(C)</td>
<td>(D)</td>
<td>(E)</td>
</tr>
<tr class="even">
<td>3</td>
<td>6</td>
<td>9</td>
<td>12</td>
<td>15</td>
</tr>
</tbody>
</table>

</div>
<p>El valor medio de esos 5 elementos –la media de la población– es: <span class="math display">\[\mu = \frac{3 + 6 + 9 + 12 + 15}{5} = 9\]</span> Existen 10 maneras de seleccionar una muestra de 3 elementos de esta población (combinaciones de 5 elementos tomados de 3 en 3). Por tanto, si tomamos una muestra con toda seguridad será una de las que se incluyen en la <a href="#tbl-Medias">Tabla 7.1</a>, puesto que están todas.</p>
<div id="tbl-Medias" ;="" class="tabla-wrapper_T0701 anchored">

<table class="tabla-0701 caption-top table">
<caption>Tabla 7.1: Medias de las 10 muestras de 3 observaciones que se pueden obtener de una población con 5 elementos.</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">Muestra nº</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
<td>8</td>
<td>9</td>
<td>10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unidades de la muestra</td>
<td>A<br>
B<br>
C</td>
<td>A<br>
B<br>
D</td>
<td>A<br>
B<br>
E</td>
<td>A<br>
C<br>
D</td>
<td>A<br>
C<br>
E</td>
<td>A<br>
D<br>
E</td>
<td>B<br>
C<br>
D</td>
<td>B<br>
C<br>
E</td>
<td>B<br>
D<br>
E</td>
<td>C<br>
D<br>
E</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Valores en la muestra</td>
<td>3<br>
6<br>
9</td>
<td>3<br>
6<br>
12</td>
<td>3<br>
6<br>
15</td>
<td>3<br>
9<br>
12</td>
<td>3<br>
9<br>
15</td>
<td>3<br>
12<br>
15</td>
<td>6<br>
9<br>
12</td>
<td>6<br>
9<br>
15</td>
<td>6<br>
12<br>
15</td>
<td>9<br>
12<br>
15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Media muestral</td>
<td>6</td>
<td>7</td>
<td>8</td>
<td>8</td>
<td>9</td>
<td>10</td>
<td>9</td>
<td>10</td>
<td>11</td>
<td>12</td>
</tr>
</tbody>
</table>

</div>Podemos comprobar que la media de la media muestral <span class="math inline">\(\bar{\bar{x}}\)</span> (parece una redundancia pero es así como hay que decirlo) coincide con la media de la población: <span class="math display">\[\bar{\bar{x}} = \frac{6+7+8+8+9+10+9+10+11+12}{10} = 9\]</span> Si al tomar una muestra de 3 elementos resulta ser la nº 1 tendremos una media <span class="math inline">\(\bar{x}=6\)</span> y si es la nº 10 tendremos <span class="math inline">\(\bar{x}=12\)</span>, valores alejados de la media de la población, mientras que si nuestra muestra es la nº 5 o la nº 7 el valor estimado coincidirá con el real. Cuando usamos la media de una muestra como estimador de la media de la población no podemos saber si hemos tenido suerte y el valor obtenido queda cerca del valor real o si queda lejos, pero podemos tener la seguridad de que si lo calculamos varias veces –cada vez con una muestra distinta– los valores obtenidos estarán en torno a la media de la población.<p></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ejemplo de estimador sesgado para la media de la población
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si descartamos los tres valores más bajos y calculamos la media del resto de la muestra, tendremos un estimador sesgado de la media de la población.</p>
</div>
</div>
</section>
<section id="intervalo-de-confianza-para-la-media" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="intervalo-de-confianza-para-la-media">Intervalo de confianza para la media</h3>
<p>Al igual que los estimadores puntuales, los intervalos de confianza se construyen a partir de la información obtenida de una muestra. Nosotros –a efectos didácticos– vamos a empezar deduciendo su expresión en torno a una sola observación y a continuación la adaptaremos para construirlos en torno a la media de una muestra.</p>
<section id="en-torno-a-una-sola-observación" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="en-torno-a-una-sola-observación">En torno a una sola observación</h4>
<p>En la <a href="#fig-ICmedia" class="quarto-xref">Figura&nbsp;<span>7.4</span></a> tenemos representada la distribución cuya media <span class="math inline">\(\mu\)</span> se desea estimar. Se han sombreado las colas de forma que la probabilidad de que una observación tomada al azar caiga en esa zona sea igual a <span class="math inline">\(\alpha\)</span> (<span class="math inline">\(\alpha\)</span>/2 en cada lado). Por tanto, la probabilidad de que caiga en la zona interior es <span class="math inline">\(1-\alpha\)</span>.</p>
<div id="fig-ICmedia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ICmedia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0704_ICmedia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ICmedia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.4: Intervalos construidos sumando y restando <span class="math inline">\(z_{\alpha/2}\sigma\)</span> a un valor obtenido al azar.
</figcaption>
</figure>
</div>
<p>Veamos cuánto vale la distancia desde la media <span class="math inline">\(\mu\)</span> al punto <span class="math inline">\(x_{\alpha/2}\)</span> en el que empieza la zona sombreada. Resulta que si $ X (; ) <span class="math inline">\(, la nueva variable aleatoria:\)</span><span class="math inline">\(Z = \frac{X-\mu}{\sigma}\)</span>$ sigue una distribución <span class="math inline">\(\text{N}(0; 1)\)</span> y tiene unas características que nos resultan muy útiles, en particular (ver Apéndice 5.A): <span class="math display">\[ \text{P}(X &gt; x_{\alpha/2}) = \text{P} \left ( Z &gt; \frac{x_{\alpha/2} - \mu}{\sigma} \right) \]</span> Por tanto, podemos escribir: <span class="math display">\[ z_{\alpha/2} = \frac{x_{\alpha/2} - \mu}{\sigma} \]</span></p>
<p>y despejando <span class="math inline">\(x_{\alpha/2}\)</span>: <span class="math display">\[ x_{\alpha/2} = \mu + z_{\alpha/2} \cdot \sigma \]</span> Como el valor de <span class="math inline">\(\alpha/2\)</span> es conocido (lo hemos elegido nosotros) podemos identificar el valor de <span class="math inline">\(Z\)</span> que deja esa área de cola. Por ejemplo, si <span class="math inline">\(\alpha=0.05\)</span>, <span class="math inline">\(\alpha/2 = 0.025\)</span> y <span class="math inline">\(z_{0.025}=1.96\)</span>. Ya es inmediato deducir que la distancia entre <span class="math inline">\(x_{\alpha/2}\)</span> y <span class="math inline">\(\mu\)</span> es igual a <span class="math inline">\(z_{\alpha/2}\sigma\)</span>. Sumando y restando esa distancia a un valor (<span class="math inline">\(x\)</span>) obtenido al azar, tenemos el intervalo: <span class="math display">\[x \pm z_{\alpha/2}\sigma \]</span> Observe que si el valor de <span class="math inline">\(x\)</span> está en la zona de probabilidad <span class="math inline">\(1 - \alpha\)</span>, tal como ocurre con <span class="math inline">\(x_1\)</span> y <span class="math inline">\(x_2\)</span>, el intervalo obtenido incluye el valor de <span class="math inline">\(\mu\)</span>. Sin embargo, si <span class="math inline">\(x\)</span> cae en la zona de las colas, como ocurre con <span class="math inline">\(x_3\)</span>, el intervalo no llega a alcanzar el valor de <span class="math inline">\(\mu\)</span>. Por tanto, los intervalos calculados con este procedimiento aciertan si el valor obtenido al azar cae entre las dos colas de la distribución, y esto ocurre con una probabilidad <span class="math inline">\(1 - \alpha\)</span>. Por esta razón se denominan intervalos de confianza <span class="math inline">\(1 - \alpha\)</span>. Este nivel de confianza se da normalmente en porcentaje y si <span class="math inline">\(\alpha = 0.05\)</span> hablamos de intervalo de confianza del 95 %.</p>
</section>
<section id="en-torno-a-la-media-de-una-muestra" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="en-torno-a-la-media-de-una-muestra">En torno a la media de una muestra</h4>
<p>La estimación es más precisa –el intervalo de confianza es más estrecho– si en vez de construirlo en torno a una observación individual lo construimos en torno a la media de una muestra. Veamos algunas características de la media muestral que nos serán útiles para construir el intervalo de confianza.</p>
<ol type="1">
<li><p>La media muestral es una variable aleatoria.</p>
<p>Parece que tenemos metido en la cabeza que la media es un número concreto y, efectivamente, así es si nos referimos a una muestra concreta. Por ejemplo, la media de 2, 4, 6 y 8 es igual a 5, un número concreto, de la misma forma que la estatura de Juan, una persona concreta, es de 172 cm. Pero la estatura de una persona genérica es una variable aleatoria de un distribución que podría ser <span class="math inline">\(\text{N}(170\, \text{cm}; 7 \, \text{cm})\)</span>. De la misma forma, la media de una muestra aleatoria genérica –no nos referimos a unos valores concretos– también es una variable aleatoria.</p></li>
<li><p>En general, podemos considerar que la media muestral tiene distribución Normal.</p>
<p>Si las observaciones provienen de una distribución Normal, la media es una combinación lineal de Normales y, por tanto, también es Normal. Si la población no es exactamente Normal, pero el tamaño de muestra no es muy pequeño, una consecuencia del teorema central del límite<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> es que –a efectos prácticos– se puede considerar que la media muestral también sigue una distribución Normal.</p></li>
</ol>
<!-- -->
<ol start="3" type="1">
<li><p>Si los valores de la muestra provienen de una distribución $ X N(; ) $ la media de muestras de tamaño <span class="math inline">\(n\)</span> sigue una distribución $ N(; ) $.</p>
<p>Al tratar las propiedades del estimador puntual, ya vimos que si $ X N(; ) $ y <span class="math inline">\(\bar{X} = \frac{1}{n} (X_1 + X_2 + \cdots + X_n)\)</span> tenemos que <span class="math inline">\(E(\bar{X}) = \mu\)</span>.</p>
<p>Ahora podemos añadir que:</p>
<p><span class="math display">\[\begin{equation*} \label{eq2}
        \begin{split}
            V(\bar{X}) &amp;=V \left( \frac{X_1+X_2+ \cdots + X_n}{n}\right) =\\[5pt]
            &amp; = \frac{1}{n^2} \left[V(X_1)+V(X_2)+ \cdots +  V(X_n) \right] =\\[5pt]
          &amp; = \frac{1}{n^2} \cdot n  \sigma^2 = \frac{\sigma^2}{n}
        \end{split}
  \end{equation*}\]</span> Por tanto, la desviación típica de la distribución de la media muestral es igual a <span class="math inline">\(\sigma\sqrt{n}\)</span>.</p></li>
</ol>
<p>En la <a href="#fig-mediaICmedia" class="quarto-xref">Figura&nbsp;<span>7.5</span></a> hemos representado la distribución de la población (campana gris) y la correspondiente a la media muestral, que tiene menos variabilidad y por tanto es más estrecha y también más alta ya que si están en la misma escala el área debe ser la misma (igual a 1). La media de una muestra es un valor de la distribución de la media muestral, es decir, de la campana estrecha. Su desviación típica es <span class="math inline">\(\sigma/\sqrt{n}\)</span>, por tanto: <span class="math display">\[z_{\alpha/2} = \frac{x_{\alpha/2} - \mu} {\frac{\sigma}{\sqrt{n}}} \]</span> Y ya es inmediato deducir que en este caso la distancia entre <span class="math inline">\(x_{\alpha/2}\)</span> y <span class="math inline">\(\mu\)</span> será: <span class="math display">\[z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\]</span></p>
<div id="fig-mediaICmedia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediaICmedia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0705_mediaICmedia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediaICmedia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.5: Intervalos construidos en torno a la media de una muestra sumando y restando <span class="math inline">\(z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\)</span>.
</figcaption>
</figure>
</div>
<p>Siguiendo el mismo razonamiento que para construir el intervalo en torno a una observación individual, en torno a la media de una muestra obtenemos: <span class="math display">\[\bar{x} \pm z_{\alpha/2} \frac{\sigma}{\sqrt{n}} \]</span> Observe que cuanto mayor es el tamaño de la muestra (mayor valor de <span class="math inline">\(n\)</span>) menor es la desviación típica de la distribución de la media muestral y, por tanto, menor es la anchura del intervalo de confianza.</p>
</section>
<section id="y-si-no-conocemos-el-valor-de" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="y-si-no-conocemos-el-valor-de">¿Y si no conocemos el valor de $ $?</h4>
<p>No conocer el valor de <span class="math inline">\(\sigma\)</span> es lo más habitual, y también lo más lógico, ya que sería extraño conocer el valor de la desviación típica de la población y no conocer el valor de la media. En la expresión del intervalo de confianza lo que hacemos es sustituir el valor de <span class="math inline">\(\sigma\)</span> por su estimador <span class="math inline">\(s\)</span> (desviación típica de la muestra) y esto tiene consecuencias prácticas si la muestra es pequeña.</p>
<p>Conociendo el valor de <span class="math inline">\(\sigma\)</span> teníamos: <span class="math display">\[\frac{X - \mu} {\sigma} = Z \sim \text{N(0; 1)}\]</span> Al colocar <span class="math inline">\(s\)</span> en el denominador estamos cambiando una constante (el valor de <span class="math inline">\(\sigma\)</span>) por una variable aleatoria. Esto provoca que la variable representada por esta nueva expresión tenga mayor variabilidad y ya no siga una distribución N(0; 1) sino otra similar con algo más de variabilidad. A esta nueva distribución se le denomina <span class="math inline">\(t\)</span> de Student<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<p><span class="math display">\[ \frac{X - \mu} {s} \sim t-\text{Student}\]</span> La distribución <span class="math inline">\(t\)</span> de Student siempre está relacionada con una estimación del valor de <span class="math inline">\(\sigma\)</span> y su forma depende del tamaño de la muestra utilizada para realizar esa estimación. Si la muestra es grande, pongamos <span class="math inline">\(n&gt;30\)</span>, el valor de <span class="math inline">\(s\)</span> tendrá poca variabilidad –cambiará poco si tomamos otra muestra– y estará próximo a <span class="math inline">\(\sigma\)</span>, de manera que la distribución de <span class="math inline">\(t\)</span> no será muy distinta de la de <span class="math inline">\(Z\)</span>. Sin embargo, si la muestra es pequeña el valor de <span class="math inline">\(s\)</span> tendrá mayor variabilidad y las distribuciones de <span class="math inline">\(t\)</span> y de <span class="math inline">\(Z\)</span> tendrán mayor diferencia.</p>
<p>Por tanto, la distribución <span class="math inline">\(t\)</span> de Student no es única, sino que depende del tamaño de la muestra con que se calcula la <span class="math inline">\(s\)</span> con la que está asociada. Para identificar a cual nos estamos refiriendo le añadimos un valor que llamamos &lt;<grados de="" libertad="">&gt; y al que asignamos la letra griega <span class="math inline">\(\nu\)</span> (nu) que colocamos como subíndice de <span class="math inline">\(t\)</span>. Los grados de libertad tienen una relación inmediata con el tamaño de muestra: <span class="math inline">\(\nu = n-1\)</span>.</grados></p>
<p>Ya hemos llegado al final. Cambiamos el valor de <span class="math inline">\(\sigma\)</span> por el de <span class="math inline">\(s\)</span> y el de <span class="math inline">\(z\)</span> por el de <span class="math inline">\(t\)</span> con sus grados de libertad y nos queda: <span class="math display">\[ \bar{x} \pm t_{\nu;\alpha/2} \frac{s}{\sqrt{n}} \]</span></p>
</section>
<section id="intervalo-de-confianza-para-el-peso-medio-de-los-paquetes-de-café" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="intervalo-de-confianza-para-el-peso-medio-de-los-paquetes-de-café">Intervalo de confianza para el peso medio de los paquetes de café</h4>
<p>Recordemos que los valores de nuestra muestra son (en gramos): 995, 987, 1008, 995, 991 y 1007. Necesitamos conocer:</p>
<div class="columns">
<div class="column" style="width:12%;">
<p><span class="math inline">\(\bar{x}\)</span>:</p>
</div><div class="column" style="width:88%;">
<p>Ya lo hemos calculado. Es igual a 997,17 g.</p>
</div>
</div>
<div class="columns">
<div class="column" style="width:12%;">
<p><span class="math inline">\(t_{5; \, 0.025}\)</span>:</p>
</div><div class="column" style="width:88%;">
<p>Es el valor de una <span class="math inline">\(t\)</span> de Student con 5 grados de libertad (<span class="math inline">\(=n-1\)</span>) que deja un área de cola de 0,025. Lo podemos obtener usando una hoja de cálculo o las típicas tablas que se incluyen (o incluían) en los libros de estadística. En nuestro caso, <span class="math inline">\(t_{5; \, 0.025} = 2.571\)</span></p>
</div>
</div>
<div class="columns">
<div class="column" style="width:12%;">
<p><span class="math inline">\(s\)</span>:</p>
</div><div class="column" style="width:88%;">
<p>Desviación típica de los valores de la muestra. <span class="math inline">\(s=8.542\)</span>.</p>
</div>
</div>
<div class="columns">
<div class="column" style="width:12%;">
<p><span class="math inline">\(n\)</span>:</p>
</div><div class="column" style="width:88%;">
<p>Tamaño de la muestra. <span class="math inline">\(n=6\)</span></p>
</div>
</div>
<p>Aplicando esta fórmula obtenemos que el intervalo de confianza del 95 % para la media de la población es: <span class="math inline">\(997.17 \pm 8.97\)</span>.</p>
<p>Los cálculos son muy fáciles de realizar. Lo importante es entender bien qué significa la información que da el intervalo y –como siempre– asegurarse de que la muestra utilizada es representativa de la población de interés.</p>
</section>
</section>
</section>
<section id="estimación-de-una-proporción" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="estimación-de-una-proporción"><span class="header-section-number">7.4</span> Estimación de una proporción</h2>
<p>Deseamos estimar el porcentaje de estudiantes de una universidad que tiene cuenta en una determinada red social, les llamaremos <em>cumplidores</em>. Como no podemos preguntar a todos, tomamos una muestra de <span class="math inline">\(n=100\)</span> y resulta que 58 tienen cuenta. ¿Qué podemos decir sobre la proporción en la población?</p>
<section id="estimación-puntual-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="estimación-puntual-1">Estimación puntual</h3>
<p>En nuestra muestra el número de cumplidores es <span class="math inline">\(X=58\)</span> pero sabemos que si hubiéramos tomado otra, tan buena como la primera, el resultado podría haber sido otro. En realidad, el valor de <span class="math inline">\(X\)</span> es una variable aleatoria que se ajusta al modelo de la distribución binomial<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> cuyos parámetros son el tamaño de la muestra <span class="math inline">\(n=100\)</span> y la proporción en la población <span class="math inline">\(p\)</span>, de valor desconocido.</p>
<p>Hemos visto que la esperanza matemática de una variable aleatoria <span class="math inline">\(X\)</span> con distribución binomial y parámetros <span class="math inline">\(n\)</span> y <span class="math inline">\(p\)</span> es: <span class="math display">\[\text{E}(X) = np \]</span> La proporción en la muestra <span class="math inline">\(\frac{X}{n}\)</span> también es una variable aleatoria, y recordando las propiedades de la esperanza matemática podemos escribir: <span class="math display">\[\text{E} \left(\frac{X}{n}\right) = \frac{1}{n}\text{E}(X) = \frac{1}{n} np = p\]</span> Por tanto, la esperanza matemática de la proporción en la muestra es igual a la proporción en la población. Dicho en otras palabras, la proporción en la muestra es un estimador insesgado de la proporción en la población.</p>
<p>Por otro lado, también podemos entender la proporción como una media. Podemos asignar el valor 1 a los que tienen cuenta en esa red social y 0 a los que no la tienen. El promedio de esos valores es la proporción a que nos estamos refiriendo. Si la proporción es una caso particular de valor medio, tiene también las propiedades que ya hemos comentado sobre la media de la muestra como estimador de la media de la población.</p>
<p>Claro que si decimos que la proporción en la población está en torno al 58 % no está claro si está entre el 56 y el 60 o entre el 50 y el 66. Para informar sobre la precisión de la estimación recurrimos a los intervalos de confianza.</p>
</section>
<section id="intervalo-de-confianza-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="intervalo-de-confianza-1">Intervalo de confianza</h3>
<p>Existen varios métodos para calcular intervalos de confianza para una proporción<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. El más habitual se basa en la aproximación de la distribución binomial a la Normal pero vamos a empezar viendo otro denominado “exacto” que se puede usar siempre y que nos parece interesante a efectos didácticos.</p>
<section id="método-exacto" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="método-exacto">Método exacto</h4>
<p>Empezamos identificando el valor de la proporción <span class="math inline">\(p_1\)</span> de cumplidores en la población que da una probabilidad de 0,025 de tener 58 o más cumplidores en una muestra de <span class="math inline">\(n\,\)</span>=100 individuos. Observe que si <span class="math inline">\(p\)</span> es grande –pongamos 90 %– será muy probable tener 58 o más cumplidores, mientras que si <span class="math inline">\(p\)</span> es bajo –pongamos del 10 %– esa probabilidad será prácticamente nula.</p>
<p>En la <a href="#tbl-Encima">Tabla 7.2</a> hemos realizado un barrido de valores de <span class="math inline">\(p\)</span> calculando para cada uno de ellos la probabilidad buscada, el uso de una hoja de cálculo facilita mucho esta tarea. En la tabla de la izquierda vemos que esa proporción está entre 0,4 y 0,5. Realizando barridos cada vez más finos llegamos a que el valor de <span class="math inline">\(p_1\)</span> con tres decimales es igual a 0,477.</p>
<p>De manera análoga podemos calcular el valor de <span class="math inline">\(p_2\)</span> que da una probabilidad de 0,025 de tener 58 o menos cumplidores. La <a href="#tbl-Debajo">Tabla 7.3</a> muestra el barrido realizado para llegar a que el valor de <span class="math inline">\(p_2\)</span> es igual a 0,678.</p>
<div id="fig-intervaloExacto" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-intervaloExacto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0706_intervaloExacto.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-intervaloExacto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.6: Intervalo de confianza del 95% para la proporción en la población si en un muestra de n=100 individuos se encuentran X=58 cumplidores.
</figcaption>
</figure>
</div>
<p>Por tanto, dadas las evidencias que tenemos (<span class="math inline">\(n\)</span>=100; <span class="math inline">\(X\)</span>=58) podemos afirmar que es poco probable que la proporción en la población sea menor del 44,7% y también es poco probable que supere el 67,8%. Concretamente, ese ``poco probable’’ significa una probabilidad del 2,5%. Luego la probabilidad de que se encuentre entre el 47,7 y el 67,8% es del 95%. Ese es el intervalo de confianza del 95%.</p>
<div id="tbl-Encima" class="anchored">

<table class="tabla-0702 caption-top table">
<caption>Tabla 7.2: Determinación de la proporción en la población (p) que da una probabilidad de 0,025 de tener un número de cumplidores <strong>igual o mayor</strong> que los obtenidos en la muestra.</caption>
<tbody>
<tr class="odd">
<td></td>
</tr>
</tbody>
</table>

</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras_07/f_Tabla0702.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
<div id="tbl-Encima" class="anchored">

<table class="tabla-0702 caption-top table">
<caption>Tabla 7.2: Determinación de la proporción en la población (p) que da una probabilidad de 0,025 de tener un número de cumplidores <strong>igual o mayor</strong> que los obtenidos en la muestra.</caption>
<tbody>
<tr class="odd">
<td></td>
</tr>
</tbody>
</table>

</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras_07/f_Tabla0703.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</section>
<section id="usando-la-distribución-normal-como-aproximación-a-la-binomial" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="usando-la-distribución-normal-como-aproximación-a-la-binomial">Usando la distribución Normal como aproximación a la binomial</h4>
<p>Al final de capítulo 5 (“La distribución Normal como aproximación a la binomial”) vimos que una variable aleatoria con distribución binomial y <span class="math inline">\(p=0,5\)</span> presenta una distribución simétrica en torno a su valor medio, y a medida que aumenta el valor de <span class="math inline">\(n\)</span> su forma se parece cada vez más a la de una distribución Normal. Si <span class="math inline">\(p \neq 0.5\)</span> la distribución también puede considerarse simétrica si el valor de <span class="math inline">\(n\)</span> es &lt;<grande>&gt;. Lo que significa &lt;<grande>&gt; depende de lo alejado que esté <span class="math inline">\(p\)</span> de 0,5. Una regla empírica es considerar que la distribución Normal es una buena aproximación a la binomial cuando se cumple que <span class="math inline">\(np&gt;5\)</span> y <span class="math inline">\(n(1-p)&gt;5\)</span>.</grande></grande></p>
<p>Recordadas las condiciones en que se puede realizar la aproximación, volvamos a nuestros datos. Se ha realizado una encuesta entre los estudiantes de una universidad y en una muestra de <span class="math inline">\(n=100\)</span> estudiantes hay 58 con cuenta en una determinada red social. Queremos dar un intervalo de confianza para la proporción de estudiantes de esa universidad que tienen cuenta. El número de cumplidores, <span class="math inline">\(X\)</span>, que aparecen en la muestra es una variable aleatoria con distribución binomial, por tanto:</p>
<span class="math display">\[\begin{equation*}
    \begin{split}
        \text{E}(X) &amp;=np\\
        \text{V}(X) &amp; = np(1-p)
    \end{split}
\end{equation*}\]</span>
<p>En nuestro caso se cumplen sobradamente las condiciones para poder aproximar la distribución de <span class="math inline">\(X\)</span> a través de una Normal, por tanto, podemos considerar que: <span class="math display">\[X \sim \text{N} \left (np; \sqrt{np(1-p)} \right )\]</span> Si en vez del número de cumplidores consideramos su proporción <span class="math inline">\(\frac{X}{n}\)</span>, recordando las reglas para operar con variables aleatorias, tenemos:</p>
<span class="math display">\[\begin{equation*}
    \begin{split}
        \text{E} \left ( \frac{X}{n} \right ) &amp;= \frac{1}{n} E(X) = p\\[5pt]
        \text{V} \left ( \frac{X}{n} \right) &amp; =\frac{1}{n^2} V(X) = \frac{p(1-p)}{n}\\
    \end{split}
\end{equation*}\]</span>
<p>Si <span class="math inline">\(X\)</span> sigue una distribución Normal, también seguirá esa distribución la variable <span class="math inline">\(\frac{X}{n}\)</span>. Llamando <span class="math inline">\(\hat{p}\)</span> a la proporción en la muestra, tenemos: <span class="math display">\[\hat{p} \sim N \left ( p; \sqrt{\frac{p(1-p)}{n}} \right ) \]</span></p>
<p>Siguiendo el razonamiento que ya habíamos realizado para deducir la expresión del intervalo de confianza para la media, el intervalo de confianza <span class="math inline">\(1-\alpha\)</span> para el valor de <span class="math inline">\(p\)</span> será: <span class="math display">\[\hat{p} \pm z_{\alpha/2} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}  \]</span></p>
<p>Algunas consideraciones sobre este intervalo:</p>
<ul>
<li><p>En la expresión de la desviación típica sustituimos el valor de <span class="math inline">\(p\)</span> (valor real en la población) por su estimación <span class="math inline">\(\hat{p}\)</span>. La razón es que no hay más remedio, puesto que el valor de <span class="math inline">\(p\)</span> no lo conocemos.</p></li>
<li><p>Consideramos que: <span class="math display">\[\frac{p\; - \;\hat{p}}{\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}}\]</span> sigue una distribución <span class="math inline">\(\text{N}(0; 1)\)</span> aunque los valores de <span class="math inline">\(\hat{p}\)</span> que usamos para estimar la desviación típica son estimados. Es una aproximación razonable si el tamaño de muestra es grande, y seguramente así será si se está usando la aproximación Normal. Si se trabaja con tamaños de muestra pequeños es mejor usar el método exacto.</p></li>
<li><p>El tamaño de la población, <span class="math inline">\(N\)</span>, no aparece en la fórmula ya que se considera infinito. Esto no es una exageración. Lo habitual es que la población sea grande, y los resultados apenas cambian si la población es grande, muy grande o enorme. Más adelante lo comentamos con detalle.</p></li>
</ul>
<p>Con nuestros valores y para una confianza del 95 %, recordando que <span class="math inline">\(z_{0.025} = 1.96\)</span>, tenemos: <span class="math display">\[0.58 \pm 1.96 \sqrt{\frac{0.58 \cdot 0.42}{100}} = 0.58 \pm  0.098 = (0.483;\; 0,677)^{}\]</span> Este intervalo es prácticamente el mismo que el obtenido con el método exacto. La anchura del intervalo no es proporcional a su nivel de confianza. Es más probable que el verdadero valor se encuentre dentro del intervalo de confianza del 50 % que en las «extensiones» que añadimos para pasar de una confianza del 99 % al 99,99 %, aunque estas últimas sean mucho más anchas (<a href="#fig-anchuraIntervalos_2" class="quarto-xref">Figura&nbsp;<span>7.7</span></a>).</p>
<div id="fig-anchuraIntervalos_2" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anchuraIntervalos_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0707_anchuraIntervalos_2.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anchuraIntervalos_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.7: Intervalos con distinto nivel de confianza para una proporción a partir de una muestra de 100 observaciones y 58 con la característica analizada.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>El intervalo de confianza no es homogéneo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un intervalo de confianza lo podemos imaginar como muchos pequeños intervalos puestos uno a continuación de otro. La probabilidad de incluir el valor estimado no es la misma para todos esos intervalos. Será más probable en los más cercanos al estimador puntual y menos en los pegados a los extremos.</p>
</div>
</div>
</section>
</section>
</section>
<section id="cálculo-del-tamaño-de-muestra" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="cálculo-del-tamaño-de-muestra"><span class="header-section-number">7.5</span> Cálculo del tamaño de muestra</h2>
<p>Cuando se calcula el tamaño que debe tener una muestra para poder estimar el valor de interés con el nivel de confianza y el margen de error deseados, lo habitual es considerar que el tamaño de la población es infinito. Salvo raras excepciones, el tamaño de la población será muy grande respecto al de la muestra y en este caso no hay diferencia entre considerar que la población es de un millón de individuos, de cien millones o infinita. También suele ocurrir que cuando nos referimos a la población no nos estamos refiriendo al “conjunto de individuos o elementos objeto de estudio” sino a modelos teóricos que caracterizan el comportamiento de los datos. Las expresiones de los intervalos de confianza que hemos deducido consideran que la población es infinita o –lo que sería equivalente a efectos prácticos– mucho mayor que el tamaño de muestra utilizado.</p>
<p>Vamos a calcular las expresiones del tamaño de muestra para el caso más habitual de considerar que la población es infinita. Para el caso de la estimación de una proporción planteamos también el caso de población finita para poder analizar la relación entre el tamaño de la muestra y el de la población, tema sobre el que existen algunos malentendidos.</p>
<section id="para-estimar-la-media" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="para-estimar-la-media">Para estimar la media</h3>
<p>Partiendo de la expresión del intervalo de confianza para la media de la población, vamos a determinar el tamaño de muestra necesario para estimar el peso medio de los paquetes de café (ejemplo del apartado 7.3) con una confianza del 95 % y un margen de error de 2 g. Considerando que el tamaño de muestra resultante será mayor de 30 unidades<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>, podemos usar la distribución Normal estandarizada igualando el margen de error al valor deseado. Tenemos:</p>
<p><span class="math display">\[z_{0.025} \frac{\sigma}{\sqrt{n}} =2 \]</span> El valor de <span class="math inline">\(\sigma\)</span> se puede conocer a partir de datos históricos, o se puede establecer un valor razonable intentando pecar más bien por exceso. Otra opción es estimarlo a partir de los valores de una primera muestra piloto tomada con este objetivo. En nuestro caso, considerando que la muestra piloto son las 6 unidades del ejemplo (<span class="math inline">\(s = 8.542\)</span>), llamando <span class="math inline">\(E\)</span> al margen de error y despejando <span class="math inline">\(n\)</span> de la expresión anterior: <span class="math display">\[n = \left ( \frac{z_{\alpha/2}\sigma}{E} \right )^2 = \left ( \frac{1.96 \cdot 8.542}{2} \right )^2 = 70.1 \]</span> El tamaño de muestra siempre se redondea por exceso para que el margen de error no supere el valor establecido, de manera que el resultado final es <span class="math inline">\(n=71\)</span>. A la vista de la desviación típica obtenida en las 71 observaciones se puede actualizar el margen de error o, si es necesario, realizar nuevas observaciones para llegar al margen de error previamente establecido.</p>
<p>Observe que –como es lógico– el tamaño de muestra requerido aumenta si se desea un mayor nivel de confianza (aumenta el valor de <span class="math inline">\(z_{\alpha/2}\)</span>) o un menor margen de error (está en el denominador). También aumenta al aumentar la variabilidad de los datos, ya que mayor variabilidad significa también una mayor incertidumbre que solo se compensa con una mayor cantidad de datos.</p>
</section>
<section id="para-estimar-una-proporción" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="para-estimar-una-proporción">Para estimar una proporción</h3>
<p>Despejando el valor de <span class="math inline">\(n\)</span> en la expresión del margen de error de su intervalo de confianza: <span class="math display">\[n = \frac{p(1-p) \cdot z_{\alpha/2}^2}{E^2} \]</span> El valor de <span class="math inline">\(p\)</span> no lo conocemos cuando nos planteamos qué tamaño debe tener la muestra, puesto que ese es el valor que queremos estimar. Lo habitual es ponerse en el caso más desfavorable y considerar <span class="math inline">\(p=0.5\)</span> de manera que <span class="math inline">\(p(1-p) = 0.25\)</span> que es el valor máximo que puede tomar ese producto. Si finalmente el valor de <span class="math inline">\(p\)</span> es distinto de 0,5, el margen de error será menor que el previamente considerado, pero nunca mayor. Si estamos seguros que la proporción que buscamos es como máximo del 20 %, podemos poner <span class="math inline">\(p=0.2\)</span>.</p>
<p>En el ejemplo de la estimación de la proporción de estudiantes que tienen cuenta en una determinada red social, si queremos realizar esa estimación con un nivel de confianza del 95 % y un margen de error del 5 %, considerando<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> <span class="math inline">\(p=0.5\)</span> se obtiene <span class="math inline">\(n=384.1 \rightarrow 385\)</span>.</p>
<section id="población-finita" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="población-finita">Población finita</h4>
<p>La peculiaridad de las poblaciones finitas tiene que ver con que el muestreo se realiza sin reposición. Una vez elegido un elemento de la población ese ya no forma parte de los elegibles y, en consecuencia, las probabilidades de incorporar a la muestra elementos de un cierto tipo depende de cuantos hayan salido ya de ese tipo. Este problema se resuelve aplicando un factor de corrección a la desviación típica del estimador puntual, es lo que llamamos “factor de corrección por población finita”. Siendo <span class="math inline">\(N\)</span> el tamaño de la población y <span class="math inline">\(n\)</span> el de la muestra, tiene la expresión<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>:</p>
<p><span class="math display">\[f = \sqrt{\frac{N-n}{N-1}}\]</span> Si lo población es infinita no importa cuantos elementos hayan salido de un tipo, su proporción se mantiene constante. Si es finita pero <span class="math inline">\(N \gg n\)</span> en la expresión anterior se ve que el valor de <span class="math inline">\(f\)</span> es prácticamente igual a 1.</p>
<p>Incluyendo este factor de corrección, la expresión del intervalo de confianza para una proporción queda: <span class="math display">\[\hat{p} \pm z_{\alpha/2} \sqrt{\frac{N-n}{N-1}} \cdot \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}  \]</span></p>
<p>y despejando el valor de <span class="math inline">\(n\)</span>: <span class="math display">\[n = \frac{z_{\alpha/2}^2 \, N \, p(1 - p)}{E^2 (N - 1) + z_{\alpha/2}^2 \, p(1 - p)}\]</span> Esta es una fórmula cerrada que no tiene ningún misterio. El nivel de confianza está relacionado con el valor de <span class="math inline">\(z_{\alpha/2}\)</span>. Para un nivel de confianza del 95 % (<span class="math inline">\(1-\alpha = 0.95\)</span> y, por tanto, <span class="math inline">\(\alpha/2 = 0.025\)</span>) tenemos que <span class="math inline">\(z_{0.025} = 1.96\)</span>. Observe también que si <span class="math inline">\(N\)</span> es muy grande en el denominador se puede ignorar el valor del segundo término frente al primero y considerando <span class="math inline">\(N \thickapprox N-1\)</span> nos queda la expresión que ya habíamos obtenido: <span class="math display">\[n = \frac{p(1-p) \cdot z_{\alpha/2}^2}{E^2}\]</span> Con la ayuda de una hoja de cálculo se puede construir una tabla como la <a href="#tbl-tamañoMuestra">7.4</a> donde se indica el tamaño de muestra necesario para estimar una proporción en función del tamaño de la población y el margen de error que se está dispuesto a asumir. Los valores que figuran son para un nivel de confianza del 95 %, pero la tabla se puede construir de manera que ese valor se pueda cambiar fácilmente.</p>
<div id="tbl-tamañoMuestra" class="tabla-wrapper_T0704 anchored">

  <div class="tabla-caption">
    Tabla 7.4: Tamaño de la muestra para estimar una proporción con un nivel de confianza del 95 % y el margen de error indicado según sea el tamaño de la población.
  </div>

  
<table class="tabla-0704 caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th rowspan="2" data-quarto-table-cell-role="th">Tamaño de la población</th>
<th colspan="6" data-quarto-table-cell-role="th">Margen de error</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">± 1 %</th>
<th data-quarto-table-cell-role="th">± 2 %</th>
<th data-quarto-table-cell-role="th">± 3 %</th>
<th data-quarto-table-cell-role="th">± 4 %</th>
<th data-quarto-table-cell-role="th">± 5 %</th>
<th data-quarto-table-cell-role="th">± 10 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>500</td>
<td>476</td>
<td>414</td>
<td>341</td>
<td>273</td>
<td>218</td>
<td>81</td>
</tr>
<tr class="even">
<td>1,000</td>
<td>906</td>
<td>707</td>
<td>517</td>
<td>376</td>
<td>278</td>
<td>88</td>
</tr>
<tr class="odd">
<td>1.500</td>
<td>1.298</td>
<td>924</td>
<td>624</td>
<td>429</td>
<td>306</td>
<td>91</td>
</tr>
<tr class="even">
<td>2.000</td>
<td>1.656</td>
<td>1.092</td>
<td>697</td>
<td>462</td>
<td>323</td>
<td>92</td>
</tr>
<tr class="odd">
<td>2.500</td>
<td>1.984</td>
<td>1.225</td>
<td>749</td>
<td>485</td>
<td>334</td>
<td>93</td>
</tr>
<tr class="even">
<td>3.000</td>
<td>2.287</td>
<td>1.334</td>
<td>788</td>
<td>501</td>
<td>341</td>
<td>94</td>
</tr>
<tr class="odd">
<td>3.500</td>
<td>2.566</td>
<td>1.425</td>
<td>818</td>
<td>513</td>
<td>347</td>
<td>94</td>
</tr>
<tr class="even">
<td>4.000</td>
<td>2.825</td>
<td>1.501</td>
<td>843</td>
<td>523</td>
<td>351</td>
<td>94</td>
</tr>
<tr class="odd">
<td>4.500</td>
<td>3.065</td>
<td>1.566</td>
<td>863</td>
<td>530</td>
<td>355</td>
<td>95</td>
</tr>
<tr class="even">
<td>5.000</td>
<td>3.289</td>
<td>1.623</td>
<td>880</td>
<td>536</td>
<td>357</td>
<td>95</td>
</tr>
<tr class="odd">
<td>6.000</td>
<td>3.694</td>
<td>1.715</td>
<td>907</td>
<td>546</td>
<td>362</td>
<td>95</td>
</tr>
<tr class="even">
<td>7.000</td>
<td>4.050</td>
<td>1.788</td>
<td>927</td>
<td>553</td>
<td>365</td>
<td>95</td>
</tr>
<tr class="odd">
<td>8.000</td>
<td>4.365</td>
<td>1.847</td>
<td>942</td>
<td>559</td>
<td>367</td>
<td>95</td>
</tr>
<tr class="even">
<td>9.000</td>
<td>4.647</td>
<td>1.896</td>
<td>955</td>
<td>563</td>
<td>369</td>
<td>96</td>
</tr>
<tr class="odd">
<td>10.000</td>
<td>4.900</td>
<td>1.937</td>
<td>965</td>
<td>567</td>
<td>370</td>
<td>96</td>
</tr>
<tr class="even">
<td>15.000</td>
<td>5.856</td>
<td>2.070</td>
<td>997</td>
<td>578</td>
<td>375</td>
<td>96</td>
</tr>
<tr class="odd">
<td>20.000</td>
<td>6.489</td>
<td>2.144</td>
<td>1.014</td>
<td>583</td>
<td>377</td>
<td>96</td>
</tr>
<tr class="even">
<td>25.000</td>
<td>6.939</td>
<td>2.191</td>
<td>1.024</td>
<td>587</td>
<td>379</td>
<td>96</td>
</tr>
<tr class="odd">
<td>50.000</td>
<td>8.057</td>
<td>2.291</td>
<td>1.045</td>
<td>594</td>
<td>382</td>
<td>96</td>
</tr>
<tr class="even">
<td>100.000</td>
<td>8.763</td>
<td>2.345</td>
<td>1.056</td>
<td>597</td>
<td>383</td>
<td>96</td>
</tr>
<tr class="odd">
<td>500.000</td>
<td>9.423</td>
<td>2.390</td>
<td>1.065</td>
<td>600</td>
<td>384</td>
<td>97</td>
</tr>
<tr class="even">
<td>1.000.000</td>
<td>9.513</td>
<td>2.396</td>
<td>1.066</td>
<td>600</td>
<td>384</td>
<td>97</td>
</tr>
<tr class="odd">
<td>1.500.000</td>
<td>9.543</td>
<td>2.398</td>
<td>1.067</td>
<td>600</td>
<td>384</td>
<td>97</td>
</tr>
<tr class="even">
<td>2.000.000</td>
<td>9.558</td>
<td>2.399</td>
<td>1.067</td>
<td>601</td>
<td>385</td>
<td>97</td>
</tr>
<tr class="odd">
<td>50.000.000</td>
<td>9.602</td>
<td>2.401</td>
<td>1.068</td>
<td>601</td>
<td>385</td>
<td>97</td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="relación-entre-el-tamaño-de-la-muestra-y-el-tamaño-de-la-población" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="relación-entre-el-tamaño-de-la-muestra-y-el-tamaño-de-la-población">Relación entre el tamaño de la muestra y el tamaño de la población</h4>
<p>Guiándonos solo por la intuición parece lógico pensar que el tamaño de la muestra debe estar muy relacionado con el de la población. Nos parece que para un país con 50 millones de habitantes hará falta una muestra mucho mayor que para una ciudad con 50 mil. Incluso hay quien desconfía de un estudio porque “la muestra no llega ni al 10 % de la población”. Pero lo cierto es que esa idea de proporcionalidad entre tamaño de muestra y de población, por muy razonable que parezca, es errónea.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>¿Para saber mi grupo sanguineo se necesita una muestra del 10 % de mi sangre?
</div>
</div>
<div class="callout-body-container callout-body">
<p>No, basta una gota, porque todas las gotas son iguales. La misma cantidad de sangre se requiere para un recién nacido que pesa 3 kg que para su padre de 85 kg.</p>
</div>
</div>
<p>En la <a href="#tbl-tamañoMuestra">Tabla 7.4</a> fijándonos, por ejemplo, en la columna que corresponde a un margen de error del 3 % vemos que el tamaño de muestra aumenta con el tamaño de la población, pero a partir de cierto tamaño de la población aumenta muy lentamente. Para una población de 50.000 individuos hace falta una muestra de 1.045, pero si multiplicamos por 10 el tamaño de la población (pasamos de 50 a 500 mil) el tamaño de muestra apenas cambia (pasa de 1.045 a 1.065) y a partir de ahí se mantiene prácticamente constante.</p>
<div id="fig-grafTamañoMuestra" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-grafTamañoMuestra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0708_grafTamañoMuestra.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grafTamañoMuestra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.8: Tamaño de muestra en función del tamaño de la población para los márgenes de error (E) que se indican, bajo el supuesto de <span class="math inline">\(p=q=0.5\)</span> y un nivel de confianza del 95 %.
</figcaption>
</figure>
</div>
<p>Una analogía muy eficaz para convencernos de que el tamaño de la muestra no debe crecer proporcionalmente con el de la población es el de la cuchara para catar la sopa. Cuando tenemos invitados y usamos una olla mucho mayor que la habitual, tamaño de la cuchara para probarla (el tamaño de la muestra) sigue siendo el mismo, y a nadie le extraña que esto sea así.</p>
<div id="fig-cucharillaOlla" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cucharillaOlla-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0709_cucharillaOlla.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cucharillaOlla-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.9: La cuchara es la misma. No importa el tamaño de la olla, pero hay que remover bien para que la muestra sea representativa.
</figcaption>
</figure>
</div>
</section>
<section id="lo-más-importante-es-que-la-muestra-sea-representativa" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="lo-más-importante-es-que-la-muestra-sea-representativa">Lo más importante es que la muestra sea REPRESENTATIVA</h4>
<p>Los razonamientos y las fórmulas a que hemos llegado se basan en la hipótesis de que las muestras son representativas. Si no lo son, los cálculos pueden aparentar mucho rigor pero ser totalmente inútiles. Con tamaños de muestra relativamente pequeños se puede extraer información valiosa si la muestra es representativa, pero si no lo es, por grande que sea, las conclusiones pueden estar totalmente alejadas de la realidad. En la analogía de la olla todos sabemos que es mucho más importante remover antes de tomar la muestra que aumentar el tamaño de la cuchara y, por supuesto, los problemas derivados de no remover bien no se resuelven con el uso de una cuchara más grande.</p>
<p>La representatividad de la muestra no se justifica con fórmulas sino con argumentos, y ahí parece que todo el mundo se siente con capacidad para argumentar que se ha hecho lo que se ha podido. El tamaño de la muestra se justifica con fórmulas y cálculos de manera que ese puede parecer un terreno “más serio” y se toma con mayor interés pero, en realidad, el tamaño de la muestra es irrelevante si no estamos seguros de su representatividad.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>La olla y la cuchara: Lo más importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Lo más importante es remover bien para que la muestra sea representativa. El pecado de no remover no se perdona usando una cuchara más grande.</p>
</div>
</div>
</section>
</section>
</section>
<section id="otras-estimaciones-tamaño-de-la-población" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="otras-estimaciones-tamaño-de-la-población"><span class="header-section-number">7.6</span> Otras estimaciones: Tamaño de la población</h2>
<p>Hay casos en que el objetivo es conocer el tamaño de la población, como cuando se quiere estimar la abundancia de un cierto tipo de animal en un territorio, ya sea porque es una especie en peligro de extinción o una especie invasora o dañina. Una forma habitual de hacerlo es mediante la técnica denominada “captura y recaptura”.</p>
<section id="cuántos-peces-hay-en-un-lago" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="cuántos-peces-hay-en-un-lago">¿Cuántos peces hay en un lago?</h3>
<p>La idea es capturar un cierto número de peces sin dañarlos, marcarlos y volverlos a soltar. Pasado un cierto tiempo se realiza otra captura y se cuenta el número de los que aparecen marcados. Un método habitual de captura de peces es el llamado electropesca que consiste en aplicar una descarga eléctrica que los aturde temporalmente y los deja flotando de manera que se pueden capturar fácilmente. Tanto las capturas como las recapturas se pueden realizar en distintos puntos del lago y la forma de hacerlas dependerá del tipo de peces que lo habitan o, si interesa contar solo los de una especie, de los hábitos que tenga esa especie.</p>
<section id="estimación-puntual-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="estimación-puntual-2">Estimación puntual</h4>
<p>Sea <span class="math inline">\(N\)</span> el número total de peces en el lago y <span class="math inline">\(M\)</span> el número de los capturados y marcados en la primera pesca; la proporción de peces marcados en el lago será igual a <span class="math inline">\(M/N\)</span>. En la repesca capturamos una muestra de <span class="math inline">\(n\)</span> peces y aparecen <span class="math inline">\(m\)</span> marcados. Entendiendo que esta segunda muestra es representativa de los peces que hay en el lago, la proporción de los que aparecen marcados <span class="math inline">\(m/n\)</span> será un estimador de la proporción de peces marcados en el lago. Es decir: <span class="math display">\[\frac{m}{n}~~ \text {es un estimador de:}~~ \frac{M}{N}\]</span> Así pues, si consideramos que: <span class="math display">\[\frac{m}{n} \approx \frac{M}{N}\]</span> despejar <span class="math inline">\(N\)</span> y tenemos: <span class="math display">\[\hat{N} = \frac{M \cdot n}{m}\]</span> Con los datos de la <a href="#fig-pescaRepesca" class="quarto-xref">Figura&nbsp;<span>7.10</span></a> nuestra estimación para el número total de peces es $ = (15)/3=75$. No se trata de un método exacto, en realidad en el dibujo hay 67 peces y, por tanto, cometeríamos un error del 12 %, pero permite tener un orden de magnitud que puede ser útil a efectos prácticos.</p>
<div id="fig-pescaRepesca" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pescaRepesca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0710_pescaRepesca.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pescaRepesca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.10: Estimación del número de peces por el procedimiento de pesca y repesca.
</figcaption>
</figure>
</div>
</section>
<section id="intervalo-de-confianza-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="intervalo-de-confianza-2">Intervalo de confianza</h4>
<p>Supongamos que se realiza una primera captura de <span class="math inline">\(M=100\)</span> peces y una recaptura, <span class="math inline">\(n\)</span>, del mismo número en la que aparecen <span class="math inline">\(m=10\)</span> marcados. El estimador puntual del número de peces en el lago es:</p>
<p><span class="math display">\[N = \frac{M \cdot n}{m} = \frac{100 \cdot 100}{10} = 1000\]</span> Para construir un intervalo de confianza podemos considerar que el número de peces que aparecen marcados es una variable aleatoria con distribución binomial y parámetros <span class="math inline">\(n=100\)</span> (número de peces que se inspeccionan en la repesca) y un valor de <span class="math inline">\(p\)</span> igual a la proporción de peces marcados en el lago (proporción en la población<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>).</p>
<p>En primer lugar vamos a determinar el valor de <span class="math inline">\(p\)</span> que hace que la probabilidad de que aparezcan 10 o más peces marcados sea igual a 0,025, es decir, el valor <span class="math inline">\(p_1\)</span> que hace que se cumpla la igualdad: <span class="math display">\[0.025 = 1-\text{B}(9; 100; p_1) \]</span> donde $ (x; n; p)$ se refiere a $ (X x)$ siendo <span class="math inline">\(X\)</span> una variable aleatoria con distribución binomial y parámetros <span class="math inline">\(n\)</span> y <span class="math inline">\(p\)</span>.</p>
<p>Una forma fácil de encontrar el valor de <span class="math inline">\(p_1\)</span> es tanteando con la ayuda de una hoja de cálculo. Se obtiene <span class="math inline">\(p_1 = 0.0490\)</span>.</p>
<p>A continuación determinamos el valor de <span class="math inline">\(p\)</span> que hace que la probabilidad de que aparezcan 10 o menos peces marcados sea también igual a 0,025, es decir, el valor de <span class="math inline">\(p_2\)</span> que cumple la expresión: <span class="math display">\[0.025 = \text{B}(10; 100; p_2) \]</span> y tenemos que <span class="math inline">\(p_2 = 0.1762\)</span>. Si <span class="math inline">\(p\)</span> fuera menor de 0,049 la probabilidad de tener 10 o menos peces marcados sería menor de 0,025, y si fuera mayor de 0,1762 la probabilidad de tener 10 o más también sería menor de 0,025. Por tanto, podemos decir que existe una probabilidad del 95 % de que el valor de <span class="math inline">\(p\)</span> esté entre 0,0490 y 0,1762.</p>
<p>Si la proporción de peces marcados es igual a 0,049, como hay <span class="math inline">\(M=100\)</span> marcados tenemos que <span class="math inline">\(0.049 = 100/N\)</span> y, por tanto <span class="math inline">\(N = 100/0.049 = 2\;\!041\)</span>. Si la proporción de marcados es 0,1762 resulta <span class="math inline">\(N = 568\)</span>. Por tanto, podemos decir que con una probabilidad de aproximadamente el 95 % en el lago habrá entre 568 y <span class="math inline">\(2\;\!041\)</span> peces<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>.</p>
</section>
</section>
<section id="cuántos-taxis-hay-en-una-ciudad" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="cuántos-taxis-hay-en-una-ciudad">¿Cuántos taxis hay en una ciudad?</h3>
<p>Si los taxis llevan a la vista un número de licencia que pertenece a un conjunto de números consecutivos del 1 al total de licencias existentes, estamos ante una población numerada. En este caso, podemos estimar su tamaño, es decir, cuántos taxis hay en la ciudad, sin necesidad de aplicar el método de captura y recaptura</p>
<p>Si <span class="math inline">\(\mu\)</span> es el valor medio de los elementos numerados siempre se cumple que el número total, <span class="math inline">\(N\)</span>, es igual a <span class="math inline">\(2\mu-1\)</span> . Por ejemplo, si los elementos numerados van del 1 al 10 su valor medio es <span class="math inline">\(\mu = 5.5\)</span> y <span class="math inline">\(N=2 \cdot 5.5-1 = 10\)</span>. Utilizando la media de la muestra <span class="math inline">\(\bar{x}\)</span> como estimador de <span class="math inline">\(\mu\)</span> podemos proponer <span class="math inline">\(2\bar{x}-1\)</span> como estimador del tamaño de la población Si los valores que se han recogido son: 8, 14, 22, 27 y 35, como <span class="math inline">\(\bar{x}=21,2\)</span>, nuestra estimación será: <span class="math inline">\(\hat{N}=2 \cdot 21.2-1 = 41\)</span> (redondeado).</p>
<p>Parece un buen método pero tiene un claro punto débil: si los valores de la muestra son 3, 4, 6 y 15, la media es 7 y por tanto nuestra estimación será igual a 13, un valor claramente incorrecto ya que como mínimo hay 15.</p>
<p>En realidad, la única incógnita es saber cuántos elementos hay a continuación del que tiene el número más alto en la muestra. Una opción que no presenta este problema es considerar que, por simetría, el número de valores que irán a continuación del último será similar al de los que hay antes del primero. En nuestro ejemplo, con los valores: 8, 14, 22, 27 y 35, la estimación será <span class="math inline">\(35+7=42\)</span>. Esta estrategia nunca dará resultados evidentemente falsos, pero tiene el inconveniente de que no aprovecha toda la información disponible.</p>
<p>Una buena idea es añadirle el promedio que se calcula con los que hay antes del primero, entre el primero y el segundo, entre el segundo y el tercero, etc. (<a href="#fig-estimacionTaxis" class="quarto-xref">Figura&nbsp;<span>7.11</span></a>). En nuestro ejemplo este promedio es igual a 6 y, por tanto, la estimación será <span class="math inline">\(35+6=41\)</span>, el mismo valor que con el primer método considerado pero este seguro que no da estimaciones claramente incorrectas.</p>
<div id="fig-estimacionTaxis" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-estimacionTaxis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0711_estimacionTaxis.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-estimacionTaxis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.11: Estimador de cuantos elementos hay con un número superior al máximo de los que aparecen en la muestra.
</figcaption>
</figure>
</div>
<p>En general, si <span class="math inline">\(n\)</span> es el número de observaciones y <span class="math inline">\(x_i\)</span> representa el valor de la observación <span class="math inline">\(i\)</span>-ésima, este promedio será: <span class="math display">\[\frac{(x_1-1)+(x_2-x_1-1)+(x_3-x_2-1)+ \cdots +(x_n-x_{n-1}-1)}{n} = \frac{x_n}{n}-1\]</span> Observe que solo es necesario saber cuantos elementos se han mirado (<span class="math inline">\(n\)</span>) y cual es su valor máximo (<span class="math inline">\(x_n\)</span>). No es necesario recordar los valores que han ido saliendo. Aplicado a la estimación del número de taxis que hay en Barcelona, mirando el número de licencia de 20 de ellos obtuvimos una estimación de <span class="math inline">\(10\;\!989\)</span>. En realidad en esa época había <span class="math inline">\(10\;\!523\)</span> (<a href="#fig-taxisNumLicencia" class="quarto-xref">Figura&nbsp;<span>7.12</span></a>).</p>
<div id="fig-taxisNumLicencia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-taxisNumLicencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0712_taxisNumLicencia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-taxisNumLicencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.12: Estimación del número de taxis que hay en Barcelona a la vista del número de licencia de una muestra de 20 de ellos.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Estimando la cantidad de armamento que tiene el enemigo.
</div>
</div>
<div class="callout-body-container callout-body">
<p>En la segunda guerra mundial el número de serie de los tanques alemanes capturados –o los de alguno de sus componentes– sirvió a los ejércitos aliados para estimar el número total de que disponía el ejército alemán. Más información en la Wikipedia: El problema de los tanques alemanes”.</p>
</div>
</div>
<section id="intervalo-de-confianza-para-el-tamaño-de-una-población-numerada" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="intervalo-de-confianza-para-el-tamaño-de-una-población-numerada">Intervalo de confianza para el tamaño de una población numerada</h4>
<p>Si de una población numerada de <span class="math inline">\(N\)</span> elementos tomamos uno al azar, la probabilidad de que su valor sea menor que <span class="math inline">\(k\)</span>, siendo <span class="math inline">\(k \leq N\)</span>, es igual a <span class="math inline">\(k/N\)</span>, ya que en la población hay <span class="math inline">\(k\)</span> casos favorables frente a <span class="math inline">\(N\)</span> posibles y equiprobables. Si tomamos una muestra –sin reposición– de <span class="math inline">\(n=2\)</span> observaciones, la probabilidad de que ambas sean menores que <span class="math inline">\(k\)</span> será igual a la probabilidad de que lo sea la primera (ya hemos visto que es <span class="math inline">\(k/N\)</span>) <strong>y</strong> también la segunda, pero ahora los casos favorables son solo <span class="math inline">\(k-1\)</span> y los posibles <span class="math inline">\(N-1\)</span>. Por tanto: <span class="math display">\[P\left(\max(x_1, x_2) \leq k \right) = \frac{k}{N} \cdot \frac{k-1}{N-1} \]</span> Generalizando a muestras de tamaño <span class="math inline">\(n\)</span>: <span class="math display">\[P\left(\max(x_1, x_2, \cdots, x_n) \leq k \right) = \prod_{i=0}^{n-1}\frac{k-i}{N-i} \]</span> Para aligerar la notación, al valor máximo de una muestra de <span class="math inline">\(n\)</span> elementos le vamos a llamar <span class="math inline">\(M_n\)</span>. Con la fórmula que acabamos de ver podemos calcular <span class="math inline">\(P \left(M_n \leq k \right)\)</span> dados los valores de <span class="math inline">\(N\)</span>, <span class="math inline">\(n\)</span> y <span class="math inline">\(k\)</span>. Por ejemplo, si <span class="math inline">\(N = 12\;\!000\)</span>, <span class="math inline">\(n=20\)</span> y <span class="math inline">\(k=11\:\!500\)</span>,se obtiene (una hoja de cálculo facilita el cálculo): <span class="math display">\[P \left(M_{20} \leq 11\:\!500 \right) = 0.4266\]</span> También es posible calcular esta probabilidad en función de <span class="math inline">\(N\)</span>. La <a href="#fig-taxisIC" class="quarto-xref">Figura&nbsp;<span>7.13</span></a> muestra esa relación en nuestro caso de <span class="math inline">\(n=20\)</span> y <span class="math inline">\(k=11\:\!500\)</span>. Hemos señalado dos valores de <span class="math inline">\(N\)</span> que tienen una probabilidad de ser sobrepasados, por arriba y por abajo, de 0,025. La probabilidad de que <span class="math inline">\(N\)</span> esté entre esos valores es del 95 %. Por tanto, podemos considerar que esos son los extremos de su intervalo de confianza del 95 %.</p>
<div id="fig-taxisIC" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-taxisIC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0713_taxisIC.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-taxisIC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.13: Población numerada. Probabilidad de que el valor máximo de una muestra de tamaño 20 sea menor de 11500 en función del tamaño de la población.
</figcaption>
</figure>
</div>
<p>Vemos que el extremo inferior del intervalo de confianza queda muy cerca del valor máximo de la muestra. En vez de repartir la probabilidad de equivocarnos entre los dos extremos, podemos concentrarla en el extremo superior, que con nuestros valores es igual a 13;!356. En este caso, diremos que el intervalo está entre 11:!500 (por ese lado seguro que no nos equivocamos) y 13;!356 (la probabilidad de que sea superior es del 5 %).</p>
</section>
</section>
</section>
<section id="apéndice-7.a-distribución-de-la-media-muestral-visión-intuitiva" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-7.a-distribución-de-la-media-muestral-visión-intuitiva">APÉNDICE 7.A: Distribución de la media muestral: Visión intuitiva</h2>
<p>Vamos a echar mano del socorrido ejemplo de la distribución de las estaturas, que supondremos <span class="math inline">\(\text{N} (170\,\text{cm}; \; 7 \text{cm})\)</span>. Si tomamos una muestra de 25 personas, sus estaturas pueden ser los valores representados para la muestra 1 en la <a href="#fig-distribucionMedia" class="quarto-xref">Figura&nbsp;<span>7.14</span></a>. Estos valores van de 158 a 183 y su valor medio –representado con un recuadro rojo– es igual a 169,8. Si vamos generando muestras aleatorias de esa población, cada una tendrá sus propios valores y, por tanto, también una media distinta. En la <a href="#fig-distribucionMedia" class="quarto-xref">Figura&nbsp;<span>7.14</span></a> se han representado los valores de 10 muestras aleatorias de esa misma población, marcando también sus valores medios. En la parte inferior se han representado solo esos valores medios y está claro que tienen variabilidad –la media muestral es una variable aleatoria– pero menos que las observaciones individuales.</p>
<div id="fig-distribucionMedia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distribucionMedia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0714_distribucionMedia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distribucionMedia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.14: Valores de 10 muestras aleatorias de una población N(170; 7) con sus medias (recuadro rojo). En la parte inferior solo se representan las medias.
</figcaption>
</figure>
</div>
</section>
<section id="apéndice-7.b-número-de-taxis-análisis-de-la-calidad-de-la-estimación-usando-una-hoja-de-cálculo" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-7.b-número-de-taxis-análisis-de-la-calidad-de-la-estimación-usando-una-hoja-de-cálculo">APÉNDICE 7.B: Número de taxis: Análisis de la calidad de la estimación usando una hoja de cálculo</h2>
<p>Supongamos que en una ciudad hay <span class="math inline">\(12\;\!000\)</span> taxis. ¿Cuál sería nuestra estimación observando el número de licencia de solo 20 de ellos?</p>
<p>Lo vamos a ver simulando con una hoja de cálculo, primero de una forma muy sencilla, sin acumular los resultados y a continuación veremos como los podemos acumular para observar la distribución.</p>
<section id="sin-acumular-resultados" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="sin-acumular-resultados">Sin acumular resultados</h4>
<p>En la primera columna colocamos valores del 1 al <span class="math inline">\(12\;\!000\)</span> (número total –que queremos estimar– de elementos en la población) y en la segunda <span class="math inline">\(12\;\!000\)</span> números aleatorios <span style="font-family: monospace;">=aleatorio()</span>. Si ordenamos los números aleatorios arrastrando los de la primera columna lo que hacemos es desordenar al azar los de esa primera columna, de manera que los 20 primeros se pueden considerar una muestra aleatoria del total. Solo hace falta identificar el máximo de esos 20 <span style="font-family: monospace;">=max(a1:a20)</span> y aplicar la fórmula que ya sabemos.</p>
<p>En la <a href="#fig-hojaExcel_1" class="quarto-xref">Figura&nbsp;<span>7.15</span></a> se muestran las primeras filas. En la columna C se tiene una copia de los 20 primeros valores de la columna A para que se vea claro cuales son los valores de la muestra. Si se vuelven a desordenar los valores de la primera columna se tendrá otra muestra, otro valor máximo y otra estimación. Para ir teniendo nuevos valores basta con pulsar la tecla F4 ya que de esta forma se repite la última operación realizada, en este caso ordenación de los números aleatorios arrastrando los de la primera columna.</p>
<div id="fig-hojaExcel_1" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hojaExcel_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0715_hojaExcel_1.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hojaExcel_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.15: Estimación del tamaño de una población numerada con Excel.
</figcaption>
</figure>
</div>
</section>
<section id="acumulando-resultados" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="acumulando-resultados">Acumulando resultados</h4>
<p>Para que los resultados no se vayan superponiendo sino que se vayan acumulando de manera que se pueda observar su distribución podemos completar la tabla de la siguiente forma:</p>
<div class="tabla-wrapper_T07_Ape_B">

<table class="tabla-Ape7B caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 85%">
</colgroup>
<tbody>
<tr class="odd">
<td>Columna</td>
<td>Contenido</td>
</tr>
<tr class="even">
<td>F</td>
<td>Primera celda: colocar un 0. Después lo sustituiremos por un 1<br>
para que vaya sumando al contador.</td>
</tr>
<tr class="odd">
<td>G</td>
<td>Primera celda: Escribimos: <span style="font-family: monospace;">=G2+F2</span>. Es el contador.</td>
</tr>
<tr class="even">
<td>H</td>
<td>Primera celda: colocar un 0. Colocar en las celdas valores del 1 al 1000, o hasta el número de<br>
valores que queremos acumular.</td>
</tr>
<tr class="odd">
<td>I</td>
<td>Primera celda: Poner <span style="font-family: monospace;">=SI(G\$2=H2;E\$2;I2)</span> y copiarlo tantas veces<br>
como número de valores queremos acumular (tantos valores como<br>
haya en la columna H).</td>
</tr>
</tbody>
</table>

</div>
<p>A continuación seguimos el siguiente procedimiento:</p>
<ul>
<li><p>Activar la opción de cálculo iterativo. Depende de la versión que se esté usando. En general hay que ir a Archivo &gt; Opciones &gt; Fórmulas y marcar la opción correspondiente</p></li>
<li><p>Sustituir el 0 de la primera celda de la columna F por un 1.</p></li>
<li><p>Ordenar los números aleatorios arrastrando en la ordenación a los de la primera columna (igual que cuando no se acumulaban).</p></li>
<li><p>Pulsar F4 para repetir la simulación. Los valores obtenidos se irán acumulando en la columna I.</p></li>
</ul>
<p>Se puede completar la hoja tabulando los resultados obtenidos y construyendo un gráfico que muestre su distribución (<a href="#fig-excelSimulaTaxis" class="quarto-xref">Figura&nbsp;<span>7.16</span></a>).</p>
<div id="fig-excelSimulaTaxis" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-excelSimulaTaxis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_07/f0716_excelSimulaTaxis.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-excelSimulaTaxis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.16: Estimación del tamaño de una población numerada. Resultados de la simulación con Excel.
</figcaption>
</figure>
</div>
<div style="text-align: center; font-size: 1.1em;">
<p>________________________ <span style="margin: 0 0.4em;">◇</span> ________________________</p>
</div>
<p><br></p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Es controvertido usar la palabra “probabilidad” en este contexto, pero a nosotros nos parece que ayuda a entender lo que representa y no es ningún disparate conceptual}<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Se menciona en el capítulo 5. Dice que la suma y, por tanto, también el valor medio, de un conjunto de <span class="math inline">\(n\)</span> variables aleatorias tiende a una distribución Normal a medida que aumenta el valor de <span class="math inline">\(n\)</span>. Incluso con datos de distribuciones discretas muy diferentes de la Normal, como el resultado de lanzar un dado, la distribución del valor medio se aproxima a la Normal con valores relativamente pequeños de <span class="math inline">\(n\)</span> (figura 5.1).<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Esta es una de las distribuciones que más aparecen en los análisis estadísticos. Volverá a tener protagonismo el el capítulo 9 (test de la <span class="math inline">\(t\)</span> de Student) y se describe con más detalle en el Apéndice 9.C}.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>En realidad, como el muestreo se hace sin reposición, la proporción <span class="math inline">\(p\)</span> no se mantiene exactamente constante, ya que va variando según el tipo de elementos que se extraen. Sin embargo, si el tamaño de la población es mucho mayor que el de la muestra, esta diferencia es irrelevante a efectos prácticos.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Puede dar un vistazo a “Binomial proportion confidence interval” en la Wikipedia.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Si, finalmente, el tamaño de muestra resulta ser menor de 30 se pueden recalcular los valores del margen de error o del nivel de confianza usando una <span class="math inline">\(t\)</span> de Student con un número de grados de libertad en relación con el tamaño de muestra obtenido. Este puede ser un proceso iterativo aunque no es necesario hilar muy fino porque las diferencias no suelen ser relevantes a efectos prácticos.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>A <span class="math inline">\(1-p\)</span> se le denomina <span class="math inline">\(q\)</span>, y este supuesto se encuentra muchas veces planteado de la forma <span class="math inline">\(p=q=50 %\)</span><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>La deducción de este factor de corrección no es trivial. Los lectores interesados pueden consultar, por ejemplo: Steven K. Thompson: “Sampling”, Wiley, 2012, pp: 20-22, o el clásico: William G. Cochran: Sampling Techniques, Wiley, 1977, pp: 21-27.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Como el muestreo se realiza sin reposición, en rigor el valor de p no es constante para todos los peces, pero considerando que el número de peces en el lago es mucho mayor que el número de la repesca, consideramos que esa proporción apenas cambia.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Existen otros procedimientos para transformar el número de peces que aparecen marcados en número de peces total que dan una estimación más precisa y con menos sesgo. Para profundizar en este tema pueden consultarse textos especializados como el de Charles J. Krebs: ``Ecological Methodology’’. 1999, Ed. Addison Wesley.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06_muestreo.html" class="pagination-link" aria-label="Muestreo. Encuestas">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Muestreo. Encuestas</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./0_04_tapaSignificativo.html" class="pagination-link" aria-label="ESTADÍSTICAMENTE SIGNIFICATIVO">
        <span class="nav-page-text">ESTADÍSTICAMENTE SIGNIFICATIVO</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>