<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Regresión simple – &lt;span style="font-size: 1.5em;"&gt;Estadística&lt;/span&gt;&lt;br&gt;
&lt;span style="font-size: 1em;"&gt;Entender - Aplicar - Enseñar&lt;/span&gt;</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./12_regreMultiple.html" rel="next">
<link href="./10_relacionLineal.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2cf3c65c5b6db5ec86e992953759863e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0_05_tapaCorrelacion.html">CORRELACIÓN Y REGRESIÓN</a></li><li class="breadcrumb-item"><a href="./11_regreSimple.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regresión simple</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"><span style="font-size: 1.5em;">Estadística</span><br> <span style="font-size: 1em;">Entender - Aplicar - Enseñar</span></a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PRESENTACIÓN</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./00_Prologo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prólogo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_01_tapaDescriptiva.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ESTADÍSTICA DESCRIPTIVA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_sintesisNumerica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Síntesis numérica de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Graficos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Representaciones gráficas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_02_tapaVariabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DESCRIBIR LO ALEATORIO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_variablesAleatorias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variables aleatorias</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_distribucionesProbabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Distribuciones de probabilidad</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_03_tapaMuestraPoblacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DE LA MUESTRA A LA POBLACIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_muestreo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Muestreo. Encuestas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_estimacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estimación de características de la población</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_04_tapaSignificativo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ESTADÍSTICAMENTE SIGNIFICATIVO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_contrasteHipotesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Contraste de hipótesis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_algunosTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Algunos test clásicos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_05_tapaCorrelacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CORRELACIÓN Y REGRESIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_relacionLineal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Medidas de relación lineal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_regreSimple.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regresión simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_regreMultiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Regresión Múltiple</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./0_06_tapaEpilogo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">EPÍLOGO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_Epilogo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Datos frente a opiniones</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#modelo-determinista-frente-a-modelo-estadístico" id="toc-modelo-determinista-frente-a-modelo-estadístico" class="nav-link active" data-scroll-target="#modelo-determinista-frente-a-modelo-estadístico"><span class="header-section-number">11.1</span> Modelo determinista frente a modelo estadístico</a></li>
  <li><a href="#ajuste-a-una-recta" id="toc-ajuste-a-una-recta" class="nav-link" data-scroll-target="#ajuste-a-una-recta"><span class="header-section-number">11.2</span> Ajuste a una recta</a>
  <ul class="collapse">
  <li><a href="#a-ojo" id="toc-a-ojo" class="nav-link" data-scroll-target="#a-ojo">A ojo</a></li>
  <li><a href="#método-de-ishikawa" id="toc-método-de-ishikawa" class="nav-link" data-scroll-target="#método-de-ishikawa">Método de Ishikawa</a></li>
  <li><a href="#haciendo-que-la-suma-de-los-residuos-sea-igual-a-cero" id="toc-haciendo-que-la-suma-de-los-residuos-sea-igual-a-cero" class="nav-link" data-scroll-target="#haciendo-que-la-suma-de-los-residuos-sea-igual-a-cero">Haciendo que la suma de los residuos sea igual a cero</a></li>
  <li><a href="#minimizando-la-suma-del-valor-absoluto-de-los-residuos" id="toc-minimizando-la-suma-del-valor-absoluto-de-los-residuos" class="nav-link" data-scroll-target="#minimizando-la-suma-del-valor-absoluto-de-los-residuos">Minimizando la suma del valor absoluto de los residuos</a></li>
  <li><a href="#minimizando-la-suma-de-los-cuadrados-de-los-residuos" id="toc-minimizando-la-suma-de-los-cuadrados-de-los-residuos" class="nav-link" data-scroll-target="#minimizando-la-suma-de-los-cuadrados-de-los-residuos">Minimizando la suma de los cuadrados de los residuos</a></li>
  </ul></li>
  <li><a href="#mínimos-cuadrados.-cálculo-de-los-coeficientes" id="toc-mínimos-cuadrados.-cálculo-de-los-coeficientes" class="nav-link" data-scroll-target="#mínimos-cuadrados.-cálculo-de-los-coeficientes"><span class="header-section-number">11.3</span> Mínimos cuadrados. Cálculo de los coeficientes</a>
  <ul class="collapse">
  <li><a href="#sin-fórmulas" id="toc-sin-fórmulas" class="nav-link" data-scroll-target="#sin-fórmulas">Sin fórmulas</a></li>
  <li><a href="#usando-fórmulas" id="toc-usando-fórmulas" class="nav-link" data-scroll-target="#usando-fórmulas">Usando fórmulas</a></li>
  </ul></li>
  <li><a href="#sec-calidadAjuste" id="toc-sec-calidadAjuste" class="nav-link" data-scroll-target="#sec-calidadAjuste"><span class="header-section-number">11.4</span> Calidad del ajuste</a></li>
  <li><a href="#análisis-de-los-residuos" id="toc-análisis-de-los-residuos" class="nav-link" data-scroll-target="#análisis-de-los-residuos"><span class="header-section-number">11.5</span> Análisis de los residuos</a></li>
  <li><a href="#relación-no-lineal-entre-x-e-y" id="toc-relación-no-lineal-entre-x-e-y" class="nav-link" data-scroll-target="#relación-no-lineal-entre-x-e-y"><span class="header-section-number">11.6</span> Relación no lineal entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span></a></li>
  <li><a href="#transformación-logarítmica" id="toc-transformación-logarítmica" class="nav-link" data-scroll-target="#transformación-logarítmica"><span class="header-section-number">11.7</span> Transformación logarítmica</a></li>
  <li><a href="#las-cosas-se-complican-lo-que-tenemos-es-una-muestra" id="toc-las-cosas-se-complican-lo-que-tenemos-es-una-muestra" class="nav-link" data-scroll-target="#las-cosas-se-complican-lo-que-tenemos-es-una-muestra"><span class="header-section-number">11.8</span> Las cosas se complican: Lo que tenemos es una muestra</a></li>
  <li><a href="#distribución-de-los-coeficientes" id="toc-distribución-de-los-coeficientes" class="nav-link" data-scroll-target="#distribución-de-los-coeficientes"><span class="header-section-number">11.9</span> Distribución de los coeficientes</a>
  <ul class="collapse">
  <li><a href="#condiciones-que-deben-reunir-los-datos" id="toc-condiciones-que-deben-reunir-los-datos" class="nav-link" data-scroll-target="#condiciones-que-deben-reunir-los-datos">Condiciones que deben reunir los datos</a></li>
  </ul></li>
  <li><a href="#significación-de-los-coeficientes" id="toc-significación-de-los-coeficientes" class="nav-link" data-scroll-target="#significación-de-los-coeficientes"><span class="header-section-number">11.10</span> Significación de los coeficientes</a>
  <ul class="collapse">
  <li><a href="#visión-intuitiva" id="toc-visión-intuitiva" class="nav-link" data-scroll-target="#visión-intuitiva">Visión intuitiva</a></li>
  <li><a href="#pruebas-de-significación-formales" id="toc-pruebas-de-significación-formales" class="nav-link" data-scroll-target="#pruebas-de-significación-formales">Pruebas de significación formales</a></li>
  </ul></li>
  <li><a href="#intervalos-de-confianza-para-la-respuesta" id="toc-intervalos-de-confianza-para-la-respuesta" class="nav-link" data-scroll-target="#intervalos-de-confianza-para-la-respuesta"><span class="header-section-number">11.11</span> Intervalos de confianza para la respuesta</a></li>
  <li><a href="#malas-prácticas-con-la-regresión-simple" id="toc-malas-prácticas-con-la-regresión-simple" class="nav-link" data-scroll-target="#malas-prácticas-con-la-regresión-simple"><span class="header-section-number">11.12</span> Malas prácticas con la regresión simple</a></li>
  <li><a href="#apéndice-11.a-otra-fórmula-para-b_1" id="toc-apéndice-11.a-otra-fórmula-para-b_1" class="nav-link" data-scroll-target="#apéndice-11.a-otra-fórmula-para-b_1">APÉNDICE 11.A: Otra fórmula para <span class="math inline">\(b_1\)</span></a></li>
  <li><a href="#apéndice-11.b-el-caso-de-la-recta-forzada-a-pasar-por-el-origen" id="toc-apéndice-11.b-el-caso-de-la-recta-forzada-a-pasar-por-el-origen" class="nav-link" data-scroll-target="#apéndice-11.b-el-caso-de-la-recta-forzada-a-pasar-por-el-origen">APÉNDICE 11.B: El caso de la recta forzada a pasar por el origen</a></li>
  <li><a href="#apéndice-11.c-datos-que-no-cumplen-las-condiciones-requeridas" id="toc-apéndice-11.c-datos-que-no-cumplen-las-condiciones-requeridas" class="nav-link" data-scroll-target="#apéndice-11.c-datos-que-no-cumplen-las-condiciones-requeridas">APÉNDICE 11.C: Datos que no cumplen las condiciones requeridas</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./0_05_tapaCorrelacion.html">CORRELACIÓN Y REGRESIÓN</a></li><li class="breadcrumb-item"><a href="./11_regreSimple.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regresión simple</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regresión simple</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Cuando se observa algún tipo de relación entre dos variables, <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span>, puede interesar explicarla a través de una función del tipo <span class="math inline">\(y =f(x)\)</span>, donde a <span class="math inline">\(y\)</span> le llamamos variable dependiente o respuesta y a <span class="math inline">\(x\)</span> variable explicativa o regresora. Esta función sirve para entender qué tipo de influencia tiene <span class="math inline">\(x\)</span> sobre <span class="math inline">\(y\)</span>, y también para realizar estimaciones sobre el valor que tomará <span class="math inline">\(y\)</span> dado un valor de <span class="math inline">\(x\)</span>.</p>
<p>Si la relación es lineal, la ecuación que la describe es la de una recta, que escribimos de la forma: <span class="math inline">\(y = b_0 + b_1x\)</span>. El coeficiente <span class="math inline">\(b_1\)</span> es la pendiente y a <span class="math inline">\(b_0\)</span> a veces se le denomina “constante” (aunque no lo es) o “intercepto” porque es el valor en que la recta “intercepta” al eje de ordenadas. Nosotros le llamaremos “ordenada en el origen”, un nombre más largo pero que no necesita explicación.</p>
<section id="modelo-determinista-frente-a-modelo-estadístico" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="modelo-determinista-frente-a-modelo-estadístico"><span class="header-section-number">11.1</span> Modelo determinista frente a modelo estadístico</h2>
<p>La fórmula que aparece en los libros de física sobre el alcance de un tiro parabólico es un modelo determinista. Dando valores a las variables que intervienen (ángulo, velocidad inicial) se obtiene el valor exacto del alcance. Estos modelos pertenecen al ámbito de la teoría o son una simplificación de la realidad. En la práctica intervienen otras variables no controladas, o no somos capaces de fijar las variables que intervienen en el valor exacto que deben tener, por lo que el resultado siempre está afectado por una cierta incertidumbre.</p>
<p>En los modelos estadísticos esa incertidumbre está explícita. Sabemos que el volumen de madera que se puede obtener de un árbol depende de su altura y del diámetro del tronco, pero dados los valores de estas variables no podemos determinar “exactamente” el volumen de madera que se va a obtener. A partir de los volúmenes y de las características de otros árboles similares podemos crear un modelo estadístico.</p>
<p>En un modelo estadístico entendemos que la ecuación obtenida indica –con mayor o menor precisión– la zona en que se encuentra la respuesta para un determinado valor de la variable regresora. Si tenemos <span class="math inline">\(n\)</span> puntos, el modelo de regresión lineal simple lo escribimos de la forma: <span class="math display">\[y_i = b_0 + b_1 x_i + e_i \quad \text{para} \quad i = 1, 2, \dots, n\]</span> Donde el verdadero valor de la respuesta, <span class="math inline">\(y_i\)</span>, es igual al punto sobre la recta más un valor <span class="math inline">\(e_i\)</span> que llamamos residuo y que no podemos prever. Al punto sobre la recta le llamamos “valor estimado” y para distinguirlo del valor real le colocamos una especie de gorro encima: <span class="math inline">\(\hat{y}_i\)</span>. Por tanto, también podemos escribir: <span class="math display">\[\hat{y}_i = b_0 + b_1 x_i \quad \text{para} \quad i = 1, 2, \cdots, n\]</span> La <a href="#fig-resiRecta" class="quarto-xref">Figura&nbsp;<span>11.1</span></a> (izquierda) contiene un diagrama bivariante con 6 puntos y su recta ajustada, mostrando el residuo correspondiente a cada punto. A la derecha tenemos la ecuación de la recta y la identificación de sus parámetros.</p>
<div id="fig-resiRecta" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resiRecta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1101_resiRecta.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resiRecta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.1: Para cada punto se indica su residuo. A la derecha, ecuación de la recta.
</figcaption>
</figure>
</div>
<p>Los residuos tienen un papel protagonista cuando se ajusta un modelo de regresión. El método de ajuste habitual consiste en elegir la ecuación que minimiza la suma de los cuadrados de los residuos. Trataremos este método con detalle pero vamos a empezar explorando otras posibles alternativas.</p>
</section>
<section id="ajuste-a-una-recta" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="ajuste-a-una-recta"><span class="header-section-number">11.2</span> Ajuste a una recta</h2>
<p>Si entre la respuesta y la variable regresora se observa una relación lineal, se determina la ecuación de la recta que mejor se adapta a los puntos disponibles. Lo que significa “mejor” es discutible. Veamos algunas formas de hacerlo.</p>
<section id="a-ojo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="a-ojo">A ojo</h3>
<p>Se traza la recta directamente sobre el papel o se identifican dos puntos de paso y a partir de ellos se calculan los coeficientes del modelo.</p>
<p>A pesar de sus evidentes limitaciones, si solo se trata de tener la recta no es un método tan malo como parece. Con un poco de práctica el ajuste no será muy distinto del “perfecto” y no se cometerán errores de bulto debido a la presencia de valores anómalos, cosa que sí puede ocurrir si se tratan los datos de forma automática sin mirarlos.</p>
<div id="fig-regresionAOjo" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regresionAOjo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1102_regresionAOjo.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regresionAOjo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.2: Ajuste a ojo y el que minimiza la suma de los cuadrados de los residuos.
</figcaption>
</figure>
</div>
<div id="tbl-ProsCons" class="tabla-wrapper04 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 11.1: Ajuste a ojo. Ventajas e inconvenientes.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Intuitivo. Muy fácil de entender.</li>
<li>No se cometen errores de mucho bulto.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>No se logra el ajuste "perfecto"</li>
<li>No se tienen medidas de calidad del ajuste.</li>
<li>Solo sirve para regresión simple.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="método-de-ishikawa" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="método-de-ishikawa">Método de Ishikawa</h3>
<p>Se identifica el primer y el tercer cuartil de los valores de <span class="math inline">\(X\)</span> <span class="math inline">\((X_{Q1}\)</span> y <span class="math inline">\(X_{Q3})\)</span>, e igual para los valores de <span class="math inline">\(Y\)</span> <span class="math inline">\((Y_{Q1}\)</span> y <span class="math inline">\(Y_{Q3})\)</span>. Se traza la recta por los puntos <span class="math inline">\((X_{Q1}\)</span>,;<span class="math inline">\(Y_{Q1})\)</span> y <span class="math inline">\((X_{Q3}\)</span>,;<span class="math inline">\(Y_{Q3})\)</span>. Se obtiene una recta muy razonable sin necesidad de realizar cálculos ni de aplicar fórmulas de las que se desconoce su lógica.</p>
<div id="fig-regresionIshikawa" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regresionIshikawa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1103_regresionIshikawa.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regresionIshikawa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.3: Ajuste por el método de Ishikawa y el que minimiza la suma de los cuadrados de los residuos.
</figcaption>
</figure>
</div>
<div id="tbl-ProsCons" class="tabla-wrapper04 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 11.2: Método de Ishikawa. Ventajas e inconvenientes.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Fácil de entender.</li>
<li>Robusto frente a la presencia de valores anómalos o con excesiva influencia.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>No se tienen medidas de calidad del ajuste.</li>
<li>Solo sirve para regresión simple.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Kaoru Ishikawa (1915-1989)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Fue un ingeniero japonés, considerado uno de los artífices del llamado “milagro japonés” que condujo los productos japoneses desde la mediocridad hasta arrasar en los mercados mundiales (electrónica, fotografía, automoción…). Una de las claves del éxito fue el uso intensivo de técnicas estadísticas para el control y la mejora de la calidad. Ishikawa es conocido por proponer el uso de herramientas sencillas, que todos puedan entender y aplicar de forma habitual.</p>
</div>
</div>
</section>
<section id="haciendo-que-la-suma-de-los-residuos-sea-igual-a-cero" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="haciendo-que-la-suma-de-los-residuos-sea-igual-a-cero">Haciendo que la suma de los residuos sea igual a cero</h3>
<p>Se trata de obtener los valores de <span class="math inline">\(b_0\)</span> y <span class="math inline">\(b_1\)</span> que cumplen la expresión: <span class="math display">\[\sum_{i=1}^n \left[ Y_i - (b_0 + b_1 X_i) \right]= 0\]</span> que es equivalente a: <span class="math inline">\(n\bar{Y} - nb_0 - b_1 n \bar{X} = 0\)</span>. Por tanto, con cualquier par de valores <span class="math inline">\(b_0\)</span> y <span class="math inline">\(b_1\)</span> que verifiquen la expresión <span class="math inline">\(\bar{Y} = b_0 + b_1 \bar{X}\)</span>, es decir, con cualquier recta que pase por (<span class="math inline">\(\bar{X}\)</span>, <span class="math inline">\(\bar{Y}\)</span>) tendremos una suma de residuos igual a cero.</p>
<p>Que haya infinitas rectas que cumplan esa condición es una mala señal, porque seguro que no todas son adecuadas. Para los valores representados en la <a href="#fig-residuosSuma" class="quarto-xref">Figura&nbsp;<span>11.4</span></a> tenemos que <span class="math inline">\(\bar{X}= 6\)</span> y <span class="math inline">\(\bar{Y}= 9\)</span>. Rectas que hacen que la suma de los residuos sea igual a cero son, por ejemplo, la que tiene coeficientes <span class="math inline">\(b_0=9\)</span> y <span class="math inline">\(b_1=0\)</span>, es decir: <span class="math inline">\(Y = 9\)</span>, o también <span class="math inline">\(b_0 = 12\)</span> y <span class="math inline">\(b_1 = -0.5\)</span>, es decir: <span class="math inline">\(Y = 12 -0.5X\)</span> y ambas son claramente muy malos ajustes. <br></p>
<div id="fig-residuosSuma" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residuosSuma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1104_residuosSuma.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residuosSuma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.4: Dos ajustes -claramente muy malos- con suma de residuos igual a cero.
</figcaption>
</figure>
</div>
<div id="tbl-ProsCons" class="tabla-wrapper04 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 11.3: Suma de los residuos igual a cero. Ventajas e inconvenientes.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 2px 0px 16px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 8px 15px 8px 0px; vertical-align: top"><ul>
<li>Ninguna.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 4px 0px 8px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Da un número infinito de soluciones, una de ellas coincide con el ajuste por mínimos cuadrados.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="minimizando-la-suma-del-valor-absoluto-de-los-residuos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="minimizando-la-suma-del-valor-absoluto-de-los-residuos">Minimizando la suma del valor absoluto de los residuos</h3>
<p>Se trata de minimizar: <span class="math display">\[S=\sum_{i=1}^n \left| Y_i - (b_0 + b_1 X_i) \right|\]</span></p>
<p>Puede no tener solución única, pero los resultados posibles son mucho más razonables que en el caso anterior. Un problema específico de este caso es que no existen expresiones analíticas para los coeficientes debido a las dificultades en el manejo de la función “valor absoluto”.</p>
<p>La <a href="#fig-residuosValorAbsoluto" class="quarto-xref">Figura&nbsp;<span>11.5</span></a> muestra dos diagramas con los mismos 4 puntos y las rectas que cumplen el criterio establecido, en todas ellas la suma del valor absoluto de los residuos es igual a 2. La línea azul, que es la misma en los dos diagramas, es la que también minimiza la suma de los cuadrados de los residuos.</p>
<div id="fig-residuosValorAbsoluto" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residuosValorAbsoluto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1105_residuosValorAbsoluto.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residuosValorAbsoluto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.5: Posibles rectas que minimizan la suma de los residuos en valor absoluto.
</figcaption>
</figure>
</div>
<div id="tbl-ProsCons" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 11.4: Minimizando la suma del valor absoluto de los residuos. Ventajas e inconvenientes.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 2px 0px 16px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Poco sensible a la presencia de valores anómalos.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 12px 15px 4px 0px; vertical-align: top"><ul>
<li>No da un ajuste equilibrado entre todos los puntos.</li>
<li>No existe expresión analítica para el cálculo de los coeficientes.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="minimizando-la-suma-de-los-cuadrados-de-los-residuos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="minimizando-la-suma-de-los-cuadrados-de-los-residuos">Minimizando la suma de los cuadrados de los residuos</h3>
<p>Elevamos los residuos al cuadrado para evitar que al sumarlos se compensen los positivos y negativos. Ahora se trata de minimizar:</p>
<span class="math display">\[\begin{equation*}
    S=\sum_{i=1}^n \left[ Y_i - (b_0 + b_1 X_i) \right]^2
\end{equation*}\]</span>
<p>En vez de decir que el criterio de ajuste ha sido “minimizar la suma de los cuadrados de los residuos”, simplemente decimos que hemos ajustado por “mínimos cuadrados”. Este es el método usado en la inmensa mayoría de los casos, produce un ajuste equilibrado de la nube de puntos y está en perfecta sintonía con otras técnicas y medidas que se construyen con criterios similares. Un inconveniente de este método es que el modelo obtenido es sensible a la presencia de valores anómalos, cosa que no ocurre si se minimiza la suma de valores absolutos.</p>
<p>En la primera fila de la <a href="#fig-residuosMinimosCuadrados" class="quarto-xref">Figura&nbsp;<span>11.6</span></a> tenemos una situación típica en la que el ajuste por mínimos cuadrados da un mejor resultado que minimizando la suma del valor absoluto. Sin embargo, en la segunda fila tenemos un caso de puntos perfectamente alineados excepto uno que muy probablemente sería un valor anómalo. Si minimizamos el valor absoluto de los residuos, el ajuste ignora el valor anómalo mientras que ajustando por mínimos cuadrados el valor anómalo tiene una notable influencia sobre la recta ajustada.</p>
<div id="fig-residuosMinimosCuadrados" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residuosMinimosCuadrados-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1106_residuosMinimosCuadrados.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residuosMinimosCuadrados-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.6: Ajustes obtenidos minimizando la suma de valores absolutos y la suma de los cuadrados de los residuos.
</figcaption>
</figure>
</div>
<div id="tbl-ProsCons" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 11.5: Minimizar la suma de los cuadrados de los residuos. Ventajas e inconvenientes.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Proporciona un ajuste muy razonable. El que queremos hacer cuando ajustamos a ojo.</li>
<li>Encaja perfectamente con el resto de técnicas estadísticas que utilizamos.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Los valores anómalos (errores o valores singulares) pueden tener bastante influencia sobre el modelo estimado. Hay que estar atentos para tratar esos puntos adecuadamente.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
</section>
<section id="mínimos-cuadrados.-cálculo-de-los-coeficientes" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="mínimos-cuadrados.-cálculo-de-los-coeficientes"><span class="header-section-number">11.3</span> Mínimos cuadrados. Cálculo de los coeficientes</h2>
<p>Existe una fórmula cerrada y con solución única para cada coeficiente, pero vamos a empezar identificando el valor de los coeficientes sin hacer uso de las fórmulas. Naturalmente, es mucho más rápido y más práctico usarlas o –mejor todavía– usar un paquete de software estadístico o una hoja de cálculo, pero hacerlo sin fórmulas permite entender perfectamente qué es lo que se está haciendo, y también descubrir algún detalle interesante.</p>
<section id="sin-fórmulas" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sin-fórmulas">Sin fórmulas</h3>
<p>Realizamos a ojo una primera estimación del valor de los coeficientes. A continuación, mediante un pequeño programa –o también usando una hoja de cálculo–, hacemos un barrido de los valores de <span class="math inline">\(b_0\)</span> y <span class="math inline">\(b_1\)</span> en torno a los estimados, identificando el par que minimiza la suma de los cuadrados de los residuos.</p>
<p>Vayamos al diagrama de la <a href="#fig-coeficientesSinFormulas" class="quarto-xref">Figura&nbsp;<span>11.7</span></a> (izquierda) que ya habíamos visto en las figuras <a href="#fig-regresionAOjo" class="quarto-xref">Figura&nbsp;<span>11.2</span></a> y <a href="#fig-regresionIshikawa" class="quarto-xref">Figura&nbsp;<span>11.3</span></a>. La recta ajustada a ojo pasa por los puntos (-4,75; 0) y (5,75; 60) por lo que sus coeficientes son: <span class="math inline">\(b_1\)</span> = 5,71 y <span class="math inline">\(b_0\)</span> = 27,14. Sería mucha casualidad que esos fueran los valores exactos que estamos buscando, pero no andarán muy lejos. Vamos a crear una malla de valores de <span class="math inline">\(b_0\)</span> y <span class="math inline">\(b_1\)</span>. Los valores de <span class="math inline">\(b_1\)</span> variarán de 2 a 8 con incrementos de 0,1 y para cada uno de esos, los de <span class="math inline">\(b_0\)</span> irán de 20 a 35 también en saltos de 0,1. A cada combinación de esos dos valores corresponde una recta, y a cada recta una suma de los cuadrados de los residuos. El par de valores que minimizan esa suma de cuadrados son: <span class="math inline">\(b_0\)</span> = 27,0 y <span class="math inline">\(b_1\)</span> = 4,9.</p>
<div id="fig-coeficientesSinFormulas" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coeficientesSinFormulas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1107_coeficientesSinFormulas.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coeficientesSinFormulas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.7: Recta ajustada a ojo (izquierda) y suma de los cuadrados de los residuos para cada par de valores <span class="math inline">\(b_0\)</span> y <span class="math inline">\(b_1\)</span>. En rojo, valores que la minimizan (derecha).
</figcaption>
</figure>
</div>
<p>Sin embargo, lo habitual es que las curvas de nivel sean muy elípticas, de modo que la representación gráfica no siempre es tan evidente. En nuestro caso hemos obtenido una forma más regular haciendo que <span class="math inline">\(\bar{x}=0\)</span>. De este modo, los coeficientes son independientes y las curvas de nivel aparecen como círculos concéntricos, lo que permite apreciar con mayor claridad la idea que queremos ilustrar.</p>
</section>
<section id="usando-fórmulas" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="usando-fórmulas">Usando fórmulas</h3>
<p>En el diagrama que representa la relación entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> cada punto <span class="math inline">\(i\)</span> puede ser identificado por sus coordenadas <span class="math inline">\((x_i, y_i)\)</span> con <span class="math inline">\(1 \leq i \leq n\)</span> siendo <span class="math inline">\(n\)</span> el número total de puntos.</p>
<p>Cada uno de los puntos tiene un residuo asociado <span class="math inline">\(e_i\)</span> y ese residuo es la diferencia entre el valor real de <span class="math inline">\(y\)</span>, es decir, <span class="math inline">\(y_i\)</span> y su valor estimado <span class="math inline">\(\hat{y}_i\)</span>, que es el que estará sobre la recta y será igual a <span class="math inline">\(b_0 + b_1 x_i\)</span>. Por tanto, el valor del residuo asociado al punto <span class="math inline">\(i\)</span> lo podemos escribir de la forma: <span class="math display">\[e_i = y_i - \left( b_0 + b_1 x_i \right)\]</span> y la suma de los cuadrados de los residuos, <span class="math inline">\(S\)</span>, será: <span class="math display">\[S = \sum_{i=1}^n \left(y_i - b_0 - b_1 x_i \right )^2\]</span> Tanto los valores de <span class="math inline">\(y_i\)</span> como los de <span class="math inline">\(x_i\)</span> vienen dados. La suma de cuadrados <span class="math inline">\(S\)</span> es función de los valores de <span class="math inline">\(b_0\)</span> y de <span class="math inline">\(b_1\)</span>. Se trata de hallar los valores de <span class="math inline">\(b_0\)</span> y de <span class="math inline">\(b_1\)</span> que minimizan esa suma de cuadrados. El mínimo lo tendremos en el punto en que la derivada de <span class="math inline">\(S \left(b_0, b_1 \right )\)</span> respecto a <span class="math inline">\(b_0\)</span> y respecto a <span class="math inline">\(b_1\)</span> es igual a cero. Seguro que es un mínimo porque el máximo no está definido.</p>
<p><span class="math display">\[\frac{\partial S}{\partial b_0} = -2 \sum_{i=1}^n \left(y_i - b_0 - b_1 x_i \right )\]</span></p>
<p><span class="math display">\[\frac{\partial S}{\partial b_1} = -2 \sum_{i=1}^n \left(y_i - b_0 - b_1 x_i \right ) x_i\]</span> Igualando a cero estas expresiones:</p>
<p><span id="eq-11.1"><span class="math display">\[\sum_{i=1}^n y_i - nb_0 - b_1 \sum_{i=1}^n x_i = 0 \tag{11.1}\]</span></span></p>
<p><span id="eq-11.2"><span class="math display">\[\sum_{i=1}^n x_i y_i - b_0 \sum_{i=1}^n x_i - b_1 \sum_{i=1}^n  x_i^2  = 0 \tag{11.2}\]</span></span></p>
<p>Dividiendo por <span class="math inline">\(n\)</span> todos los términos de la ecuación <a href="#eq-11.1" class="quarto-xref"><span>11.1</span></a> tenemos:</p>
<p><span class="math display">\[b_0 = \bar{y} - b_1 \bar{x} \]</span></p>
<div style="height: 1px;">

</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>La recta ajustada pasa por el punto <span class="math inline">\((\bar{x}, \bar{y})\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>De la anterior expresión para <span class="math inline">\(b_0\)</span> también se deduce que <span class="math inline">\(\bar{y} = b_0 + b_1\bar{x}\)</span>. Es decir, la recta ajustada minimizando la suma de los cuadrados de los residuos siempre pasa por el punto <span class="math inline">\((\bar{x}, \bar{y})\)</span>.</p>
</div>
</div>
<p>Sustituyendo la expresión de <span class="math inline">\(b_0\)</span> en la ecuación <a href="#eq-11.2" class="quarto-xref"><span>11.2</span></a> tenemos: <span id="eq-11.3"><span class="math display">\[\sum_{i=1}^n x_i y_i - \bar{y} \sum_{i=1}^n x_i +  b_1\bar{x} \sum_{i=1}^n x_i- b_1 \sum_{i=1}^n  x_i^2  = 0 \tag{11.3}\]</span></span></p>
<p>Para aligerar la notación no pondremos los límites a los sumatorios, que siempre son desde <span class="math inline">\(i=1\)</span> hasta <span class="math inline">\(n\)</span>. Despejando <span class="math inline">\(b_1\)</span> llegamos a:</p>
<p><span id="eq-11.4"><span class="math display">\[b_1 = \frac{\sum x_i y_i - \bar{y} \sum x_i}{\sum x_i^2 - \bar{x} \sum x_i} \tag{11.4}\]</span></span></p>
<p>También la expresión de <span class="math inline">\(b_1\)</span> se suele dar de la forma (ver Apéndice 10.A):</p>
<p><span id="eq-11.5"><span class="math display">\[b_1 = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2} \tag{11.5}\]</span></span></p>
<p>A partir de la ecuación <a href="#eq-11.5" class="quarto-xref"><span>11.5</span></a> y recordando las expresiones de la covarianza y del coeficiente de correlación, llegamos a una expresión que también se ve con frecuencia en los libros de texto, seguramente porque una calculadora sencilla da directamente los tres valores que intervienen:</p>
<p><span id="eq-11.6"><span class="math display">\[b_1 = \frac{Cov(XY)}{s_X^2} = \frac{r_{XY} s_X s_Y}{s_X^2} = r_{XY} \frac{s_Y}{s_X} \tag{11.6}\]</span></span></p>
<p>Calculando los coeficientes que corresponden a los datos de la <a href="#fig-coeficientesSinFormulas" class="quarto-xref">Figura&nbsp;<span>11.7</span></a> se obtiene: <span id="eq-11.7"><span class="math display">\[b_0 = 26,9615 \qquad  \qquad b_1 = 4,8616 \tag{11.7}\]</span></span></p>
<p>Ahora sí, con todos los decimales que queramos, aunque dar más decimales de los que tienen los datos es añadir números que no aportan ninguna información, dan una falsa sensación de precisión y complican la lectura del resultado.</p>
<div style="height: 1px;">

</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Nuestro modelo ajustado no es una ecuación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sean, por ejemplo, los puntos: (4; 3), (6; 8), (8; 12), (10; 10), (12; 12). La recta ajustada es: <span class="math inline">\(y = 1+x\)</span>. Si en vez de ajustar <span class="math inline">\(y = f(x)\)</span> se ajusta <span class="math inline">\(x=f(y)\)</span> ¿se obtendrá la ecuación resultante de despejar <span class="math inline">\(x\)</span> en <span class="math inline">\(y=f(x)\)</span>, es decir: <span class="math inline">\(x = -1 + y\)</span>? Si ajustamos <span class="math inline">\(x=f(y)\)</span> la ecuación será: <span class="math inline">\(x=1,57+0,714y\)</span>. No es lo mismo minimizar la suma de los cuadrados de los residuos medidos en dirección vertical que en dirección horizontal (esto último no son los residuos).</p>
</div>
</div>
</section>
</section>
<section id="sec-calidadAjuste" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="sec-calidadAjuste"><span class="header-section-number">11.4</span> Calidad del ajuste</h2>
<p>El gráfico de la izquierda de la <a href="#fig-ArbolMano" class="quarto-xref">Figura&nbsp;<span>11.8</span></a> muestra la relación entre la longitud de la circunferencia (<span class="math inline">\(X\)</span>) de los troncos de un determinado tipo de árbol y el volumen de madera (<span class="math inline">\(Y\)</span>) que se puede obtener de ellos<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Se observa que a más circunferencia mayor volumen de madera, tal como era de esperar, y la ecuación de la recta ajustada es útil para estimar cuánta madera se obtendrá de un tronco de determinado diámetro. Sin embargo, el gráfico de la derecha se ha realizado con los datos de un estudio<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> donde se analiza la relación entre la edad al morir y la longitud de cierta línea de la mano, a partir de una muestra de 50 personas fallecidas. A la vista del diagrama queda claro que no hay ninguna relación entre ambas variables. En este caso el modelo ajustado no sirve para nada. Pero los dos modelos tienen el mismo aspecto y solo a la vista del valor de sus coeficientes es imposible saber cuál de los dos es útil.</p>
<div id="fig-ArbolMano" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ArbolMano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1108_ArbolMano.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ArbolMano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.8: Relación muy clara y relación inexistente, situaciones que no pueden distinguirse solo a la vista del modelo ajustado.
</figcaption>
</figure>
</div>
<p>Es necesario, por tanto, completar el modelo con una medida que informe de la calidad del ajuste. Esa medida es el coeficiente de determinación <span class="math inline">\(R^2\)</span>.</p>
<p>Para calcular el valor de <span class="math inline">\(R^2\)</span> empezamos poniéndonos en el peor de los casos: suponemos que <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son independientes, es decir, que el valor de <span class="math inline">\(X\)</span> no aporta ninguna información sobre el valor de <span class="math inline">\(Y\)</span>. En este caso, la recta que muestra la relación entre ambas variables es una recta horizontal: la estimación del valor de <span class="math inline">\(Y\)</span> es siempre la misma, sin importar el valor de <span class="math inline">\(X\)</span>, y la mejor apuesta para ese valor de <span class="math inline">\(Y\)</span> -a falta de cualquier otra información- es su valor medio <span class="math inline">\(\bar{y}\)</span>. A la suma de los cuadrados de los residuos correspondientes a esa recta horizontal que pasa por <span class="math inline">\(\bar{y}\)</span> le llamamos <span class="math inline">\(Q_Y\)</span>.</p>
<p>A continuación calculamos la suma de los cuadrados de los residuos correspondientes a nuestra recta ajustada (la que minimiza la suma de los cuadrados de los residuos) y le llamamos <span class="math inline">\(Q_R\)</span>. Cuanto mejor sea el ajuste menor será el valor de <span class="math inline">\(Q_R\)</span> y mayor la diferencia entre <span class="math inline">\(Q_Y\)</span> y <span class="math inline">\(Q_R\)</span>.</p>
<p>El valor de <span class="math inline">\(R^2\)</span> es igual a la proporción de <span class="math inline">\(Q_Y\)</span> explicada por <span class="math inline">\(X\)</span>, es decir, la proporción en que disminuye <span class="math inline">\(Q_Y\)</span> gracias a la introducción de <span class="math inline">\(X\)</span> como variable explicativa, es decir: <span class="math display">\[ R^2 = \frac{Q_Y - Q_R}{Q_Y} \]</span></p>
<p>Veamos este cálculo en un ejemplo con datos sencillos. En la <a href="#fig-R2" class="quarto-xref">Figura&nbsp;<span>11.9</span></a> tenemos 5 puntos que podrían representar la relación entre el peso y la estatura de 5 individuos. Si, ignorando la información aportada por la estatura, siempre damos una estimación del peso igual a su valor medio, será como ajustar a una recta horizontal y tendremos una suma de los cuadrados de los residuos <span class="math inline">\(Q_Y = 56\)</span>. Sin embargo, si utilizamos la información que aporta la estatura y realizamos el ajuste minimizando la suma de los cuadrados de los residuos tenemos <span class="math inline">\(Q_R = 16\)</span>.</p>
<p>Hemos reducido la suma de los cuadrados de los residuos de 56 a 16, por tanto: <span class="math display">\[R^2 = \frac{Q_Y - Q_R}{Q_Y} = \frac{56 - 16}{56} = 0.7143\]</span> Normalmente nos referimos a este valor como un porcentaje. En este caso sería el 71,43 %. En los ejemplos de la <a href="#fig-ArbolMano" class="quarto-xref">Figura&nbsp;<span>11.8</span></a> estos valores son del 93,5 % (volumen de madera) y 1,5 % (edad al morir).</p>
<div style="height: 1px;">

</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span><span class="math inline">\(R^2\)</span> es el cuadrado del coeficiente de correlación <span class="math inline">\(r\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>En un modelo de regresión simple, el valor de <span class="math inline">\(R^2\)</span> es igual al cuadrado del coeficiente de correlación<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Este último puede variar entre <span class="math inline">\(-1\)</span> y <span class="math inline">\(1\)</span> por lo que <span class="math inline">\(R^2\)</span> varía entre 0 y 1.</p>
</div>
</div>
<div style="height: 1px;">

</div>
<div id="fig-R2" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-R2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1109_R2.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-R2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.9: Aprovechando la información aportada por la estatura disminuimos la suma de los cuadrados de los residuos.
</figcaption>
</figure>
</div>
</section>
<section id="análisis-de-los-residuos" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="análisis-de-los-residuos"><span class="header-section-number">11.5</span> Análisis de los residuos</h2>
<p>Antes de dar por bueno un ajuste conviene examinar el comportamiento de los residuos. Igual que en el lenguaje habitual, los residuos son aquello que se descarta, lo que no se aprovecha; por eso debemos asegurarnos de que no contienen información relevante.</p>
<p>Los residuos se deben comportar de manera aleatoria, sin que se pueda apreciar en ellos ningún tipo de patrón o de comportamiento predecible. Si muestran algún tipo de regularidad, significa que aún contienen información, y esa información debe incorporarse al modelo en lugar de desecharse.</p>
<p>Una forma habitual de analizar el comportamiento de los residuos es representarlos gráficamente en un diagrama bivariante frente a los valores previstos. En la <a href="#fig-analisisResiduos" class="quarto-xref">Figura&nbsp;<span>11.10</span></a> se muestra la relación entre dos variables, <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>, que a primera vista puede parecer lineal y, de hecho, si se ajusta a una recta se obtiene un coeficiente de determinación muy alto (<span class="math inline">\(R^2=99.35\%)\)</span>. Sin embargo, en el gráfico de residuos frente a valores previstos vemos que los residuos tienen un comportamiento que no es aleatorio: para valores previstos que están en los extremos de su rango de variación, los residuos son positivos, mientras que en los valores centrales son negativos. Realmente, esto ya se ve mirando con detalle los puntos con la recta ajustada. Los puntos muestran una cierta curvatura que no capta el modelo lineal. Esa discrepancia entre el comportamiento de los puntos y la recta ajustada se ve de una forma mucho más clara en el gráfico de residuos en función de los valores sobre la recta.</p>
<div id="fig-analisisResiduos" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-analisisResiduos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1110_analisisResiduos.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-analisisResiduos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.10: El gráfico de residuos frente a valores previstos pone de manifiesto de forma clara que la relación entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> no es lineal.
</figcaption>
</figure>
</div>
<p>Lo que esperamos es que los puntos se distribuyan aleatoriamente en torno a la recta, no que en una zona estén por encima y en otra por debajo. En la <a href="#fig-residuosModCuadra" class="quarto-xref">Figura&nbsp;<span>11.11</span></a> los puntos se han ajustado a un modelo cuadrático. En este caso, la línea ajustada pasa por en medio de los puntos y el gráfico de residuos frente a valores previstos no muestra ningún patrón previsible.</p>
<p>Con este modelo cuadrático el ajuste mejora ligeramente —ahora <span class="math inline">\(R^2=99.79\%\)</span>—, pero lo más importante es que hemos identificado el tipo de relación existente entre las variables analizadas.</p>
<div id="fig-residuosModCuadra" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residuosModCuadra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1111_residuosModCuadra.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residuosModCuadra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.11: Ajuste a un modelo cuadrático y gráfico de residuos frente a valores previstos.
</figcaption>
</figure>
</div>
</section>
<section id="relación-no-lineal-entre-x-e-y" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="relación-no-lineal-entre-x-e-y"><span class="header-section-number">11.6</span> Relación no lineal entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span></h2>
<p>Si a la vista del diagrama bivariante se observa que la relación entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> no es lineal, se puede utilizar el aspecto de la nube de puntos y el conocimiento del fenómeno que se estudia para plantear un modelo que se ajuste a los datos. Los modelos polinómicos de segundo grado son muy versátiles y pueden ser una buena opción. También se puede ajustar a modelos linealizables transformando los valores de <span class="math inline">\(X\)</span>, los de <span class="math inline">\(Y\)</span>, o ambos. Si nuestros datos se ajustan a una función del tipo <span class="math inline">\(y = \beta_0 e^{\beta_1 x}\)</span>, podemos realizar el cambio <span class="math inline">\(y' = \ln y\)</span> obteniendo el modelo lineal: <span class="math inline">\(y' = \ln \beta_0 + \beta_1 x\)</span> a partir del cual se deducen de forma inmediata los coeficientes del modelo original<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p>La <a href="#fig-molinoViento" class="quarto-xref">Figura&nbsp;<span>11.12</span></a> (izquierda) muestra los datos de producción de electricidad de un aerogenerador según sea la velocidad del viento<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. Se observa una relación no lineal ya que cuando la velocidad del viento es baja, pequeños incrementos en la velocidad tienen un impacto importante en la producción de electricidad, mientras que para velocidades altas la producción tiende a estabilizarse. Ajustando a una parábola se obtiene <span class="math inline">\(y = -1,156 + 0,7229x -0,03812x^2\)</span> con un coeficiente de determinación <span class="math inline">\(R^2 = 96,8\%\)</span>, lo cual no está nada mal.</p>
<p>Otra opción es estudiar la producción de electricidad en función de la inversa de la velocidad del viento (figura de la derecha). Creamos la variable <span class="math inline">\(x' = 1/x\)</span> y obtenemos el ajuste: <span class="math inline">\(y = 2,979 - 6,935x'\)</span>, es decir: <span class="math inline">\(y = 2.979 - 6.935/x\)</span>, con un <span class="math inline">\(R^2 = 97.9\%\)</span>, que es también un valor excelente con un modelo más compacto. Trabajar con la inversa de <span class="math inline">\(x\)</span> puede ser una buena alternativa al modelo cuadrático.</p>
<div id="fig-molinoViento" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-molinoViento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1112_molinoViento.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-molinoViento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.12: La relación se linealiza con el cambio de variable: <span class="math inline">\(x' = 1/x\)</span>
</figcaption>
</figure>
</div>
<p>Pero tampoco se debe abusar de las transformaciones. Volviendo a los datos de la <a href="#fig-residuosSuma" class="quarto-xref">Figura&nbsp;<span>11.4</span></a> donde a partir de los pesos de 5 personas (efectivamente son muy pocas, es solo un ejemplo) queremos modelar la relación entre peso y estatura, el modelo lineal es el más razonable (<a href="#fig-ajustePolinomio" class="quarto-xref">Figura&nbsp;<span>11.13</span></a>). Si ajustamos los datos a un modelo cuadrático se tiene un máximo de peso en torno a una estatura de 175 cm lo cual no concuerda con lo que ya sabemos sobre esta relación. El polinomio de tercer grado presenta una forma que tampoco es razonable y el de cuarto grado es un modelo con 5 parámetros (los 4 coeficientes y la ordenada en el origen) y como tenemos 5 puntos, ajusta perfectamente, pero ni es un modelo razonable ni sirve para estimar el peso de un individuo a partir de su altura (sí lo explica para los 5 individuos usados para construir el modelo, pero para esos ya lo sabíamos).</p>
<p>Recuerde que dos puntos se ajustan perfectamente a un modelo con dos parámetros (una recta), tres puntos a un modelo con tres parámetros… etc. Estos son modelos que explican muy bien lo que ya se sabe, pero son inútiles para hacer predicciones, que es lo que –en general– se pretende.</p>
<div id="fig-ajustePolinomio" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ajustePolinomio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1113_ajustePolinomio.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ajustePolinomio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.13: Ir aumentando el grado del polinomio produce modelos con ajustes “forzados” que no sirven para hacer previsiones.
</figcaption>
</figure>
</div>
</section>
<section id="transformación-logarítmica" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="transformación-logarítmica"><span class="header-section-number">11.7</span> Transformación logarítmica</h2>
<p>En algunos casos, los valores de <span class="math inline">\(X\)</span>, los de <span class="math inline">\(Y\)</span>, o ambos, siguen una distribución asimétrica, con valores que aparecen agrupados cerca del origen y muy dispersos hacia los valores altos. Un ejemplo típico de esta situación se da al analizar la relación entre el peso del cerebro y el peso del cuerpo en 62 especies de mamíferos<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>. La mayoría de esos mamíferos pesan poco –la mediana es 3,34 kg– pero algunos, como los elefantes, pesan varias toneladas y algo similar ocurre con el peso de los cerebros. Al realizar el diagrama bivariante del peso del cerebro (<span class="math inline">\(Y\)</span>) frente al peso de cuerpo (<span class="math inline">\(X\)</span>) prácticamente todos los puntos aparecen amontonados en la zona próxima al origen (<a href="#fig-brainBodyOriginal" class="quarto-xref">Figura&nbsp;<span>11.14</span></a>). En estas condiciones ajustar un modelo de regresión no tiene sentido, porque la mayoría de datos actúan como un solo punto y los que están alejados tienen una gran influencia sobre la recta ajustada.</p>
<div id="fig-brainBodyOriginal" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brainBodyOriginal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1114_brainBodyOriginal.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brainBodyOriginal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.14: Diagrama bivariante, con histogramas marginales, del peso del cerebro frente al peso del cuerpo de 62 especies de mamíferos.
</figcaption>
</figure>
</div>
<p>Uno puede caer en la tentación de considerar a los elefantes como valores anómalos y eliminarlos, pero esa no es una buena decisión por dos razones:</p>
<ol type="1">
<li><p>Restringe la validez del modelo, ya no valdrá para todos los mamíferos considerados.</p></li>
<li><p>Al eliminar esos valores y reescalar el gráfico aparecen otros valores anómalos: la persona humana (que da más reparo eliminar), la jirafa, el caballo, la vaca… y al final nos vamos quedando sin puntos.</p></li>
</ol>
<p>En casos como este, la transformación logarítmica “estira” los datos permitiendo un ajuste en el que todos los puntos tienen una influencia similar. Realizando esta transformación en nuestros datos se obtiene –casi parece un milagro– una nube de puntos tal como esperamos tener cuando ajustamos a una recta. El modelo obtenido es: <span class="math display">\[\log(Y) = 0,9271 + 0,7517 \log(X) \quad \text{con} \quad R^2 = 91,95\%\]</span> Volviendo a las variables originales nos queda (el peso del cuerpo está en kg y el del cerebro en g): <span class="math display">\[Y = 8,45 \cdot X^{3/4}\]</span></p>
<div id="fig-brainBodyTransfo" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-brainBodyTransfo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1115_brainBodyTransfo.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-brainBodyTransfo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.15: Peso del cerebro frente al peso del cuerpo antes y después de la transformación logarítmica.
</figcaption>
</figure>
</div>
<p>La transformación logarítmica de los datos es, sin duda, una buena opción en casos como este, pero también tiene efectos secundarios no deseados.</p>
<p>En primer lugar hay que tener en cuenta que los residuos también están en escala logarítmica. Por ejemplo, para el elefante africano (el mayor, parece que la recta pasa por el punto) el valor real del peso del cerebro es de 5712 g y la previsión es de 6229 (+9 %) y para el elefante asiático el valor real es de 4603 g mientras que el valor previsto es de 3031 g (-34 %). El mamífero que presenta mayor residuo positivo es la persona humana (valor real: 1320, previsto: 185, -86 %) mientras que el de mayor residuo negativo corresponde al Yapok (en inglés: Water opossum). Seguramente más interesante que el modelo en sí es conocer qué animales se separan más -por encima y por debajo- del patrón general. Sobre este tema existen muchas publicaciones. Los interesados pueden empezar explorando la Wikipedia (<em>Brain–body mass ratio</em>) y las referencias que incluye.</p>
<div style="height: 1px;">

</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Transformación logarítmica: No importa la base
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sea <span class="math inline">\(y = \ln (x)\)</span> y <span class="math inline">\(z = \log_{10}(x)\)</span>. Tendremos que <span class="math inline">\(e^y = x\)</span> y también que <span class="math inline">\(10^z = x\)</span>, luego <span class="math inline">\(e^y = 10^z\)</span>. Por tanto, <span class="math inline">\(\ln(e^y) = \ln(10^z)\)</span> y es inmediato que: <span class="math inline">\(y = z \cdot \ln(10)\)</span>. Por tanto, cambiar la base del logaritmo equivale a multiplicar por una constante. El aspecto del diagrama bivariante es el mismo con independencia de la base utilizada para la transformación logarítmica, solo cambian las escalas.</p>
</div>
</div>
</section>
<section id="las-cosas-se-complican-lo-que-tenemos-es-una-muestra" class="level2" data-number="11.8">
<h2 data-number="11.8" class="anchored" data-anchor-id="las-cosas-se-complican-lo-que-tenemos-es-una-muestra"><span class="header-section-number">11.8</span> Las cosas se complican: Lo que tenemos es una muestra</h2>
<p>La interpretación de los resultados se complica cuando caemos en la cuenta de que los datos disponibles son solo una muestra de la población de interés. Supongamos que deseamos estudiar la relación entre el peso y la estatura de los jóvenes de cierta edad (haríamos bien en separar hombres y mujeres, pero aquí vamos a ignorar ese aspecto, que trataremos en el siguiente capítulo) y que disponemos de una muestra de 20 jóvenes. Con los datos de esa muestra ajustamos una recta como se ha realizado en la figura <a href="#fig-unaRegresionVA" class="quarto-xref">Figura&nbsp;<span>11.16</span></a> pero, en realidad, esa no es la recta que andamos buscando. Si hubiéramos tomado otra muestra, la recta sería otra –distinta– pero tan válida como la primera. Entonces, ¿cómo se interpreta la recta obtenida?</p>
<div id="fig-unaRegresionVA" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-unaRegresionVA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1116_unaRegresionVA.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-unaRegresionVA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.16: Recta ajustada a partir de los datos de una muestra.
</figcaption>
</figure>
</div>
<p>Como en otros casos, una forma de ver lo que ocurre es simulando. En los diagramas de la <a href="#fig-regresionVariablesAleatorias" class="quarto-xref">Figura&nbsp;<span>11.17</span></a> las estaturas (<span class="math inline">\(X\)</span>) se han generado aleatoriamente de una distribución N(170; 8) y a cada estatura se le ha asignado un peso (<span class="math inline">\(Y\)</span>) mediante la expresión <span class="math inline">\(Y = X -100 +e\)</span>, donde <span class="math inline">\(e\)</span> es un valor también generado aleatoriamente de una distribución N(0;,5). Tanto los valores de la estatura (en cm) como los obtenidos para los pesos (en kg) son valores razonables para una población joven. Hemos repetido la simulación 6 veces y, como es natural, cada vez hemos obtenido unos datos distintos y, por tanto, también una recta ajustada distinta.</p>
<div id="fig-regresionVariablesAleatorias" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regresionVariablesAleatorias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1117_regresionVariablesAleatorias.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regresionVariablesAleatorias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.17: Rectas ajustadas a partir de muestras de n=20 datos de una misma población. La línea negra representa el modelo teórico.
</figcaption>
</figure>
</div>
<p>En la <a href="#fig-regreVAsuperpuestas" class="quarto-xref">Figura&nbsp;<span>11.18</span></a> (izquierda) se han superpuesto los 6 diagramas anteriores pudiéndose observar el haz de rectas que se obtiene. A la derecha tenemos la misma situación superponiendo 50 simulaciones (cada una con 20 datos) añadiendo, de color verde, la recta que representa el modelo teórico, es decir, la población.</p>
<div id="fig-regreVAsuperpuestas" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regreVAsuperpuestas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1118_regreVAsuperpuestas.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regreVAsuperpuestas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.18: Superposición de 6 (izquierda) y 50 (derecha) simulaciones de conjuntos de 20 datos del modelo representado con una línea verde.
</figcaption>
</figure>
</div>
</section>
<section id="distribución-de-los-coeficientes" class="level2" data-number="11.9">
<h2 data-number="11.9" class="anchored" data-anchor-id="distribución-de-los-coeficientes"><span class="header-section-number">11.9</span> Distribución de los coeficientes</h2>
<p>La buena noticia distribución} es que si los datos cumplen ciertas condiciones –que en general se cumplirán– los valores de los coeficientes pertenecen a distribuciones Normales con parámetros conocidos<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>. Siguiendo con el ejemplo anterior hemos repetido 10.000 veces la simulación obteniendo otras tantas rectas ajustadas. La <a href="#fig-distribucionCoeficientes" class="quarto-xref">Figura&nbsp;<span>11.19</span></a> muestra los histogramas de los 10.000 valores obtenidos para <span class="math inline">\(b_0\)</span> y <span class="math inline">\(b_1\)</span>.</p>
<div id="fig-distribucionCoeficientes" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distribucionCoeficientes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1119_distribucionCoeficientes.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distribucionCoeficientes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.19: Distribución de los coeficientes.
</figcaption>
</figure>
</div>
<p>Observe que las medias de las distribuciones coinciden con el verdadero valor del parámetro estimado. Las desviaciones típicas dependen de:</p>
<ul>
<li><p><strong>Número de datos (</strong><span class="math inline">\(n\)</span>): Cuantos más datos, mayor información y menos incertidumbre; por tanto, menos desviación típica en la distribución de los coeficientes.</p></li>
<li><p><strong>Desviación típica de la respuesta (</strong><span class="math inline">\(\sigma\)</span>)}: A mayor variabilidad de la respuesta mayor incertidumbre y mayor variabilidad en la distribución de los coeficientes.</p></li>
<li><p><strong>El rango de variación de</strong> <span class="math inline">\(x\)</span>: Si los valores de de la variable regresora están muy próximos a su media habrá mayor variabilidad en la distribución de los coeficientes. Quizá este aspecto no es tan intuitivo como los anteriores, pero se entiende muy bien a la vista de un gráfico como el de la <a href="#fig-regreRangoX" class="quarto-xref">Figura&nbsp;<span>11.20</span></a>. En la izquierda tenemos el mismo gráfico que en la <a href="#fig-regreVAsuperpuestas" class="quarto-xref">Figura&nbsp;<span>11.18</span></a> con valores de <span class="math inline">\(X\)</span> generados de una distribución N(170; 8) mientras que en el de la derecha se ha construido de la misma forma pero los valores de <span class="math inline">\(X\)</span> se han generado de una N(170; 3). Al tener menos variabilidad en los valores de <span class="math inline">\(X\)</span> tenemos mayor variabilidad en los coeficientes.</p></li>
</ul>
<div id="fig-regreRangoX" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regreRangoX-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1120_regreRangoX.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regreRangoX-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.20: La variabilidad de las rectas ajustadas depende del rango de X.
</figcaption>
</figure>
</div>
<p>Conocer la distribución de los coeficientes (Apéndice 10.C) hace posible calcular intervalos de confianza o realizar contrastes de hipótesis sobre sus valores.</p>
<section id="condiciones-que-deben-reunir-los-datos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="condiciones-que-deben-reunir-los-datos">Condiciones que deben reunir los datos</h3>
<p>Para que los coeficientes tengan las distribuciones que se suponen, los datos utilizados para ajustar el modelo deben cumplir las siguientes condiciones:</p>
<ul>
<li><p><strong>Distribución de</strong> <span class="math inline">\(Y\)</span>: Dado un valor de <span class="math inline">\(X\)</span>, los valores de <span class="math inline">\(Y\)</span> deben seguir una distribución Normal. Si <span class="math inline">\(X\)</span> es la estatura e <span class="math inline">\(Y\)</span> es el peso, no hace falta suponer que el peso –globalmente– sigue una distribución Normal, pero sí que los pesos para las personas de una determinada estatura siguen esa distribución.</p></li>
<li><p><strong>Variabilidad de</strong> <span class="math inline">\(Y\)</span>: La variabilidad de <span class="math inline">\(Y\)</span> no depende del valor de <span class="math inline">\(X\)</span>. En nuestro ejemplo sería suponer que la variabilidad en el peso de las personas que miden 1,60 es la misma que en las personas que miden 1,80 m. Es posible que esto no sea exactamente así porque es habitual que cuando aumenta el nivel de la respuesta aumente también su variabilidad. Si esto ocurre lo veremos en el diagrama bivariante: la nube de puntos se irá ensanchando a medida que aumenta el valor de <span class="math inline">\(X\)</span>. En este caso quizá convenga transformar los datos, aunque ya estaríamos ante una situación más complicada que las que pretendemos tratar aquí.</p></li>
<li><p><strong>Valores de</strong> <span class="math inline">\(X\)</span>: No hay ninguna exigencia especial sobre estos valores. Solo es necesario que la variable sea cuantitativa. Es decir, el día de la semana, codificado como: lunes = 1, martes = 2, … no puede ser una variable regresora porque el modelo entendería que el domingo es igual a 7 veces el lunes. Aun así, también hay formas de incluir este tipo de variables. Lo veremos en el próximo capítulo en el caso de que solo puedan tomar dos valores posibles.</p></li>
<li><p><strong>Independencia de los residuos</strong>: La desviación respecto al valor previsto (valor sobre la recta) en un punto no da ninguna pista sobre la desviación en el punto siguiente. Esto no ocurre con las variables que evolucionan en el tiempo, como la temperatura o la cotización de acciones en la bolsa, en que el valor de un día está influenciado por el valor del día anterior.</p></li>
</ul>
<p>Cuando se ajustan modelos de regresión simple, la observación del diagrama bivariante de <span class="math inline">\(Y\)</span> frente a <span class="math inline">\(X\)</span> ya permite valorar si es razonable suponer que se cumplen los supuestos requeridos. Si nada hace suponer lo contrario, supondremos que se cumplen. En realidad nunca se cumplirán “exactamente” pero si el comportamiento de los datos no se aleja mucho de los supuestos realizados, los intervalos de confianza y las pruebas de significación en que estamos interesados seguirán siendo válidos a efectos prácticos.</p>
</section>
</section>
<section id="significación-de-los-coeficientes" class="level2" data-number="11.10">
<h2 data-number="11.10" class="anchored" data-anchor-id="significación-de-los-coeficientes"><span class="header-section-number">11.10</span> Significación de los coeficientes</h2>
<section id="visión-intuitiva" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="visión-intuitiva">Visión intuitiva</h3>
<p>Usaremos los datos que ya vimos (apartado #sec-calidadAjuste) sobre el volumen de madera que se obtiene de un árbol en función del diámetro de su tronco y sobre la edad al morir en función de la longitud de una línea de la mano. La <a href="#fig-ArbolManoModelos" class="quarto-xref">Figura&nbsp;<span>11.21</span></a> contiene las rectas ajustadas y algunos valores característicos de cada situación. Aunque a la vista de los gráficos ya se ve claro que en el caso del volumen de madera la pendiente es significativa y en el de la línea de la mano no lo es, vamos a comprobar por simulación que estamos en lo cierto.</p>
<div id="fig-ArbolManoModelos" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ArbolManoModelos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1121_ArbolManoModelos.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ArbolManoModelos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.21: Modelos ajustados y valores característicos de cada conjunto de datos.
</figcaption>
</figure>
</div>
<p>Si no hay ninguna relación entre la variable regresora (<span class="math inline">\(X\)</span>) y la respuesta (<span class="math inline">\(Y\)</span>), la pendiente de la recta estará en torno a cero (será igual a cero en la población, que en estos casos son modelos teóricos). Para ver lo que significa “en torno a cero” podemos simular nubes de puntos manteniendo las características de <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> y suponiendo que no existe ninguna relación entre ellas.</p>
<p>En el caso del volumen de madera empezamos generando 31 números aleatorios (una cantidad igual a nuestro tamaño de muestra) que asignamos al diámetro de los troncos. Para que estos datos se puedan considerar del mismo tipo de los que tenemos en la muestra es razonable generarlos de una distribución Normal con la media <span class="math inline">\((\bar{x} = 13.25)\)</span> y la desviación típica <span class="math inline">\((s_X = 3.2)\)</span> de los valores que aparecen en la muestra, es decir: <span class="math inline">\(X \sim N(13.25; 3.2)\)</span>. A continuación, a cada valor de <span class="math inline">\(X\)</span> le hacemos corresponder un valor de <span class="math inline">\(Y\)</span> igual a la media de los valores disponibles <span class="math inline">\((\bar{y} = 30.2)\)</span> añadiendo un número aleatorio de una distribución Normal con media cero (ni sube ni baja de forma sistemática el valor de la respuesta) y una desviación típica igual a la que presentan los residuos del modelo ajustado <span class="math inline">\((s_R = 4.25)\)</span>. Por tanto, tendremos: <span class="math inline">\(Y = 30.2 + N(0; 4.25)\)</span>.</p>
<p>Para el modelo de la edad al morir hacemos exactamente lo mismo con los valores que corresponden: <span class="math inline">\(n=50\)</span>; <span class="math inline">\(\bar{x}=9.2\)</span>; <span class="math inline">\(s_X = 1.27\)</span>; <span class="math inline">\(s_R=14.15\)</span>; <span class="math inline">\(\bar{y}=66.7\)</span>.</p>
<p>Para cada conjunto de puntos simulados se ha calculado la recta ajustada. En los dos casos la simulación se ha repetido 50 veces y en los diagramas de la <a href="#fig-pruebasSignaficacion" class="quarto-xref">Figura&nbsp;<span>11.22</span></a> se han ido acumulando tanto los puntos como las rectas ajustadas. También se ha añadido, de color verde, la línea correspondiente a los datos de la muestra. Está muy claro que en el caso del volumen de madera, la recta ajustada con los datos de la muestra no se puede confundir con los generados aleatoriamente suponiendo que no hay relación entre ambas variables. Sin embargo, en el caso de la edad al morir, la recta que corresponde a los datos disponibles se confunde con las que hemos simulado, por tanto, el valor de la pendiente queda explicado por la variabilidad intrínseca de los datos, diremos que esa diferencia no es estadísticamente significativa.</p>
<div id="fig-pruebasSignaficacion" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pruebasSignaficacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1122_pruebasSignaficacion.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pruebasSignaficacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.22: Rectas ajustadas considerando que no hay relación entre las variables y recta obtenida con los datos de la muestra (color verde).
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Pruebas de significación y contraste de hipótesis
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una prueba de significación es un caso particular de contraste de hipótesis donde se contrasta que el valor del parámetro es igual a cero. Significación equivale a “significativamente distinto de cero”, es decir, que la variabilidad aleatoria no justifica la diferencia respecto a cero.</p>
</div>
</div>
</section>
<section id="pruebas-de-significación-formales" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="pruebas-de-significación-formales">Pruebas de significación formales</h3>
<p>Aunque pueden no ser necesarias en casos tan claros como los que acabamos de ver, conocer la distribución de los coeficientes nos permite realizar pruebas de significación de manera más directa, sin necesidad de realizar simulaciones.</p>
<p>Lo habitual es contrastar que el coeficiente, ya sea <span class="math inline">\(\beta_0\)</span> o <span class="math inline">\(\beta_1\)</span>, es igual a cero frente a la alternativa de que es distinto de cero.</p>
<section id="sobre-el-valor-de-la-ordenada-en-el-origen-beta_0" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="sobre-el-valor-de-la-ordenada-en-el-origen-beta_0">Sobre el valor de la ordenada en el origen, <span class="math inline">\(\beta_0\)</span></h4>
<p>Tiene interés cuando hay razones para suponer que la recta pasa por el origen de coordenadas. Permite verificar que los resultados obtenidos no están en contradicción con ese supuesto.</p>
<p>Si los datos cumplen las condiciones que antes hemos comentado tendremos: <span class="math display">\[b_0 \sim N \left(\beta_0; \; \sigma_{b_0} \right)\]</span> luego si <span class="math inline">\(\beta_0 = 0\)</span>: <span class="math display">\[\frac{b_0-0}{\sigma_{b_0}} \sim N (0; 1)\]</span> Pero como no conocemos <span class="math inline">\(\sigma_{b_0}\)</span> y usamos su estimación <span class="math inline">\(s_{b_0}\)</span>, el estadístico de prueba es: <span class="math display">\[ T = \frac{b_0}{s_{b_0}}\]</span> y su distribución de referencia es una <span class="math inline">\(t\)</span>-Student con <span class="math inline">\(n-2\)</span> grados de libertad, siendo <span class="math inline">\(n\)</span> el número de datos disponibles. Los 2 grados de libertad que se pierden tienen que ver con las restricciones que presentan los residuos cuando el modelo se ha ajustado por el método de los mínimos cuadrados <span class="math inline">\(\left ( \sum e_i = 0 \; \text{y} \; \sum e_ix_i = 0 \right )\)</span>.</p>
<p>Como regla general, si <span class="math inline">\(|T| &gt; 2\)</span>, es decir, el valor obtenido está a más de dos desviaciones típicas de cero, se rechaza la hipótesis nula. Por supuesto, también se puede calcular el <span class="math inline">\(p\)</span>-valor exacto y tomar la decisión de acuerdo con el nivel de significación establecido.</p>
<p>Si se decide eliminar <span class="math inline">\(b_0\)</span> del modelo es necesario recalcular el valor de <span class="math inline">\(b_1\)</span> con una fórmula específica para esta situación puesto que ya no estamos aplicando el criterio de los mínimos cuadrados. En el apéndice 10.B se comentan algunas peculiaridades de este caso particular.</p>
</section>
<section id="sobre-el-valor-de-la-pendiente-de-la-recta-beta_1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="sobre-el-valor-de-la-pendiente-de-la-recta-beta_1">Sobre el valor de la pendiente de la recta, <span class="math inline">\(\beta_1\)</span></h4>
<p>Este contraste siempre tiene interés. Se trata de verificar que la pendiente de la recta es significativamente distinta de cero. Si no lo es, una recta horizontal es compatible con los datos por lo que no se puede afirmar que haya relación entre la variable regresora y la respuesta.</p>
<p>El procedimiento es idéntico que para <span class="math inline">\(\beta_0\)</span>. El estadístico de prueba ahora es: <span class="math display">\[T = \frac{b_1}{s_{b_1}} \sim t-\text{Student} \;\text{con} \; n-2 \; \text{grados de libertad}\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ligando las pruebas de significación para <span class="math inline">\(r\)</span> y para <span class="math inline">\(b_1\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Que el coeficiente de correlación entre dos variables sea significativo implica que la pendiente de la recta ajustada también lo será, y viceversa. Además, el p-valor también será el mismo, sería una incongruencia que fueran distintos.</p>
</div>
</div>
</section>
<section id="resultados-presentados-por-los-paquetes-de-software-estadístico" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="resultados-presentados-por-los-paquetes-de-software-estadístico">Resultados presentados por los paquetes de software estadístico</h4>
<p>En general, además de presentar los coeficientes del modelo también presentan los <span class="math inline">\(p\)</span>-valores asociados a los contrastes que hemos comentado. La <a href="#fig-salidaSoftwareRegresion" class="quarto-xref">Figura&nbsp;<span>11.23</span></a> muestra parte de la salida que proporciona Minitab en los dos casos que estamos considerando. Tal como hemos visto, el <strong>T-value</strong> que aparece en el listado es simplemente el cociente entre el coeficiente (<strong>Coef</strong>) y su desviación típica (<strong>SE Coef</strong>) y el p-valor (<strong>P-Value</strong>) es el área de cola –multiplicada por 2, ya que es una prueba bilateral– que deja ese T-Value en una distribución t-Student con <span class="math inline">\(n-2\)</span> grados de libertad, siendo <span class="math inline">\(n\)</span> el número de puntos usados en cada caso.</p>
<div id="fig-salidaSoftwareRegresion" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-salidaSoftwareRegresion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1123_salidaSoftwareRegresion.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-salidaSoftwareRegresion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.23: Salida del paquete de software estadístico Minitab al ajustar modelos de regresión en los dos ejemplos que hemos visto.
</figcaption>
</figure>
</div>
<p>También puede interesar contrastar otros valores para la pendiente de la recta. Para verificar que un aparato mide correctamente la concentración de monóxido de carbono (CO) en el aire, se mide la concentración de 11 muestras con valores conocidos. Los resultados obtenidos<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> son los que se indican en la <a href="#tbl-concentracionCO">Tabla 11.6</a>.</p>
<div id="tbl-concentracionCO" class="tabla-wrapper_T1106 anchored">

<table class="tabla-1106 caption-top table">
<caption>Tabla 11.6: Concentración de CO, Valores reales y valores medidos (ppm).</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<tbody>
<tr class="odd">
<td>Valor real:</td>
<td>0</td>
<td>10</td>
<td>20</td>
<td>30</td>
<td>40</td>
<td>50</td>
<td>60</td>
<td>70</td>
<td>80</td>
<td>90</td>
<td>100</td>
</tr>
<tr class="even">
<td>Valor medido:</td>
<td>1</td>
<td>11</td>
<td>21</td>
<td>28</td>
<td>37</td>
<td>48</td>
<td>56</td>
<td>68</td>
<td>75</td>
<td>86</td>
<td>96</td>
</tr>
</tbody>
</table>

</div>
<p>La <a href="#fig-pendiente1" class="quarto-xref">Figura&nbsp;<span>11.24</span></a> (izquierda) muestra el diagrama bivariante de los valores medidos frente a los reales con su recta ajustada. El aparato estará bien calibrado si –en promedio– el valor de la concentración medida es igual a la concentración real. Es decir, si los datos se ajustan al modelo: <span class="math inline">\(y = x\)</span>.</p>
<div id="fig-pendiente1" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pendiente1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1124_pendiente1.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pendiente1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.24: La recta ajustada no se confunde con las de pendiente igual a 1.
</figcaption>
</figure>
</div>
<p>Usando Minitab tenemos los coeficientes del modelo y la prueba de significación para sus valores (<a href="#fig-salidaConcentracion" class="quarto-xref">Figura&nbsp;<span>11.25</span></a>, izquierda).</p>
<div id="fig-salidaConcentracion" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-salidaConcentracion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1125_salidaConcentracion.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-salidaConcentracion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.25: Ajuste habitual (mínimos cuadrados) y forzando a que la recta pase por el origen.
</figcaption>
</figure>
</div>
<p>Vemos que la ordenada en el origen (Minitab le llama “Constant” pero ya dijimos que esta no nos parece una denominación adecuada) no es significativamente distinta de cero por lo que hemos recalculado el modelo sin ese término. En el nuevo modelo el valor de <span class="math inline">\(b_1\)</span> (coeficiente de la concentración real) es claramente significativo (significativamente distinto de cero) pero no es eso lo que nos preocupa. Lo que queremos saber es si es significativamente distinto de 1. Minitab no lo hace automáticamente pero es muy fácil hacerlo a mano: <span class="math display">\[T =  \frac{b_1-1}{s_{b_1}} = \frac{0.95351-1}{0.00598} = -7.77\]</span> Si efectivamente <span class="math inline">\(\beta_1 = 1\)</span> el valor de <span class="math inline">\(T\)</span> pertenece a una distribución <span class="math inline">\(t\)</span>-Student, pero si lo fuera su valor estaría comprendido aproximadamente entre -2 y 2, y el valor que hemos obtenido está muy lejos de este intervalo. Por tanto, la hipótesis nula de que <span class="math inline">\(\beta_1=1\)</span> queda descartada. El aparato no está bien calibrado.</p>
<p>En la <a href="#fig-pendiente1" class="quarto-xref">Figura&nbsp;<span>11.24</span></a> (derecha) se han representado las rectas ajustadas (color azul) de valores de la concentración medida (<span class="math inline">\(y\)</span>) en función de la concentración real (<span class="math inline">\(x\)</span>) generados con el modelo <span class="math inline">\(y = x + e\)</span> siendo <span class="math inline">\(e\)</span> valores de una distribución Normal con media cero y una desviación típica igual a la que presentan los residuos del modelo obtenido. La recta ajustada con los datos reales aparece de color verde (es la misma que tenemos en el diagrama de la izquierda), se ve que no se confunde con las generadas aleatoriamente suponiendo que el aparato está bien calibrado, a partir de una concentración de 50 tiende a dar valores menores que los reales.</p>
</section>
</section>
</section>
<section id="intervalos-de-confianza-para-la-respuesta" class="level2" data-number="11.11">
<h2 data-number="11.11" class="anchored" data-anchor-id="intervalos-de-confianza-para-la-respuesta"><span class="header-section-number">11.11</span> Intervalos de confianza para la respuesta</h2>
<p>Volvamos a los datos del diámetro de los troncos y el volumen de madera que se extrajo de cada uno de ellos.</p>
<p>Con la información disponible, la mejor predicción que podemos hacer del volumen de madera (<span class="math inline">\(Y\)</span>) que se obtendrá de un tronco de circunferencia <span class="math inline">\(X\)</span> es el valor que nos da la recta ajustada para ese valor de <span class="math inline">\(X\)</span>. Como el modelo ajustado es <span class="math inline">\(Y = -36.94 + 5.066  X\)</span> nuestra apuesta para el volumen de madera que se puede obtener de un tronco con una circunferencia de 20 in será: <span class="math inline">\(Y = -36.94 + 5.066 \cdot 20 = 64.4\)</span>, así de fácil.</p>
<p>Pero ya sabemos que es mejor dar un intervalo de confianza que una predicción puntual. De acuerdo con los supuestos realizados sobre el comportamiento de los datos, para cada valor de <span class="math inline">\(X\)</span>, los valores de <span class="math inline">\(Y\)</span> siguen una distribución Normal centrada en la estimación puntual y con una desviación típica cuyo estimador es la desviación típica de los residuos. Sabemos que en una distribución Normal el 95 % de las observaciones están en el intervalo <span class="math inline">\(\mu \pm 1.96\sigma\)</span>. Si, como es habitual, ajustamos el modelo con un número de puntos no muy pequeño (en nuestro caso <span class="math inline">\(n=31\)</span>) podemos identificar <span class="math inline">\(\sigma\)</span> con su estimador <span class="math inline">\(s_R\)</span> y redondeando el 1,96 a 2 podemos establecer con un cálculo rápido que el intervalo de confianza del 95 % para la predicción es: <span class="math inline">\(\hat{y} \pm 2s_R\)</span>. Con nuestros números: <span class="math inline">\(64,4 \pm 2 \cdot 4,25 = (54,9;  73,9)\)</span></p>
<p>Pero, naturalmente, lo más rápido y lo más cómodo es pedirle la predicción al paquete de software que ha realizado el ajuste. También se le puede pedir que represente las bandas de confianza para el modelo ajustado, tal como están representadas en la <a href="#fig-bandasConfianza" class="quarto-xref">Figura&nbsp;<span>11.26</span></a>.</p>
<div id="fig-bandasConfianza" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bandasConfianza-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1126_bandasConfianza.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bandasConfianza-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.26: Recta ajustada y bandas de confianza del 95 %
</figcaption>
</figure>
</div>
</section>
<section id="malas-prácticas-con-la-regresión-simple" class="level2" data-number="11.12">
<h2 data-number="11.12" class="anchored" data-anchor-id="malas-prácticas-con-la-regresión-simple"><span class="header-section-number">11.12</span> Malas prácticas con la regresión simple</h2>
<section id="extrapolar-más-allá-de-donde-se-tienen-datos" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="extrapolar-más-allá-de-donde-se-tienen-datos">Extrapolar más allá de donde se tienen datos</h4>
<p>Un buen ajuste dentro del rango en que se tienen datos no garantiza predicciones fiables fuera de él. Supongamos que para un vehículo se informa del siguiente consumo en función de la velocidad a que circula:</p>
<div class="tabla-wrapper_1100a">

<table class="tabla-1100a caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td>Velocidad (km/h):</td>
<td>60</td>
<td>70</td>
<td>80</td>
<td>90</td>
<td>100</td>
</tr>
<tr class="even">
<td>Consumo (litros/100 km):</td>
<td>4,0</td>
<td>4,8</td>
<td>6,1</td>
<td>7,0</td>
<td>8,2</td>
</tr>
</tbody>
</table>

</div>
<p>Una estimación razonable para el consumo a 75 km/h es de 5,5 litros/100 km pero no podemos decir que a 25 km/h el consumo es prácticamente nulo y que a 20 km/h es negativo, aunque esos son los valores que se deducen del modelo ajustado.</p>
</section>
<section id="ignorar-la-autocorrelación-de-las-observaciones" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="ignorar-la-autocorrelación-de-las-observaciones">Ignorar la autocorrelación de las observaciones</h4>
<p>Cuando las observaciones se presentan en orden cronológico y el valor de una depende del de la anterior, como la evolución de la temperatura mínima diaria, los modelos de regresión no sirven para hacer previsiones. En el gráfico de la <a href="#fig-extrapolarSerieTiempo" class="quarto-xref">Figura&nbsp;<span>11.27</span></a> (derecha) una previsión a ojo mejora la que proporciona el modelo ajustado (la línea a trazos corresponde a un modelo cuadrático). Para estos casos tenemos otras herramientas que llamamos de análisis de series de tiempo, que tienen en cuenta la posible estacionalidad o periodicidad de los datos, además de su tendencia.</p>
<div id="fig-extrapolarSerieTiempo" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-extrapolarSerieTiempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1127_extrapolarSerieTiempo.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-extrapolarSerieTiempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.27: No se debe extrapolar fuera del rango de variación de los datos ni usar modelos de regresión para hacer previsiones de datos obtenidos en orden cronológico.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>La estadística en la bolsa
</div>
</div>
<div class="callout-body-container callout-body">
<p>La estadística tiene muchos campos de aplicación pero no sirve para hacer predicciones y ganar dinero en la bolsa. Si le interesa este tema un buen libro es el de John Allen Paulos: “Un matemático invierte en bolsa”.</p>
</div>
</div>
</section>
</section>
<section id="apéndice-11.a-otra-fórmula-para-b_1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-11.a-otra-fórmula-para-b_1">APÉNDICE 11.A: Otra fórmula para <span class="math inline">\(b_1\)</span></h2>
<p>Algunos libros texto dan una fórmula distinta de la que hemos deducido nosotros pero es muy fácil pasar de una a otra. Partimos de la expresión que hemos deducido:</p>
<p><span class="math display">\[b_1 = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2}\]</span> Podemos poner el numerador de la forma: <span class="math display">\[\begin{equation*}
    \begin{split}
        \sum (x_i - \bar{x})(y_i - \bar{y}) &amp;= \sum x_i y_i - \bar{x} \sum y_i - \bar{y} \sum x_i + n\bar{x}\bar{y} =\\
        &amp;= \sum x_i y_i -2n\bar{x}\bar{y} + n\bar{x}\bar{y} =\\
        &amp;= \sum x_i y_i -n\bar{x}\bar{y} = \\
        &amp;= \sum x_i y_i - \bar{y} \sum x_i
    \end{split}
\end{equation*}\]</span></p>
<p>y el denominador: <span class="math display">\[\begin{equation*}
    \begin{split}
        \sum (x_i - \bar{x})^2 &amp;= \sum x_i^2 - 2 \bar{x} \sum x_i + n \bar{x}^2 =\\
        &amp;= \sum x_i^2 -n\bar{x}^2 =\\
        &amp;= \sum x_i^2 - \bar{x} \sum x_i
    \end{split}
\end{equation*}\]</span></p>
<p>Por tanto,</p>
<p><span class="math display">\[b_1 = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2}  = \frac{\sum x_i y_i - \bar{y} \sum x_i}{\sum x_i^2 - \bar{x} \sum x_i} \]</span> Esta última fórmula facilita los cálculos, pero en los tiempos que corren, donde los cálculos los hacen los ordenadores, ésta es una ventaja que ha perdido interés.</p>
</section>
<section id="apéndice-11.b-el-caso-de-la-recta-forzada-a-pasar-por-el-origen" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-11.b-el-caso-de-la-recta-forzada-a-pasar-por-el-origen">APÉNDICE 11.B: El caso de la recta forzada a pasar por el origen</h2>
<p>Cuando el valor de <span class="math inline">\(b_0\)</span> no es significativo se puede plantear la posibilidad de eliminarlo y recalcular el valor de <span class="math inline">\(b_1\)</span>, pero deben darse también las siguientes circunstancias:</p>
<ul>
<li><p>Se sabe –o es razonable considerar– que cuando <span class="math inline">\(X=0\)</span> también tendremos <span class="math inline">\(Y=0\)</span>.</p></li>
<li><p>El rango de variación de los valores disponibles de <span class="math inline">\(X\)</span> incluye <span class="math inline">\(X=0\)</span> o queda cerca de ese valor. Si estudiamos la relación entre peso y estatura de las personas adultas es cierto que a una estatura igual a cero le corresponde también un peso nulo, pero los valores de estatura que tenemos siempre están lejos de cero por lo que no hay que forzar que la recta pase por el origen, además de que en este caso seguro que el valor de <span class="math inline">\(b_0\)</span> sí es significativo.</p></li>
</ul>
<p>El modelo ajustado al forzar <span class="math inline">\(b_0=0\)</span> tiene algunas peculiaridades:</p>
<ul>
<li>El valor de <span class="math inline">\(b_1\)</span> no se calcula con la fórmula habitual. Si <span class="math inline">\(b_0 = 0\)</span> lo que hay que minimizar es <span class="math inline">\(S = \sum \left( y_i - b_1 x_i \right)^2\)</span> y aplicando el procedimiento habitual:</li>
</ul>
<p><span class="math display">\[\frac{\mathrm{d}S}{\mathrm{d}b_1}  = \frac{\mathrm{d}(\sum y_i^2-\sum 2y_ib_1x_i+ \sum b_1^2x_i^2)} {\mathrm{d} b_1} = -2 \sum x_iy_i +2 \sum x_i^2b_1\]</span> Está claro que la segunda derivada es positiva (es una suma de cuadrados) por lo que tendremos un mínimo. Igualando a cero y despejando el valor de <span class="math inline">\(b_1\)</span> se obtiene:</p>
<p><span class="math display">\[ b_1 = \frac{\sum x_iy_i}{\sum x_i^2}\]</span> - El modelo obtenido no es el que minimiza la suma de los cuadrados de los residuos. Seguro que esa suma será mayor que si se ajusta dejando libertad al valor de los dos coeficientes.</p>
<ul>
<li>El valor de <span class="math inline">\(R^2\)</span> no es una buena medida de calidad del ajuste. <span class="math inline">\(R^2\)</span> mide la proporción en que se reduce la suma de los cuadrados de los residuos en la recta ajustada respecto a la que no usa la información que aporta <span class="math inline">\(X\)</span>. Esta última es una recta horizontal, pero si la hacemos pasar por <span class="math inline">\(\bar{y}\)</span> –lo habitual– no está pasando por el origen por lo que no es una buena referencia para comparar, y una horizontal pasando por el origen da una suma de cuadrados exagerada. Lo mejor es no dar ese valor en este caso.</li>
</ul>
</section>
<section id="apéndice-11.c-datos-que-no-cumplen-las-condiciones-requeridas" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-11.c-datos-que-no-cumplen-las-condiciones-requeridas">APÉNDICE 11.C: Datos que no cumplen las condiciones requeridas</h2>
<p>Se puede representar un triángulo en unos ejes de coordenadas generando 6 números aleatorios y agrupándolos en 3 parejas cada una de las cuales define un vértice. Hemos repetido esta operación 500 veces generando los números aleatorios de una distribución U(0; 150). De los 500 triángulos resultantes, hemos calculado su área y su perímetro. En la <a href="#fig-triangulos" class="quarto-xref">Figura&nbsp;<span>11.28</span></a> (izquierda) tenemos el diagrama bivariante de los resultados obtenidos.</p>
<div id="fig-triangulos" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-triangulos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1128_triangulos.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-triangulos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.28: Datos que no cumplen las condiciones exigidas para realizar estimaciones de la forma habitual.
</figcaption>
</figure>
</div>
<p>Está claro que esa nube de puntos no responde a lo que esperamos cuando ajustamos un modelo de regresión. Nosotros consideramos que para cada valor de <span class="math inline">\(X\)</span> los valores de <span class="math inline">\(Y\)</span> siguen una distribución Normal, cada una con una media específica para cada valor de <span class="math inline">\(X\)</span>, pero siempre con la misma varianza. El valor de esa varianza interviene en la distribución de los coeficientes y, por tanto, afecta a los resultados de las pruebas de significación y también a los intervalos de confianza de las predicciones.</p>
<p>En nuestro caso esa varianza claramente no es constante. Para valores bajos del perímetro hay muy poca variabilidad en el área (siempre pequeña) pero perímetros grandes pueden corresponder tanto a triángulos con área grande como con área pequeña cuando dos de sus ángulos son muy pequeños. En este tipo de situación no vale la teoría que hemos desarrollado.</p>
<p>A la vista de la representación de los datos ya es evidente que la varianza no es constante, pero también el análisis de los residuos pone de manifiesto que algo falla: el gráfico de residuos frente a valores previstos (a la derecha) tiene forma de embudo, síntoma de una patología que llamamos <em>heterocedasticidad</em> y que significa que la variabilidad de <span class="math inline">\(Y\)</span> aumenta al aumentar el valor de <span class="math inline">\(X\)</span>.</p>
<p>Una solución puede ser transformar los datos. El precio a pagar es que el modelo puede parecer caprichoso y poco interpretable. Con estos datos, si realizamos la transformación <span class="math inline">\(Y = \sqrt[3]{\text{Área}}\)</span>, no los deja en perfecto estado pero los arregla bastante (<a href="#fig-triangulosTransfo" class="quarto-xref">Figura&nbsp;<span>11.29</span></a>).</p>
<div id="fig-triangulosTransfo" class="fig-normal6 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-triangulosTransfo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras_11/f1129_triangulosTransfo.png" class="fig-normal6 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-triangulosTransfo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11.29: Transformando los valores de alguna de las variables –o de ambas– se puede mejorar su comportamiento.
</figcaption>
</figure>
</div>
<div style="text-align: center; font-size: 1.1em;">
<p>________________________ <span style="margin: 0 0.4em;">◇</span> ________________________</p>
</div>
<p><br></p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Son los datos que ya vimos en el capítulo anterior, apartado 10.1.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Son los datos que ya vimos en el capítulo anterior, apartado 10.1.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Puede ver una demostración <a href="https://statproofbook.github.io/P/slr-rsq">aquí</a>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Interesados en este tipo de transformaciones para linealizar la dependencia pueden consultar el libro de Daniel Peña (2002): “Regresión y diseño de experimentos”, Alianza Editorial, pág. 314 o el de Montgomery, D. C. y Peck, E. A. (1992): “Introduction to Linear Regression Analysis” Ed. Wiley, pág. 90.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Datos en: Montgomery D. C y Runger, G. C. (2011): “Applied Statistics and Probability for Engineers”. Ed. Wiley, 5a ed., pág. 439.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Fuente: Página personal del prof. Weisberg en <span style="font-family: monospace;"><a href="https://cla.umn.edu/statistics" class="uri">https://cla.umn.edu/statistics</a></span> &gt; Other Resources &gt; data files &gt; brains.csv. Otros datos y más información <a href="https://resources.wolframcloud.com/ExampleRepository/resources/Animal-Brain-vs-Body-Mass">aquí</a>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>En realidad, lo conocido es la expresión del parámetro. Su valor se estima a partir de los datos de la muestra.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Fuente: Navidi W. (2010): ``Statistics for Engineers and Scientists’’. Ed McGraw Hill, 3a ed., pág. 585.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./10_relacionLineal.html" class="pagination-link" aria-label="Medidas de relación lineal">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Medidas de relación lineal</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./12_regreMultiple.html" class="pagination-link" aria-label="Regresión Múltiple">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Regresión Múltiple</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>