<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Representaciones gráficas – &lt;span style="font-size: 1.5em;"&gt;Estadística&lt;/span&gt;&lt;br&gt;
&lt;span style="font-size: 1em;"&gt;Entender - Aplicar - Enseñar&lt;/span&gt;</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./30_VARIABILIDAD.html" rel="next">
<link href="./21_sintesisNumerica.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2cf3c65c5b6db5ec86e992953759863e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./20_DESCRIPTIVA.html">ESTADÍSTICA DESCRIPTIVA</a></li><li class="breadcrumb-item"><a href="./22_Graficos.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Representaciones gráficas</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"><span style="font-size: 1.5em;">Estadística</span><br> <span style="font-size: 1em;">Entender - Aplicar - Enseñar</span></a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PRESENTACIÓN</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01_Prologo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prólogo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_INTRODUCCION.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./20_DESCRIPTIVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ESTADÍSTICA DESCRIPTIVA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21_sintesisNumerica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Síntesis numérica de datos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22_Graficos.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Representaciones gráficas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./30_VARIABILIDAD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DESCRIBIR LO ALEATORIO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31_variablesAleatorias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variables aleatorias</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32_distribucionesProbabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Distribuciones de probabilidad</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./40_MUESTRA_POBLACION.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DE LA MUESTRA A LA POBLACIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41_muestreo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Muestreo. Encuestas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42_estimacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estimación de características de la población</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./50_SIGNIFICATIVO.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ESTADÍSTICAMENTE SIGNIFICATIVO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./51_contrasteHipotesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Contraste de hipótesis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./52_algunosTest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Algunos test clásicos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./60_CORRELACION.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CORRELACIÓN Y REGRESIÓN</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./61_relacionLineal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Medidas de relación lineal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./62_regreSimple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regresión simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./63_regreMultiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Regresión Múltiple</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">EPÍLOGO</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Origen de los datos</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#forma-de-la-distribución-valor-central-y-dispersión" id="toc-forma-de-la-distribución-valor-central-y-dispersión" class="nav-link active" data-scroll-target="#forma-de-la-distribución-valor-central-y-dispersión"><span class="header-section-number">3.1</span> Forma de la distribución, valor central y dispersión</a>
  <ul class="collapse">
  <li><a href="#histograma" id="toc-histograma" class="nav-link" data-scroll-target="#histograma">Histograma</a></li>
  <li><a href="#diagrama-de-puntos" id="toc-diagrama-de-puntos" class="nav-link" data-scroll-target="#diagrama-de-puntos">Diagrama de puntos</a></li>
  <li><a href="#boxplot" id="toc-boxplot" class="nav-link" data-scroll-target="#boxplot">Boxplot</a></li>
  </ul></li>
  <li><a href="#evolución" id="toc-evolución" class="nav-link" data-scroll-target="#evolución"><span class="header-section-number">3.2</span> Evolución</a>
  <ul class="collapse">
  <li><a href="#gráfico-de-serie-temporal" id="toc-gráfico-de-serie-temporal" class="nav-link" data-scroll-target="#gráfico-de-serie-temporal">Gráfico de serie temporal</a></li>
  <li><a href="#gráfico-de-serie-temporal-1" id="toc-gráfico-de-serie-temporal-1" class="nav-link" data-scroll-target="#gráfico-de-serie-temporal-1">Gráfico de serie temporal</a></li>
  <li><a href="#evolución-de-datos-económicos" id="toc-evolución-de-datos-económicos" class="nav-link" data-scroll-target="#evolución-de-datos-económicos">Evolución de datos económicos</a></li>
  </ul></li>
  <li><a href="#relación-entre-variables" id="toc-relación-entre-variables" class="nav-link" data-scroll-target="#relación-entre-variables"><span class="header-section-number">3.3</span> Relación entre variables</a>
  <ul class="collapse">
  <li><a href="#diagrama-bivariante" id="toc-diagrama-bivariante" class="nav-link" data-scroll-target="#diagrama-bivariante">Diagrama bivariante</a></li>
  <li><a href="#gráficos-3d-para-tres-variables" id="toc-gráficos-3d-para-tres-variables" class="nav-link" data-scroll-target="#gráficos-3d-para-tres-variables">Gráficos 3D para tres variables</a></li>
  </ul></li>
  <li><a href="#importancia-de-cada-parte" id="toc-importancia-de-cada-parte" class="nav-link" data-scroll-target="#importancia-de-cada-parte"><span class="header-section-number">3.4</span> Importancia de cada parte</a>
  <ul class="collapse">
  <li><a href="#diagrama-de-barrras" id="toc-diagrama-de-barrras" class="nav-link" data-scroll-target="#diagrama-de-barrras">Diagrama de barrras</a></li>
  <li><a href="#gráficos-de-pastel-y-de-dónut" id="toc-gráficos-de-pastel-y-de-dónut" class="nav-link" data-scroll-target="#gráficos-de-pastel-y-de-dónut">Gráficos de pastel, y de dónut</a></li>
  <li><a href="#otros-gráficos" id="toc-otros-gráficos" class="nav-link" data-scroll-target="#otros-gráficos">Otros gráficos</a></li>
  </ul></li>
  <li><a href="#gráficos-que-conviene-evitar" id="toc-gráficos-que-conviene-evitar" class="nav-link" data-scroll-target="#gráficos-que-conviene-evitar"><span class="header-section-number">3.5</span> Gráficos que conviene evitar</a>
  <ul class="collapse">
  <li><a href="#gráficos-con-tres-dimensiones" id="toc-gráficos-con-tres-dimensiones" class="nav-link" data-scroll-target="#gráficos-con-tres-dimensiones">Gráficos con tres dimensiones</a></li>
  <li><a href="#comparar-gráficos-construidos-con-diferentes-escalas" id="toc-comparar-gráficos-construidos-con-diferentes-escalas" class="nav-link" data-scroll-target="#comparar-gráficos-construidos-con-diferentes-escalas">Comparar gráficos construidos con diferentes escalas</a></li>
  <li><a href="#gráficos-que-destacan-falsas-tendencias" id="toc-gráficos-que-destacan-falsas-tendencias" class="nav-link" data-scroll-target="#gráficos-que-destacan-falsas-tendencias">Gráficos que destacan falsas tendencias</a></li>
  <li><a href="#pictogramas-que-exageran-las-diferencias" id="toc-pictogramas-que-exageran-las-diferencias" class="nav-link" data-scroll-target="#pictogramas-que-exageran-las-diferencias">Pictogramas que exageran las diferencias</a></li>
  </ul></li>
  <li><a href="#dar-gato-por-liebre-usando-gráficos" id="toc-dar-gato-por-liebre-usando-gráficos" class="nav-link" data-scroll-target="#dar-gato-por-liebre-usando-gráficos"><span class="header-section-number">3.6</span> Dar gato por liebre usando gráficos</a>
  <ul class="collapse">
  <li><a href="#representar-la-variable-que-más-conviene" id="toc-representar-la-variable-que-más-conviene" class="nav-link" data-scroll-target="#representar-la-variable-que-más-conviene">Representar la variable que más conviene</a></li>
  <li><a href="#gráficos-con-escalas-inapropiadas" id="toc-gráficos-con-escalas-inapropiadas" class="nav-link" data-scroll-target="#gráficos-con-escalas-inapropiadas">Gráficos con escalas inapropiadas</a></li>
  <li><a href="#buenas-y-malas-artes-en-la-construcción-de-gráficos" id="toc-buenas-y-malas-artes-en-la-construcción-de-gráficos" class="nav-link" data-scroll-target="#buenas-y-malas-artes-en-la-construcción-de-gráficos">Buenas y malas artes en la construcción de gráficos</a></li>
  </ul></li>
  <li><a href="#apéndice-3.a-software-para-representaciones-gráficas-y-análisis-estadísticos" id="toc-apéndice-3.a-software-para-representaciones-gráficas-y-análisis-estadísticos" class="nav-link" data-scroll-target="#apéndice-3.a-software-para-representaciones-gráficas-y-análisis-estadísticos">Apéndice 3.A: Software para representaciones gráficas y análisis estadísticos</a></li>
  <li><a href="#apéndice-3.b-cuadros-de-mando" id="toc-apéndice-3.b-cuadros-de-mando" class="nav-link" data-scroll-target="#apéndice-3.b-cuadros-de-mando">Apéndice 3.B: Cuadros de mando</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./20_DESCRIPTIVA.html">ESTADÍSTICA DESCRIPTIVA</a></li><li class="breadcrumb-item"><a href="./22_Graficos.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Representaciones gráficas</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Representaciones gráficas</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Empezamos planteando un reto: la <a href="#tbl-Panaderia">Tabla 3.1</a> contiene los pesos de una muestra de las barras de pan producidas en una panadería. El pan es elaborado en dos máquinas que son utilizadas por dos operarios, uno por la mañana y otro por la tarde. El peso debe ser de <span class="math inline">\(220 \pm 10\)</span> g. ¿Observa algún problema? Si lo hay, ¿qué se debería hacer para resolverlo?</p>
<div id="tbl-Panaderia" class="tabla-wrapper42 anchored">

<table class="tabla-0301 caption-top table">
<caption>Tabla 3.1: Datos tomados en una panadería</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Día</th>
<th data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Operario</th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Máquina 1</th>
<th data-quarto-table-cell-role="th">&nbsp;</th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Máquina 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>B</td>
<td>220,3</td>
<td>215,8</td>
<td>220,4</td>
<td>221,5</td>
<td>&nbsp;</td>
<td>217,7</td>
<td>214,9</td>
<td>214,7</td>
<td>218,2</td>
</tr>
<tr class="even">
<td>2</td>
<td>A</td>
<td>217,7</td>
<td>222,7</td>
<td>216,0</td>
<td>219,4</td>
<td>&nbsp;</td>
<td>214,1</td>
<td>216,2</td>
<td>213,1</td>
<td>214,7</td>
</tr>
<tr class="odd">
<td>3</td>
<td>A</td>
<td>219,8</td>
<td>220,2</td>
<td>218,0</td>
<td>219,3</td>
<td>&nbsp;</td>
<td>216,8</td>
<td>214,2</td>
<td>215,4</td>
<td>215,9</td>
</tr>
<tr class="even">
<td>4</td>
<td>B</td>
<td>220,0</td>
<td>223,9</td>
<td>220,1</td>
<td>216,9</td>
<td>&nbsp;</td>
<td>218,9</td>
<td>218,8</td>
<td>215,2</td>
<td>219,9</td>
</tr>
<tr class="odd">
<td>5</td>
<td>B</td>
<td>217,9</td>
<td>224,2</td>
<td>214,1</td>
<td>221,1</td>
<td>&nbsp;</td>
<td>216,5</td>
<td>218,0</td>
<td>213,8</td>
<td>215,2</td>
</tr>
<tr class="even">
<td>6</td>
<td>A</td>
<td>215,5</td>
<td>222,0</td>
<td>221,7</td>
<td>227,0</td>
<td>&nbsp;</td>
<td>220,1</td>
<td>217,6</td>
<td>217,9</td>
<td>218,4</td>
</tr>
<tr class="odd">
<td>7</td>
<td>B</td>
<td>225,3</td>
<td>215,1</td>
<td>218,8</td>
<td>218,3</td>
<td>&nbsp;</td>
<td>216,5</td>
<td>217,5</td>
<td>216,2</td>
<td>215,8</td>
</tr>
<tr class="even">
<td>8</td>
<td>B</td>
<td>222,6</td>
<td>219,5</td>
<td>223,9</td>
<td>221,6</td>
<td>&nbsp;</td>
<td>218,9</td>
<td>215,4</td>
<td>215,0</td>
<td>215,4</td>
</tr>
<tr class="odd">
<td>9</td>
<td>B</td>
<td>214,1</td>
<td>220,6</td>
<td>218,8</td>
<td>221,6</td>
<td>&nbsp;</td>
<td>212,8</td>
<td>213,4</td>
<td>215,1</td>
<td>220,8</td>
</tr>
<tr class="even">
<td>10</td>
<td>A</td>
<td>225,7</td>
<td>216,2</td>
<td>219,7</td>
<td>225,0</td>
<td>&nbsp;</td>
<td>221,4</td>
<td>216,7</td>
<td>215,9</td>
<td>212,9</td>
</tr>
<tr class="odd">
<td>11</td>
<td>A</td>
<td>219,1</td>
<td>218,9</td>
<td>220.6</td>
<td>219,5</td>
<td>&nbsp;</td>
<td>218,0</td>
<td>223,5</td>
<td>216,9</td>
<td>213,4</td>
</tr>
<tr class="even">
<td>12</td>
<td>B</td>
<td>223,0</td>
<td>219,6</td>
<td>217,9</td>
<td>216,7</td>
<td>&nbsp;</td>
<td>216,0</td>
<td>214,2</td>
<td>221,6</td>
<td>213,1</td>
</tr>
<tr class="odd">
<td>13</td>
<td>A</td>
<td>221,1</td>
<td>222,4</td>
<td>219,6</td>
<td>218,8</td>
<td>&nbsp;</td>
<td>206,5</td>
<td>212,5</td>
<td>212,0</td>
<td>210,3</td>
</tr>
<tr class="even">
<td>14</td>
<td>A</td>
<td>224,3</td>
<td>219,5</td>
<td>218,4</td>
<td>220,6</td>
<td>&nbsp;</td>
<td>212,1</td>
<td>210,6</td>
<td>211,0</td>
<td>208,2</td>
</tr>
<tr class="odd">
<td>15</td>
<td>A</td>
<td>222,2</td>
<td>219,9</td>
<td>222,4</td>
<td>222,7</td>
<td>&nbsp;</td>
<td>211,1</td>
<td>208,2</td>
<td>209,8</td>
<td>210,7</td>
</tr>
<tr class="even">
<td>16</td>
<td>B</td>
<td>219,2</td>
<td>213,6</td>
<td>219,6</td>
<td>222,5</td>
<td>&nbsp;</td>
<td>209,4</td>
<td>211,0</td>
<td>210,4</td>
<td>212,2</td>
</tr>
<tr class="odd">
<td>17</td>
<td>B</td>
<td>218,0</td>
<td>217,3</td>
<td>213,0</td>
<td>224,1</td>
<td>&nbsp;</td>
<td>209,4</td>
<td>211,8</td>
<td>212,7</td>
<td>212,5</td>
</tr>
<tr class="even">
<td>18</td>
<td>B</td>
<td>217,7</td>
<td>219,9</td>
<td>221,9</td>
<td>219,9</td>
<td>&nbsp;</td>
<td>211,6</td>
<td>211,9</td>
<td>207,9</td>
<td>212,0</td>
</tr>
<tr class="odd">
<td>19</td>
<td>A</td>
<td>217,4</td>
<td>219,6</td>
<td>217,9</td>
<td>222,6</td>
<td>&nbsp;</td>
<td>217,7</td>
<td>215,4</td>
<td>214,9</td>
<td>216,5</td>
</tr>
<tr class="even">
<td>20</td>
<td>A</td>
<td>216,1</td>
<td>220,4</td>
<td>224,5</td>
<td>222,2</td>
<td>&nbsp;</td>
<td>214,3</td>
<td>221,4</td>
<td>213,4</td>
<td>215,0</td>
</tr>
</tbody>
</table>

</div>
<p>Si trata de sacar conclusiones solo mirando los números es fácil que se equivoque. Aunque solo hay 160 valores, analizarlos “a ojo” siempre es arriesgado. Tampoco es una buena idea empezar calculando medias y desviaciones típicas o, peor todavía, empezar planteando test estadísticos más o menos sofisticados.</p>
<p>Después de valorar la calidad de los datos, es decir, de reflexionar sobre si son representativos del conjunto sobre el que se pretende sacar conclusiones, lo primero que conviene hacer es representarlos gráficamente. De esta manera tenemos una primera idea –muchas veces ya suficiente– de lo que está pasando. También podemos detectar posibles valores anómalos (en nuestro ejemplo no los hay) que si pasan desapercibidos pueden alterar completamente las conclusiones finales.</p>
<p>En la <a href="#fig-histoPanaderia" class="quarto-xref">Figura&nbsp;<span>3.1</span></a> tenemos los histogramas de nuestros datos separados primero por máquina y después por operario. Siempre es una buena idea analizar los datos según su origen. También habíamos construido histogramas específicos para los datos de cada operario en cada máquina ya que el problema podría estar concentrado en el uso que uno de los operarios hace de una de las máquinas, pero vimos que esto no ocurre.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Analizar los datos separándolos según su origen
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cuando se busca la causa de un problema siempre conviene analizar los datos separándolos según su procedencia, por si el problema se concentra en un origen concreto. Pero esto solo es posible si los datos se han recogido teniendo en cuenta ese interés. Si en la panadería se hubieran anotado únicamente los pesos, sin identificar su origen, sería imposible comparar las máquinas y, por tanto, descubrir el origen del problema.</p>
</div>
</div>
<p>Lo que nuestros gráficos indican es que la máquina 2 está desajustada: está fabricando aproximadamente en torno a 215 g cuando debería hacerlo en torno a 220. Sobre el peso de las unidades de la máquina 1 no hay objeciones. Respecto a los operarios, aunque –como es natural– sus histogramas no son iguales, no se observa ninguna diferencia que sugiera un comportamiento distinto.</p>
<p>En resumen: habría que ajustar la máquina 2 para que -en promedio- dé el peso objetivo. Respecto a la máquina 1 y a los operarios, no aparece ninguna información relevante.</p>
<div id="fig-histoPanaderia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-histoPanaderia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0301_histogramaPanaderia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-histoPanaderia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.1: Histogramas de los datos recogidos en una panadería estratificados por máquina y por operario.
</figcaption>
</figure>
</div>
<section id="forma-de-la-distribución-valor-central-y-dispersión" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="forma-de-la-distribución-valor-central-y-dispersión"><span class="header-section-number">3.1</span> Forma de la distribución, valor central y dispersión</h2>
<p>Cuando el interés se centra en conocer la forma que presenta la distribución (si es simétrica, bimodal, …), el gráfico de uso más habitual es el histograma, aunque cuando se tienen pocos datos es preferible usar diagramas de puntos.</p>
<p>Una alternativa a los histogramas son los boxplots, que permiten resumir en poco espacio la información más relevante de grandes volúmenes de datos, destacando de forma explícita los posibles valores anómalos.</p>
<section id="histograma" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="histograma">Histograma</h3>
<p>En la <a href="#tbl-Tabulacion">Tabla 3.1</a> están tabulados los valores obtenidos en la máquina 1. El histograma es la representación gráfica de esa tabla y, por lo general, se construye a partir de las frecuencias absolutas. No obstante, cuando se comparan situaciones con distinto número de datos, puede resultar más adecuado emplear frecuencias relativas o porcentajes. El aspecto del histograma no cambia al pasar de un tipo de frecuencia a otro; únicamente se modifica la escala vertical.</p>
<div id="tbl-Tabulacion" ;="" class="tabla-wrapper42 anchored">

<table class="tabla-0302 caption-top table">
<caption>Tabla 3.2: Tabulación de los valores obtenidos en la máquina 1.</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Pesos</th>
<th data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Frecuencia</th>
<th data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Frecuencia</th>
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; vertical-align: middle;">Porcentaje</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">absoluta (<em>n</em>)</th>
<th data-quarto-table-cell-role="th">absoluta (<em>f</em>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&gt;212 - 214</td>
<td>2</td>
<td>0,025</td>
<td>2,5</td>
</tr>
<tr class="even">
<td>&gt;214 - 216</td>
<td>7</td>
<td>0,0875</td>
<td>8,75</td>
</tr>
<tr class="odd">
<td>&gt;216 - 218</td>
<td>12</td>
<td>0,15</td>
<td>15</td>
</tr>
<tr class="even">
<td>&gt;218 - 220</td>
<td>23</td>
<td>0,2875</td>
<td>28,75</td>
</tr>
<tr class="odd">
<td>&gt;220 - 222</td>
<td>16</td>
<td>0,02</td>
<td>20</td>
</tr>
<tr class="even">
<td>&gt;222 - 224</td>
<td>12</td>
<td>0,015</td>
<td>15</td>
</tr>
<tr class="odd">
<td>&gt;224 - 226</td>
<td>7</td>
<td>0,0875</td>
<td>8,75</td>
</tr>
<tr class="even">
<td>&gt;226 - 228</td>
<td>1</td>
<td>0,0125</td>
<td>1,25</td>
</tr>
<tr class="odd">
<td>Total</td>
<td><em>N</em> = 80</td>
<td>1</td>
<td>100</td>
</tr>
</tbody>
</table>

</div>
<p>Los histogramas se construyen para variables continuas (las que pueden tomar cualquier valor dentro de un intervalo: peso, longitud, tiempo,…) de forma que cuando acaba una barra empieza otra, sin espacio entre ellas.</p>
<p>Si la variable es discreta (solo toma valores concretos: número de hijos por familia, número de pedidos que se reciben cada día, …) hablamos de diagrama de barras. En este caso se levanta una barra sobre cada uno de los valores posibles (o grupos de ellos) y las barras pueden no tocarse.</p>
<p>Algunos aspectos a considerar en la construcción de los histogramas son:</p>
<ul>
<li><p>Conviene tener unos <strong>25 datos como mínimo</strong>. Con menos datos no es capaz de reflejar de forma adecuada la información relevante.</p></li>
<li><p>Existen fórmulas para orientar en la selección del <strong>número de intervalos</strong> (<span class="math inline">\(h\)</span>) en función del número de datos (<span class="math inline">\(N\)</span>). La más sencilla es <span class="math inline">\(h=\sqrt{N}\)</span>, aunque no interesa tener menos de 5 ni suelen ser necesarios más de 15. En cualquier caso, lo más importante es que la escala del eje horizontal, así como los extremos y la anchura de los intervalos sean números redondos, fáciles de leer y de interpretar. Esta tarea no la suelen hacer bien los paquetes de software y conviene editar el gráfico o hacer uso de las opciones disponibles para colocar los valores que interesan.</p></li>
<li><p>Cuando se construyen tablas de frecuencia o histogramas siempre surge la duda de a qué intervalo asignar los <strong>valores frontera</strong>. La respuesta es que no importa, solo hay que ser coherente y usar el mismo criterio en todos los intervalos. Nosotros hemos asignado los valores frontera al extremo superior, tal como lo hace por defecto el programa R. Si con los mismos datos, misma anchura de intervalo, mismos valores de los extremos, en fin, todo igual, hacemos el histograma con Minitab<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, sale distinto. La razón es que Minitab asigna los valores frontera al extremo inferior.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>La forma del histograma no es única.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Fijando las escalas de los ejes, la forma del histograma depende de la anchura que se elija para los intervalos y también del punto en que se empiezan a construir. Si decidimos que la anchura sea igual a 2, el perfil del histograma no será el mismo si los extremos son 0, 2, 4, 6,.. que si son 1, 3, 5, 7,… Aún así, si tenemos suficientes datos, aunque el perfil cambie, la impresión que dará será la misma.</p>
</div>
</div>
<p>Un último comentario sobre los histogramas: no hay que esperar que cuando provienen de una distribución Normal su perfil sea simétrico y con la típica forma de campana. Eso hay que esperar cuando se tienen muchos datos (pongamos que más de 1000), pero no cuando se tienen 50 o 100. Lo volveremos a comentar con ejemplos gráficos cuando hablemos de la distribución Normal.</p>
<div id="tbl-ProsCons" ;="" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 3.3: Histograma. Pros y contras</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 22px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Da una visión de la forma de la distribución, del valor en torno al que se mueven los datos y de su dispersión.</li>
<li>Si se añaden las tolerancias y el valor objetivo, ayuda a valorar como está saliendo la producción en procesos industriales.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 22px 0px 8px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>No es útil si se tienen pocos datos.</li>
<li>Su aspecto depende del número de intervalos y de los valores en que están situados.</li>
<li>No informa sobre posibles tendencias o evolución de los datos.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="diagrama-de-puntos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="diagrama-de-puntos">Diagrama de puntos</h3>
<p>Cuando se tienen pocos datos, y especialmente cuando se trata de comparar los de varios grupos, los diagramas de puntos son una herramienta clara y sencilla. Basta construir una escala y colocar cada valor donde le corresponde. Naturalmente, si se comparan varios grupos la escala debe ser la misma para todos ellos.</p>
<p>Se puede pensar que si se tienen pocos datos no vale la pena representarlos gráficamente, pero los gráficos siempre ayudan a ver de forma más clara los resultados obtenidos y también a detectar posibles valores anómalos, si los hay.</p>
<p>Observe los siguientes valores que podrían corresponder a los resultados obtenidos con dos tratamientos, A y B:</p>
<table class="tabla-03sn1 caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td>Grupo A:</td>
<td>14,0</td>
<td>16,0</td>
<td>14,5</td>
<td>13,9</td>
<td>15,3</td>
<td>12,9</td>
<td>14,7</td>
<td>15,1</td>
<td>15,9</td>
<td>13,5</td>
</tr>
<tr class="even">
<td>Grupo B:</td>
<td>17,9</td>
<td>17,3</td>
<td>17,3</td>
<td>15,4</td>
<td>16,3</td>
<td>16,9</td>
<td>17,8</td>
<td>17,6</td>
<td>15,7</td>
<td>16,6</td>
</tr>
</tbody>
</table>
<p>Seguramente solo mirando los números ya se dará cuenta de que en el grupo B los valores son más altos, pero la situación queda mucho más clara a la vista del diagrama de puntos (<a href="#fig-dotplot" class="quarto-xref">Figura&nbsp;<span>3.2</span></a>).</p>
<div id="fig-dotplot" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dotplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0302_dotplot.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dotplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.2: Diagramas de puntos para comparar los resultados de dos tratamientos.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>¿Qué aportaría un test estadístico formal?
</div>
</div>
<div class="callout-body-container callout-body">
<p>A la vista de estos diagramas de puntos estamos prácticamente seguros de que el nivel de respuesta con el tratamiento B es mayor que con el A. No hace falta realizar análisis más sofisticados para llegar a esa conclusión. Cuando a la vista del gráfico hay dudas, un test estadístico formal no las aclara, simplemente les asigna un valor numérico (una probabilidad) relacionado con la discrepancia observada. Ese valor ayuda a decidir si nos inclinamos a considerar que hay diferencias o que no las hay. Tratamos este tema con más detalle en el capítulo 8.</p>
</div>
</div>
<div id="tbl-ProsCons" ;="" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 3.4: Diagrama de puntos</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Especialmente útil para comparar situaciones con pocos datos.</li>
<li>Es fácil de construir --incluso a mano-- y de interpretar.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 18px 15px 24px 0px; vertical-align: top"><ul>
<li>Hay alternativas mejores cuando se tienen muchos datos.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="boxplot" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="boxplot">Boxplot</h3>
<p>Capta los aspectos más relevantes de grandes volúmenes de datos: valor central, simetría y dispersión, destacando de forma individual cada uno de los valores que se podrían considerar anómalos.</p>
<p>Su interpretación exige recordar algunas de las medidas que definimos en el capítulo anterior. Vamos a construir uno paso a paso usando un sencillo conjunto de 15 valores que ya presentamos ordenados:</p>
<table class="tabla-03sn2 caption-top table">
<tbody>
<tr class="odd">
<td><em>1</em></td>
<td><em>2</em></td>
<td><em>3</em></td>
<td><em>4</em></td>
<td><em>5</em></td>
<td><em>6</em></td>
<td><em>7</em></td>
<td><em>8</em></td>
<td><em>9</em></td>
<td><em>10</em></td>
<td><em>11</em></td>
<td><em>12</em></td>
<td><em>13</em></td>
<td><em>14</em></td>
<td><em>15</em></td>
</tr>
<tr class="even">
<td>8</td>
<td>17</td>
<td>24</td>
<td>27</td>
<td>27</td>
<td>30</td>
<td>31</td>
<td>32</td>
<td>33</td>
<td>35</td>
<td>39</td>
<td>39</td>
<td>50</td>
<td>60</td>
<td>62</td>
</tr>
</tbody>
</table>
<p>Empezamos calculando los siguientes valores:</p>
<ul>
<li><p>Mediana (<span class="math inline">\(Me\)</span>). Como tenemos 15 valores, la mediana será el que queda en la posición 8, por tanto: <span class="math inline">\(Me = 32\)</span>.</p></li>
<li><p>Cuartiles (<span class="math inline">\(Q_1\)</span> y <span class="math inline">\(Q_3\)</span>). Primero identificamos la posición (<span class="math inline">\(P\)</span>) y después calculamos los valores. Como en este caso la posición nos da números enteros no hace falta interpolar. <span class="math display">\[P_{Q_1}=0,25(n+1) = 4  \rightarrow Q_1 = 27\]</span> <span class="math display">\[P_{Q_3}=0,75(n+1) = 12  \rightarrow Q_3 = 39\]</span></p></li>
<li><p>Rango intercuartílico: <span class="math inline">\(IQR = Q_3 - Q_1 = 39 -27 = 12\)</span></p></li>
<li><p>Valores frontera (<span class="math inline">\(F_1\)</span> y <span class="math inline">\(F_3\)</span>): Marcan el inicio de la zona de anomalías y se sitúan a una distancia de 1,5 veces el rango intercuartílico a partir de cada cuartil, es decir: <span class="math display">\[F_1 = Q_1 -1,5 \cdot IQR = 9\]</span> <span class="math display">\[F_3 = Q_3 +1,5 \cdot IQR = 57\]</span> Ya podemos construir el boxplot. Tomando como referencia una escala que abarque el rango de variación de nuestros datos, seguimos los siguientes pasos:</p></li>
</ul>
<ol type="1">
<li><p>Construir la caja (rectángulo) cuyos extremos inferior y superior corresponden al valor de los cuartiles <span class="math inline">\(Q_1\)</span> y <span class="math inline">\(Q_3\)</span>. El ancho de la caja no importa. Dentro de la caja se traza una línea correspondiente al valor de la mediana.</p></li>
<li><p>Colocar las “patas”. La de arriba va desde <span class="math inline">\(Q_3\)</span> hasta la última observación antes de entrar en la zona de anomalías. Esta zona empieza en <span class="math inline">\(F_3 = 57\)</span>. La última observación antes de llegar a 57 es igual a 50 por tanto, hasta ahí llegará la pata superior. El valor frontera en la parte inferior es <span class="math inline">\(F_1 = 9\)</span>, el último valor antes de llegar a 9 es 17 y hasta ahí llega la pata inferior.</p></li>
<li><p>Añadir los valores anómalos. Se coloca un símbolo, normalmente un asterisco, en el lugar correspondiente de la escala.<br></p></li>
</ol>
<div id="fig-boxplotConstruccion" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplotConstruccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0303_boxplotConstruccion.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplotConstruccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.3: Construcción de un boxplot. Las patas llegan hasta la última observación antes de entrar en la zona de anomalías.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Otros nombres para el boxplot
</div>
</div>
<div class="callout-body-container callout-body">
<p>Boxplot se puede traducir por “diagrama de caja”. Para que el nombre incluya la referencia a las patas también se le ha llamado “box-and-whisker plot” y como <em>whisker</em> se traduce como “bigote”, a veces en español se le ha denominado “diagrama de caja y bigotes”. En aras de la brevedad nosotros le llamaremos simplemente boxplot. Meter los bigotes seguramente solo sirve para llamar la atención.</p>
</div>
</div>
<p>Volvamos a los datos de la panadería. En la <a href="#fig-boxplotPanaderia" class="quarto-xref">Figura&nbsp;<span>3.4</span></a> comparamos los pesos de cada máquina y de cada operario usando boxplots. Igual que en los histogramas, puede verse que la máquina 1 produce en torno al valor objetivo y con una variabilidad que es compatible con las tolerancias establecidas, mientras que la máquina 2 está claramente desajustada. Entre los operarios, tal como habíamos visto, no se aprecia una diferencia relevante.</p>
<div id="fig-boxplotPanaderia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplotPanaderia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0304_boxplotPanaderia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplotPanaderia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.4: Datos de la panadería. Boxplots para comparar máquinas y operarios.
</figcaption>
</figure>
</div>
<p>La <a href="#fig-boxplotEspeVida" class="quarto-xref">Figura&nbsp;<span>3.5</span></a> muestra la esperanza de vida en 2019 para cada uno de los 196 países del mundo, agrupados según el continente al que pertenecen (datos: Gapminder)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. En el gráfico de la izquierda, la esperanza de vida de cada país se representa con un punto en la columna correspondiente a su continente. Los puntos se desplazan ligeramente de forma aleatoria en el eje horizontal para evitar la superposición y facilitar la percepción de su densidad.</p>
<p>A la derecha se muestran los boxplots correspondientes. En un caso como este, ambos tipos de gráfico pueden resultar apropiados. Sin embargo, si el número de datos fuera muy elevado, sería preferible utilizar los boxplots, ya que en el gráfico de puntos los valores acabarían formando masas compactas en las que no sería posible distinguir unos puntos de otros.</p>
<p>En los boxplots hemos añadido los nombres de los países que aparecen como anomalías en cada continente. En África y en América lo son por tener una esperanza de vida singularmente baja, y en Oceanía, por tenerla alta. Los paquetes de software suelen tener opciones para identificar con facilidad el origen de esos puntos, que muchas veces son los más interesantes.</p>
<div id="fig-boxplotEspeVida" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplotEspeVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0305_boxplotEspeVida.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplotEspeVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.5: Dos formas de representar la esperanza de vida en los 196 países del mundo según el continente al que pertenecen.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>¿Son siempre “anómalos” los valores marcados como anomalías?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cuando provienen de una distribución Normal (forma de campana simétrica y con la mayoría de observaciones agrupadas en torno al valor central) si un valor aparece como anomalía significa que está bastante más lejos de donde “debería estar” y vale la pena prestarle atención. Si los datos provienen de otro tipo de distribución, como distribuciones asimétricas con cola larga hacia un lado, estos valores pueden ser perfectamente normales y no deberían considerarse anómalos.</p>
</div>
</div>
<div id="tbl-ProsCons" ;="" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 3.5: Boxplots. Pros y contras</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Pueden resumir en poco espacio la información más relevante de grandes volúmenes de datos.</li>
<li>Muy útiles para comparar varios grupos, especialmente si el número de datos es muy grande.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 18px 15px 24px 0px; vertical-align: top"><ul>
<li>No se puede deducir con cuantos datos se ha construido y este es un valor relevante para poderlo interpretar adecuadamente.</li>
<li>Su interpretación no es intuitiva.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
</section>
<section id="evolución" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="evolución"><span class="header-section-number">3.2</span> Evolución</h2>
<p>Cuando los datos se han tomado en orden cronológico, siempre es interesante ver cuál ha sido su evolución. La figura <a href="#fig-evolucionPanaderia" class="quarto-xref">Figura&nbsp;<span>3.6</span></a> muestra los pesos obtenidos en la panadería a lo largo del mes. Los de las cuatro unidades de cada máquina que se han pesado cada día aparecen alineados verticalmente sobre el número de día, y una línea va uniendo sus valores medios. Además de ver que la máquina 2 está descentrada observamos que en esta máquina se produce un bajón en los pesos desde mediados de la semana 3 hasta mediados de la semana 4. Este aspecto –que puede ayudar a identificar el origen del problema– es imposible de detectar si solo se usan los gráficos que hemos visto hasta ahora.</p>
<div id="fig-evolucionPanaderia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-evolucionPanaderia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0306_evolucionPanaderia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-evolucionPanaderia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.6: Datos de la panadería. Evolución de los pesos en máquinas 1 y 2.
</figcaption>
</figure>
</div>
<section id="gráfico-de-serie-temporal" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="gráfico-de-serie-temporal">Gráfico de serie temporal</h3>
<p>Cuando el interés se centra en conocer la evolución de una variable, los gráficos de líneas, o de serie temporal, suelen ser los más adecuados. La <a href="#fig-evoEspVida" class="quarto-xref">Figura&nbsp;<span>3.7</span></a> muestra la evolución de la esperanza de vida en cinco países, uno de cada continente (datos: <a href="https://www.gapminder.org/data">Gapminder</a>). Cada valor se representa con un punto y los puntos correspondientes a cada país se unen con una recta que en este caso da sensación de continuidad porque los puntos están muy cerca. Se observa una tendencia creciente en los cinco países con algunos bajones muy pronunciados que podemos identificar con conflictos bélicos.</p>
<div id="fig-evoEspVida" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-evoEspVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0307_evoEspVida.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-evoEspVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.7: Datos de la panadería. Evolución de los pesos en máquinas 1 y 2.
</figcaption>
</figure>
</div>
<p>Como regla general, cuando se trata de representar cómo evoluciona una variable lo mejor es usar diagramas de líneas. No es buena idea usar columnas para representar el valor en cada unidad de tiempo.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>¿Qué es la esperanza de vida?
</div>
</div>
<div class="callout-body-container callout-body">
<p>A veces nos esmeramos en dar valores muy precisos sobre variables (salud mental, inteligencia, popularidad, pobreza…) que no está claro cómo se han definido. Un chascarrillo dice que la mejor forma de disminuir el número de pobres de un país es cambiando la definición de pobre. Respecto a la esperanza de vida hay aspectos que no son intuitivos y es interesante ver como se calcula. En la Wikipedia hay información muy clara y detallada sobre este tema, también con datos y gráficos.</p>
</div>
</div>
<div id="tbl-ProsCons" ;="" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 3.6: Gráficos en serie de tiempo. Pros y contras</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Claro e intuitivo.</li>
<li>Permite analizar la evolución de varias variables usando distinto tipo de línea (distinto trazo o color).</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 12px 15px 15px 0px; vertical-align: top"><ul>
<li>Un manejo descuidado de la escala vertical puede dificultar la valoración de la evolución.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="gráfico-de-serie-temporal-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="gráfico-de-serie-temporal-1">Gráfico de serie temporal</h3>
<p>Para tener una visión general de cómo ha evolucionado la esperanza de vida en todos los países no es buena idea usar un gráfico como el de la <a href="#fig-evoEspVida" class="quarto-xref">Figura&nbsp;<span>3.7</span></a> con una línea para cada país, puesto que aparecerá una maraña de líneas donde será imposible distinguir unas de otras. Una buena opción es construir un boxplot para cada año con los valores de los 196 países y ver cómo evolucionan esos boxplots (<a href="#fig-evoBoxplotEspVida" class="quarto-xref">Figura&nbsp;<span>3.8</span></a>). No es posible seguir la evolución de cada país pero sí se tiene una visión general de cómo se han ido moviendo esos valores en el periodo considerado. Por ejemplo, vemos que hasta la década de 1940 algunos países aparecían como anómalos por tener una esperanza de vida muy superior a la habitual y que actualmente esos valores ya no son excepcionales: en el boxplot correspondiente a 2019 –el último– observamos que quedan al mismo nivel o por debajo del primer cuartil (en el gráfico hemos añadido una línea horizontal a trazos para verlo más claro).</p>
<p>A partir de la segunda mitad del siglo XX desaparecen las anomalías por valores altos pero aparecen algunas anomalías por tener valores singularmente bajos, parece que debido a guerras o desastres naturales. También es interesante observar que los valores máximos presentan una suave tendencia creciente que no sabemos donde nos llevará.</p>
<div id="fig-evoBoxplotEspVida" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-evoBoxplotEspVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0308_evoBoxplotEspVida.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-evoBoxplotEspVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.8: Evolución de la esperanza de vida desde 1901 hasta 2019. Cada boxplot representa los valores de todos los países en el año correspondiente.
</figcaption>
</figure>
</div>
<div id="tbl-ProsCons" ;="" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 3.7: Boxplots estratificados por periodo de tiempo. Pros y contras</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Permite analizar la evolución global de muchas variables.</li>
<li>Si se dispone de muchas medidas en cada unidad de tiempo permiten visualizar su variabilidad de forma compacta.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 3px 0px 12px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 18px 15px 15px 0px; vertical-align: top"><ul>
<li>Interpretación menos intuitiva que los gráficos en serie de tiempo.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="evolución-de-datos-económicos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="evolución-de-datos-económicos">Evolución de datos económicos</h3>
<p>El análisis de la evolución de variables en el ámbito de la economía requiere prestar atención a aspectos como los que a continuación se comentan.</p>
<section id="inflación" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="inflación">Inflación</h4>
<p>Cuando la magnitud representada se mide en dinero, hay que estar atentos a si los valores se presentan tal cual (valores corrientes) o si se han corregido con la inflación (valores constantes), ya que las conclusiones pueden ser muy distintas. Supongamos que en un país los salarios se han duplicado en los últimos 10 años, pasando de 100 a 200, siguiendo la evolución que se muestra en la <a href="#fig-salariosInflacion" class="quarto-xref">Figura&nbsp;<span>3.9</span></a> (izquierda). A la vista de los datos y de lo empinada que es la tendencia, parece que los trabajadores de este país son unos afortunados.</p>
<p>Incluso si nos dicen que la tasa de inflación durante ese periodo ha sido del 15% anual, parece que las cosas han ido bien, a fin de cuentas, los salarios no han subido el 15% sino el 100%. Pero al hacer las cuentas el panorama cambia. El aumento de los precios se acumula anualmente y si en el año 1 eran igual a 100, el año 2 serán igual a 115 (=100·1,15), el año 3 tendremos 132,5 (=115·1,15), el año 7 ya habrán superado el valor de 200 y el año 10 estarán en 351,79. Es decir, lo que hace 10 años se compraba con un salario ahora se compra con tres y medio. Así pues, las cosas no van tan bien para los trabajadores de ese país.</p>
<div id="fig-salariosInflacion" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-salariosInflacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0309_salariosInflacion.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-salariosInflacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.9: Evolución de los salarios (izquierda) y de los salarios y el poder adquisitivo (derecha). Parece que los salarios crecen menos en el gráfico de la derecha, la diferencia está en la escala.
</figcaption>
</figure>
</div>
<p>Que el coste de la vida aumente por encima de los salarios significa que el poder adquisitivo disminuye. Si en el año 1 el salario daba para comprar todo lo necesario, en el año 2 ya no llegará, porque aunque se cobre 110, lo que antes se compraba por 100 ahora costará 115 y ya no da para todo sino solo para el 95,7%. En el año 3 se cobra 115 y los precios ya van por 132,25 (solo podremos comprar el 87%), hasta el año 10, en que cobramos 200 pero lo necesario está ya en 351,8, con lo que apenas llegaremos al 57%. La situación queda resumida en la tabla y el gráfico de la <a href="#fig-salariosPoderAdq" class="quarto-xref">Figura&nbsp;<span>3.10</span></a>.</p>
<div style="display: flex; gap: 0rem; align-items: center;">

  <!-- TABLA -->
  <div style="flex: 0.9;">
    <!-- <table style="border-collapse: collapse; width: 100%; text-align: center;"> -->
    <table class="tabla-0310">
    
    <colgroup>
      <col style="width: 16%;">
      <col style="width: 26%;">
      <col style="width: 26%;">
      <col style="width: 32%;">
    </colgroup>
  
      <thead>
        <tr>
          <th>Día</th>
          <th>Precios</th>
          <th>Salarios</th>
          <th>Poder adquisitivo</th>
        </tr>
      </thead>
      <tbody>
        <tr><td>1</td><td>100,0</td><td>100</td><td>100</td></tr>
        <tr><td>2</td><td>115,0</td><td>110</td><td>95,7</td></tr>
        <tr><td>3</td><td>132,3</td><td>115</td><td>87,0</td></tr>
        <tr><td>4</td><td>152,1</td><td>130</td><td>85,5</td></tr>
        <tr><td>5</td><td>174,9</td><td>130</td><td>74,3</td></tr>
        <tr><td>6</td><td>201,1</td><td>135</td><td>67,1</td></tr>
        <tr><td>7</td><td>231,3</td><td>140</td><td>60,5</td></tr>
        <tr><td>8</td><td>266,0</td><td>150</td><td>56,4</td></tr>
        <tr><td>9</td><td>305,9</td><td>180</td><td>58,8</td></tr>
        <tr><td>10</td><td>351,8</td><td>200</td><td>56,9</td></tr>
      </tbody>
    </table>
  </div>

  <!-- IMAGEN -->
  <div style="flex: 1; text-align: center;">
    <img src="Figuras/f0310_poderAdquisitivo.png" style="max-width: 95%; height: auto;">
  </div>

</div>
<div id="fig-salariosPoderAdq" class="fig-normal4 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-salariosPoderAdq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0000_figuraFantasma2.png" class="fig-normal4 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-salariosPoderAdq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.10: Salarios y poder adquisitivo. Los salarios se duplican en 10 años, pero la inflación es del 15% anual.
</figcaption>
</figure>
</div>
</section>
<section id="valores-que-presentan-estacionalidad" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="valores-que-presentan-estacionalidad">Valores que presentan estacionalidad</h4>
<p>Muchas variables que se utilizan para valorar la marcha de la economía presentan estacionalidad, es decir, no se comportan de manera uniforme a lo largo del año, sino que en determinados periodos tienden a subir y en otros a bajar. En España el número de parados suele bajar en diciembre y volver a subir a principios de año. Esto provoca que –aunque interesa que el número de parados sea el menor posible– la bajada en un mes pueda ser peor noticia que la subida en otro mes. Si normalmente un mes baja en 200.000 y este año solo ha bajado 100.000, las cosas están yendo mal, mientras que si normalmente sube 100.000 y este año solo ha subido 20.000, las cosas van mejor.</p>
<p>A fin de poder valorar mejor la evolución de la variable considerada, es preferible que el eje horizontal solo incluya los 12 meses de un año y se representen por separado las líneas correspondientes a cada uno de los años considerados, como en la parte derecha de la <a href="#fig-salariosPoderAdq" class="quarto-xref">Figura&nbsp;<span>3.10</span></a><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>, sale distinto. La razón es que Minitab asigna los valores frontera al extremo inferior.</p>
<div id="fig-paro" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-paro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0311_paro.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:110.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-paro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.11: Dos formas de representar la evolución del número de parados en España en 2022 y 2023.
</figcaption>
</figure>
</div>
</section>
<section id="valores-absolutos-o-porcentajes" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="valores-absolutos-o-porcentajes">¿Valores absolutos o porcentajes?</h4>
<p>En algunos casos lo relevante es el porcentaje de cambio y no su valor absoluto. Si se compara la rentabilidad de dos acciones, una que el año pasado valía 5 y este año vale 10, con otra que valía 50 y ahora vale 55, si representamos el cambio colocando los valores en el eje vertical parece que las dos acciones han subido lo mismo, pero el que compró la primera ha ganado el 100% (ha doblado su valor) mientras que el que compró la segunda solo ha ganado el 10%. Como esto es lo que realmente interesa, es mejor usar porcentajes en el eje vertical, como en la figura de la derecha.</p>
<div id="fig-valorAcciones" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-valorAcciones-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0312_valorAcciones.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:110.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-valorAcciones-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.12: Dos formas de representar la evolución del número de parados en España en 2022 y 2023.
</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="relación-entre-variables" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="relación-entre-variables"><span class="header-section-number">3.3</span> Relación entre variables</h2>
<p>Para estudiar la relación entre dos variables cuantitativas, lo habitual –y también lo más sencillo– es utilizar un diagrama bivariante.</p>
<p>Conviene tener presente que el hecho de que dos variables muestren una estrecha relación entre ellas no implica que exista entre ellas una relación de causa-efecto: es decir, que cambiar el valor de una no necesariamente provoca un cambio en el valor de la otra. Puede existir una tercera variable relacionada con esas dos que al cambiar provoque cambios en las que observamos, sin que exista ninguna relación directa entre ellas. Un ejemplo muy típico es el de los daños que causa un incendio y el número de bomberos que acuden a apagarlo. Se observa en los datos estadísticos que, cuantos más bomberos acuden, mayores son los daños ocasionados, pero a nadie se le ocurre mandar menos bomberos para que los daños sean menores. En este caso, la variable relacionada con las que observamos es –obviamente– la magnitud del incendio.</p>
<section id="diagrama-bivariante" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="diagrama-bivariante">Diagrama bivariante</h3>
<p>La figura <a href="#fig-espeVida_RentaPC" class="quarto-xref">Figura&nbsp;<span>3.13</span></a> muestra la relación entre la esperanza de vida y la renta per cápita de la mayoría de países en 2019 (datos: <a href="https://www.gapminder.org/data">Gapminder</a>). No se han incluido los que tienen menos de 100.000 habitantes, ya que algunos (como Mónaco) tienen rentas muy altas y obligan a utilizar una escala en la que los puntos que interesa observar quedan amontonados.</p>
<p>Utilizando puntos de distinto color se identifica a qué continente pertenece cada país. África tiene la renta y la esperanza de vida más bajas. Además de observar la tendencia general, conocida como curva de Preston<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>, también tienen interés los puntos singulares, es decir, los países que tienen una esperanza de vida singularmente alta o baja en relación con su renta, sobre el diagrama se indican los nombres de algunos de estos países.</p>
<div id="fig-espeVida_RentaPC" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-espeVida_RentaPC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0313_espeVida_RentaPC.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-espeVida_RentaPC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.13: Relación entre esperanza de vida y renta per cápita en el año 2019 en países con más de 100.000 habitantes.
</figcaption>
</figure>
</div>
<p>Recuerde que cuando analizamos una variable, debe estar muy claro a qué nos estamos refiriendo. Los gráficos que incluye <a href="https://www.gapminder.org/data">Gapminder</a> informan con todo detalle sobre el significado de las variables que se incluyen, en particular, de los criterios usados para calcular la renta per cápita<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Otros nombres para el diagrama bivariante
</div>
</div>
<div class="callout-body-container callout-body">
<p>También se conoce como diagrama de correlación o diagrama de dispersión.</p>
</div>
</div>
<p>En un diagrama bivariante podemos hacer que el tamaño de los puntos esté relacionado con el valor de una nueva variable, dando lugar al llamado <em>diagrama de burbujas</em>. En la <a href="#fig-espeVida_RentaPC_mortInf" class="quarto-xref">Figura&nbsp;<span>3.14</span></a> el tamaño de los puntos está relacionado con la tasa de mortalidad infantil. Se observa que los países con baja esperanza de vida y también baja renta son los que tienen una mayor mortalidad infantil, y que estos países se encuentran básicamente en el continente africano.</p>
<div id="fig-espeVida_RentaPC_mortInf" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-espeVida_RentaPC_mortInf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0314_espeVida_RentaPC_mortInf.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-espeVida_RentaPC_mortInf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.14: La superficie de los puntos es proporcional al ratio de mortalidad infantil del país que representan.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Cada variable tiene su eje
</div>
</div>
<div class="callout-body-container callout-body">
<p>En el eje horizontal (<span class="math inline">\(x\)</span>) colocamos la variable que viene dada y en el vertical (<span class="math inline">\(y\)</span>), aquella cuya relación con la primera queremos analizar. No al revés. Para ver si el peso de las personas está relacionado con su estatura, colocamos la estatura en el eje horizontal y el peso en el vertical. La estatura viene dada; si alguien considera que pesa mucho en relación con su estatura, no se plantea crecer, sino perder peso.</p>
</div>
</div>
<div id="tbl-ProsCons" ;="" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 3.7: Diagramas bivariantes. Pros y contras</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 18px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>La forma más sencilla de analizar la relación entre dos variables cuantitativas.</li>
<li>Permite la estratificación usando distintos tipos de punto. Se puede añadir una tercera variable relacionada con el tamaño de los puntos.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 12px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 12px 15px 15px 0px; vertical-align: top"><ul>
<li>Cuando se analizan grandes volúmenes de datos puede aparecer una gran mancha de puntos que hace imposible su interpretación.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="gráficos-3d-para-tres-variables" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="gráficos-3d-para-tres-variables">Gráficos 3D para tres variables</h3>
<p>En general, existen mejores alternativas que usar tres dimensiones para mostrar la relación entre tres variables. La <a href="#fig-Gini_rentaPC_EspVida" class="quarto-xref">Figura&nbsp;<span>3.15</span></a> representa la esperanza de vida frente al índice de Gini (una medida de desigualdad en la distribución de la riqueza), y la renta per cápita. Aunque los paquetes de software estadístico permiten mover el cubo para buscar la perspectiva más adecuada, no suele ser fácil apreciar de un vistazo las relaciones que existen.</p>
<div id="fig-Gini_rentaPC_EspVida" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Gini_rentaPC_EspVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0315_Gini_rentaPC_EspVida.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Gini_rentaPC_EspVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.15: Esperanza de vida frente al índice de Gini y la renta per cápita en un gráfico 3D.
</figcaption>
</figure>
</div>
<p>En la <a href="#fig-Graf2D_Gini_rentaPC_EspVida" class="quarto-xref">Figura&nbsp;<span>3.16</span></a> se pierde la información sobre el continente al que pertenece cada país, pero se observa con mayor claridad que los valores elevados del índice de Gini están asociados a rentas per cápita bajas —aunque seguramente habrá superricos— y a una menor esperanza de vida.</p>
<div id="fig-Graf2D_Gini_rentaPC_EspVida" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Graf2D_Gini_rentaPC_EspVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0316_Graf2D_Gini_rentaPC_EspVida.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Graf2D_Gini_rentaPC_EspVida-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.16: Índice de Gini frente a renta per cápita, usando un código de colores para representar la esperanza de vida.
</figcaption>
</figure>
</div>
<p>No hay que dejarse deslumbrar por gráficos que son muy vistosos pero que no transmiten de forma clara la información que contienen los datos.</p>
<div id="tbl-ProsCons" ;="" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 3.7: Diagramas 3D. Pros y contras.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Pueden ser útiles para una primera exploración de los datos, especialmente cuando se pueden manejar de forma interactiva.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 12px 0px 12px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 8px 15px 8px 0px; vertical-align: top"><ul>
<li>No son fáciles de interpretar cuando no hay posibilidad de interacción.</li>
<li>En general existen otras opciones que muestran la información de forma más clara.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
</section>
<section id="importancia-de-cada-parte" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="importancia-de-cada-parte"><span class="header-section-number">3.4</span> Importancia de cada parte</h2>
<p>La forma habitual de representar tablas de frecuencias es usar diagramas de barras, con distintas opciones de estratificación. También se utilizan otros gráficos como los diagramas de pastel, aunque con este estilo nosotros preferimos los de tipo <em>dónut</em>. Los paquetes de software también presentan otras posibilidades.</p>
<section id="diagrama-de-barrras" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="diagrama-de-barrras">Diagrama de barrras</h3>
<p>La <a href="#fig-diagramaBarras" class="quarto-xref">Figura&nbsp;<span>3.17</span></a> utiliza un diagrama de barras para mostrar el número de países que hay en cada continente. A la derecha, cada barra se ha estratificado según el cuartil al que pertenece cada país según su renta per cápita. Se observa que la mayoría de países situados en el primer cuartil (el 25% que tiene menor renta) están en África.</p>
<div id="fig-diagramaBarras" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagramaBarras-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0317_diagramaBarras.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagramaBarras-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.17: Número de países en cada continente. A la derecha estratificados según el cuartil al que pertenecen según su renta per cápita.
</figcaption>
</figure>
</div>
</section>
<section id="gráficos-de-pastel-y-de-dónut" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="gráficos-de-pastel-y-de-dónut">Gráficos de pastel, y de dónut</h3>
<p>Otra forma de representar el tamaño de cada una de las partes son los gráficos de pastel (también se usan otros nombres<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>, como el de la izquierda de la figura <span class="math inline">\(\ref{donutPiePoblacion}\)</span>, donde se representa la población en cada uno de los cinco continentes. Este tipo de diagrama nunca ha tenido mucho predicamento en el ámbito científico-técnico, donde en general se prefieren los diagramas de barras, aunque sí es utilizado en economía y gestión de empresas. Últimamente se está viendo desplazado por el llamado gráfico de dónut (seguimos en la pastelería), en el que la información se ve más clara y se ahorra tinta <a href="#fig-donutPiePoblacion" class="quarto-xref">Figura&nbsp;<span>3.18</span></a> derecha).</p>
<div id="fig-donutPiePoblacion" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-donutPiePoblacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0318_donutPiePoblacion.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-donutPiePoblacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.18: Población en cada continente. Diagramas de pastel y de dónut.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Diagrama de Florence Nightingale
</div>
</div>
<div class="callout-body-container callout-body">
<p>Florence Nightingale fue una pionera en la recolección y el análisis de datos para mejorar la toma de decisiones en el ámbito sanitario. Utilizaba una representación gráfica que recuerda al diagrama de pastel, pero que en realidad es un histograma ordenado cronológicamente de forma circular<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
</div>
</div>
<div id="tbl-ProsCons" ;="" class="tabla-wrapper34 anchored">

<table class="tabla-ProsCons caption-top table">
<caption>Tabla 3.7: Diagramas de pastel o de dónut. Pros y contras.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 8px 0px 8px 0px; vertical-align: top;"><!-- top right bottom left -->
<div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>PROS</strong> <span class="fa-solid fa-thumbs-up fa-xl" style="color: #0ca701;"></span>
</div></td>
<td style="padding: 12px 15px 8px 0px; vertical-align: top"><ul>
<li>Representación sencilla e intuitiva de las partes de un total.</li>
<li>Construcción con paquetes de software de fácil acceso.</li>
</ul></td>
</tr>
<tr class="even" style="border-top: 1px solid #dee2e6; border-bottom: 1px solid #dee2e6;">
<td style="text-align: center; padding: 12px 0px 12px 0px; vertical-align: top;"><div style="display: flex; flex-direction: column; align-items: center; gap: 12px;">
<strong>CONS</strong> <span class="fa-solid fa-thumbs-down fa-xl" style="color: #f03333; "></span>
</div></td>
<td style="padding: 8px 15px 8px 0px; vertical-align: top"><ul>
<li>No deben usarse cuando se tienen muchas partes, ya que cuesta identificar lo que representa cada una.</li>
<li>Su utilidad es dudosa cuando solo se tienen dos partes ya que un solo número (un porcentaje) da la misma información.</li>
</ul></td>
</tr>
</tbody>
</table>

</div>
</section>
<section id="otros-gráficos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="otros-gráficos">Otros gráficos</h3>
<p>Muchos paquetes de software estadístico permiten el uso de nuevas formas de representación gráfica de los datos, como el diagrama de rectángulos de la <a href="#fig-rectPropor" class="quarto-xref">Figura&nbsp;<span>3.19</span></a>. A la vista de este gráfico, es interesante observar las enormes diferencias que existen en el número de habitantes de cada país. Realizando algunas sencillas operaciones con la tabla de valores se observa que entre China e India tienen tantos habitantes como los 182 países con menor población (de Vietnam en adelante). Los seis países más poblados (China, India, EE.UU., Indonesia, Pakistán y Brasil) concentran el 50% de la población mundial. Los seis menos poblados (Liechtenstein, Mónaco, San Marino, Palau, Nauru y Tuvalu, los tres primeros europeos y los otros tres de Oceanía) suman unos 150.000 habitantes y apenas representan el 0,00145% de la población mundial.</p>
<p>Estos resultados no son ninguna novedad, pero verlos de forma explícita invita a reflexionar sobre la pertinencia de usar el país como unidad de análisis para comparar indicadores de bienestar y desarrollo. En China o en la India caben casi 30 Colombias u otras tantas Españas.</p>
<div id="fig-rectPropor" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rectPropor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0319_rectPropor.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rectPropor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.19: La población de cada país es proporcional a la superficie del rectángulo que lo representa. En el recuadro rojo hay 76 países –el 38,8%– pero solo contienen el 1,5% de la población.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ranking de medallas en los juegos olímpicos
</div>
</div>
<div class="callout-body-container callout-body">
<p>No parece muy razonable que el ranking de medallas obtenidas en los Juegos Olímpicos se presente usando el país como unidad de comparación, colocando al mismo nivel a países como EE.UU. y a Dominica<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>.</p>
</div>
</div>
<p>Cuando se trata de representar la distribución geográfica de un valor, lo más claro suele ser hacerlo sobre el mapa adecuado. La <a href="#fig-mapaMundi_MortInf" class="quarto-xref">Figura&nbsp;<span>3.20</span></a> muestra el intervalo en que se encuentra el índice de mortalidad infantil en cada país. Hay que tener en cuenta que en casos como este la impresión que se da puede variar dependiendo de la forma en que se elijan los intervalos.</p>
<div id="fig-mapaMundi_MortInf" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mapaMundi_MortInf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0320_mapaMundi_MortInf.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mapaMundi_MortInf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.20: Intervalo en que se encuentra el ratio de mortalidad infantil.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="gráficos-que-conviene-evitar" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="gráficos-que-conviene-evitar"><span class="header-section-number">3.5</span> Gráficos que conviene evitar</h2>
<p>Puede ser discutible cuál es la mejor forma de representar unos datos, pero siempre hay que evitar los gráficos con adornos innecesarios que dificultan su interpretación y –por supuesto– los que transmiten información falsa o tendenciosa.</p>
<section id="gráficos-con-tres-dimensiones" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="gráficos-con-tres-dimensiones">Gráficos con tres dimensiones</h3>
<p>Si de lo que se trata es de transmitir la información de forma clara –otra cosa es querer impresionar con gráficos &lt;<artísticos>&gt;–, los gráficos con tres dimensiones son siempre una mala opción. Enredan el gráfico al incluir aspectos irrelevantes que dificultan la transmisión de la información de forma rápida y directa. En la <a href="#fig-graficos3D" class="quarto-xref">Figura&nbsp;<span>3.21</span></a> queda claro que se lee mejor y más rápido cuando se construyen sin esa tercera dimensión.</artísticos></p>
<div id="fig-graficos3D" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-graficos3D-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0321_graficos3D.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-graficos3D-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.21: Añadir una tercera dimensión es una mala opción cuando el objetivo es transmitir la información de la forma más clara posible.
</figcaption>
</figure>
</div>
<p>En los gráficos de pastel, especialmente cuando para destacar un sector se desgaja del resto, el problema no es que sean más difíciles de interpretar, sino que pueden dar a entender una situación que es falsa. En la figura <a href="#fig-pastel3D" class="quarto-xref">Figura&nbsp;<span>3.22</span></a> en el gráfico 3D parece que el sector Sanidad es el más importante, cuando basta mirar los números para darse cuenta de que no lo es.</p>
<div id="fig-pastel3D" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pastel3D-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0322_pastel3D.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pastel3D-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.22: El diagrama 3D da la falsa sensación de que la sanidad es el sector más importante.
</figcaption>
</figure>
</div>
</section>
<section id="comparar-gráficos-construidos-con-diferentes-escalas" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="comparar-gráficos-construidos-con-diferentes-escalas">Comparar gráficos construidos con diferentes escalas</h3>
<p>Recordemos el caso de la panadería y supongamos que se dispone de una tercera máquina de la que también se han recogido datos, como en las otras dos. El histograma de estos datos está en la <a href="#fig-distintasEscala" class="quarto-xref">Figura&nbsp;<span>3.23</span></a>, junto al que ya vimos de la máquina 1. ¿Qué puede decirse de la producción de la máquina 3?</p>
<div id="fig-distintasEscala" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distintasEscala-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0323_distintasEscala.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distintasEscala-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.23: ¿Qué se puede decir de la máquina 3 respecto a la 1?
</figcaption>
</figure>
</div>
<p>Si está pensando que produce con más variabilidad, ha caído en la trampa. Los dos histogramas se han construido con los mismos datos, el diferente aspecto es debido a que la escala del eje horizontal es distinta. Moraleja: cuando se construyen histogramas –o gráficos en general– para comparar distintas situaciones, es imprescindible que las escalas sean iguales, tal como hemos hecho en la <a href="#fig-histoPanaderia" class="quarto-xref">Figura&nbsp;<span>3.1</span></a>, de lo contrario vamos a confundir a nuestros lectores o incluso nos vamos a engañar nosotros mismos. Esta tarea no la hacen los paquetes de software, que adaptan la escala a la variabilidad de los datos. Es necesario acceder a las opciones y fijar los valores que nos conviene. Si la magnitud representada tiene unas tolerancias, incluirlas en el gráfico, junto con el valor objetivo en el centro de la escala, también ayuda a la interpretación.</p>
</section>
<section id="gráficos-que-destacan-falsas-tendencias" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="gráficos-que-destacan-falsas-tendencias">Gráficos que destacan falsas tendencias</h3>
<p>A veces nos encontramos con un diagrama bivariante en el que la nube de puntos no muestra ninguna relación entre las variables, pero incluye algunos puntos alejados de esa nube. Si se ajusta una recta de regresión, esos puntos singulares pueden influir mucho en su pendiente, sugiriendo la presencia de una relación que en realidad no existe.</p>
<p>La <a href="#fig-rectaTendencia" class="quarto-xref">Figura&nbsp;<span>3.24</span></a> (izquierda) muestra una situación de este tipo, con tres puntos alejados del resto e incluyendo la recta de regresión ajustada. Esta recta puede dar la sensación de que al aumentar el valor de <span class="math inline">\(X\)</span> también tiende a aumentar el de <span class="math inline">\(Y\)</span>, pero esta tendencia viene determinada por los puntos singulares, que quizá son errores o corresponden a circunstancias excepcionales que no forman parte del marco que se está estudiando. Si observamos la zona donde se encuentra la mayoría de puntos (figura de la derecha) constatamos que no existe ninguna relación y, por tanto, la recta de tendencia da una información engañosa.</p>
<div id="fig-rectaTendencia" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rectaTendencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0324_rectaTendencia.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rectaTendencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.24: La recta ajustada sugiere una relación que seguramente no existe y que solo es debida a la influencia de unos puntos singulares.
</figcaption>
</figure>
</div>
</section>
<section id="pictogramas-que-exageran-las-diferencias" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="pictogramas-que-exageran-las-diferencias">Pictogramas que exageran las diferencias</h3>
<p>Recurrir a imágenes para representar cantidades –los llamados &lt;<pictogramas>&gt;– puede ser visualmente atractivo pero dar una visión deformada de la información que se quiere transmitir.</pictogramas></p>
<p>Para poner de manifiesto que el precio de la vivienda se ha triplicado en los últimos años podemos representar ese incremento dibujando dos casas, la segunda con el triple de altura que la primera. El problema radica en que si se mantienen las proporciones, la segunda tendrá el triple de altura, pero nueve veces la superficie de la primera, y la sensación que se transmite es que la segunda casa (el segundo precio) es nueve veces mayor que la primera (<a href="#fig-casaConRayas" class="quarto-xref">Figura&nbsp;<span>3.25</span></a>).</p>
<div id="fig-casaConRayas" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-casaConRayas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0325_casaConRayas.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-casaConRayas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.25: La segunda casa es el triple de alta pero da la sensación de ser nueve veces mayor.
</figcaption>
</figure>
</div>
<p>Si se utilizan círculos para representar cantidades, lo proporcional a la cantidad debe ser el área, no el diámetro. Si las cantidades a representar son proporcionales a 1, 3 y 5, los diámetros deben serlo a 1, <span class="math inline">\(\sqrt{3}\)</span> y <span class="math inline">\(\sqrt{5}\)</span>.</p>
<div id="fig-circulo" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-circulo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0326_circulo.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-circulo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.26: Los círculos de la primera fila, con un diámetro proporcional al valor que representan, exageran las diferencias. En la segunda fila el área es proporcional al valor.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="dar-gato-por-liebre-usando-gráficos" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="dar-gato-por-liebre-usando-gráficos"><span class="header-section-number">3.6</span> Dar gato por liebre usando gráficos</h2>
<p>A veces la información estadística puede ser poco fiable, no porque se digan mentiras –que a veces también, pero ese no es nuestro tema–, sino porque nos presentan los datos de una manera interesada, más orientada a defender un punto de vista o un interés concreto que a reflejar la realidad de forma objetiva. En este terreno de la transmisión de información interesada, los gráficos tienen un papel protagonista.</p>
<p>Naturalmente, una misma información se puede dar de muchas maneras, con gráficos y sin ellos. Es normal que si se tiene interés en dar una cierta impresión se elija la forma que más convenga. Si en una tienda de ropa tienen una prenda barata y pasada de moda, la pueden anunciar con esas palabras o diciendo que es clásica y económica. Algo parecido ocurre con los gráficos, depende de como se construyan pueden dar una impresión u otra. Conocer los trucos y argucias más habituales nos sirve para valorar mejor su calidad y honradez.</p>
<section id="representar-la-variable-que-más-conviene" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="representar-la-variable-que-más-conviene">Representar la variable que más conviene</h3>
<p>Si las exportaciones de enero a junio se han ido reduciendo, de manera que en junio son solo la mitad que en enero, podemos representar los datos con el gráfico de la izquierda de la <a href="#fig-exportaciones" class="quarto-xref">Figura&nbsp;<span>3.27</span></a> o con el de la derecha, en el que se han usado los mismos datos, pero representando los valores acumulados. Si usted es el responsable de las ventas y presenta el primer gráfico va a dar muy mala impresión pero, sin decir mentiras, puede presentar el segundo y, con un poco de suerte, un buen discurso y pasando rápido sobre los detalles, quizá pase desapercibido.</p>
<div id="fig-exportaciones" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-exportaciones-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0327_exportaciones.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-exportaciones-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.27: Dos formas de representar la evolución de las exportaciones. Los datos son los mismos pero la impresión que dan los gráficos es muy diferente.
</figcaption>
</figure>
</div>
</section>
<section id="gráficos-con-escalas-inapropiadas" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="gráficos-con-escalas-inapropiadas">Gráficos con escalas inapropiadas</h3>
<section id="diagramas-de-barras" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="diagramas-de-barras">Diagramas de barras</h4>
<p>Jugar con la escala vertical en los diagramas de barras es el recurso más habitual para exagerar la diferencia entre grupos. La <a href="#fig-escalaBarra" class="quarto-xref">Figura&nbsp;<span>3.28</span></a> (izquierda) está inspirada en el gráfico que apareció en un anuncio en el que la cadena de televisión TV4 presumía de tener más audiencia que sus competidoras. Efectivamente, los datos indican que ha tenido un mayor porcentaje de audiencia, pero las diferencias son muy pequeñas –aproximadamente un punto porcentual– y probablemente quedan dentro del margen de error en este tipo de estimaciones. Sin embargo, la impresión que da a primera vista –que es como seguramente se miran los gráficos en los anuncios– es que las diferencias son importantes, y todavía se podría exagerar más haciendo partir la escala de 17,5. En el gráfico de la derecha la escala parte de cero, que es lo correcto en este tipo de gráficos, y las diferencias apenas se notan, que es lo que ocurre en realidad.</p>
<div id="fig-escalaBarra" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-escalaBarra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0328_escalaBarra.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-escalaBarra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.28: Adaptando la escala al rango de variación de los datos se exageran las diferencias. En los diagramas de barras el eje vertical debe partir de cero.
</figcaption>
</figure>
</div>
</section>
<section id="gráficos-de-serie-temporal" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="gráficos-de-serie-temporal">Gráficos de serie temporal</h4>
<p>En los gráficos de serie temporal las reglas son otras. No conviene que la escala vertical vaya del valor mínimo al máximo, como en la <a href="#fig-escalaLineas" class="quarto-xref">Figura&nbsp;<span>3.29</span></a> (izquierda), porque se exageran las diferencias, pero tampoco conviene partir siempre de cero, porque dependiendo de la magnitud representada, los cambios pueden ser relevantes y apenas notarse (derecha). Una interesante guía de estilo de <em>The Wall Street Journal</em><a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> recomienda que el rango de variación de los datos ocupe aproximadamente dos tercios de la escala vertical, tal como hemos realizado en el gráfico de la <a href="#fig-escalaLineas2" class="quarto-xref">Figura&nbsp;<span>3.30</span></a>. Además, si lo que interesa es la variación más que los valores absolutos, es recomendable representar los porcentajes.</p>
<div id="fig-escalaLineas" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-escalaLineas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0329_escalaLineas.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-escalaLineas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.29: En el gráfico de la izquierda se exageran las diferencias, en el de la derecha apenas se notan.
</figcaption>
</figure>
</div>
<div id="fig-escalaLineas2" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-escalaLineas2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0330_escalaLineas2.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-escalaLineas2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.30: Escala vertical recomendada en gráficos que muestran una tendencia.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="buenas-y-malas-artes-en-la-construcción-de-gráficos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="buenas-y-malas-artes-en-la-construcción-de-gráficos">Buenas y malas artes en la construcción de gráficos</h3>
<p>Un clásico sobre cómo dar información interesada usando la estadística es el libro de Darrell Huff: <em>How to Lie with Statistics</em>, escrito en 1954 con toques de humor que lo hacen muy ameno y que todavía mantiene interés y actualidad. Existen también libros específicos sobre cómo manipular gráficos, como el de Gerald E. Jones: <em>How to Lie with Charts</em>, pero lo fundamental está en el de Huff. El libro de Alberto Cairo: <em>How Charts Lie</em> es una exposición muy seria, completa y bien documentada sobre cómo detectar manipulaciones y malos usos de los gráficos.</p>
<p>Un libro que nos parece excelente y que ya hemos citado es la guía de <em>The Wall Street Journal</em>, especialmente para representaciones gráficas en el ámbito de la economía . El texto de Cole N. Knaflic: <em>Storytelling with Data</em> contiene muchas ideas interesantes y muy bien expuestas sobre como presentar los gráficos de manera que sean más claros e informativos.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>No todo es manipulación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dar demasiado protagonismo a la búsqueda de pifias o malos usos de la estadística puede fomentar una imagen frívola de nuestra disciplina, que poco o nada tiene que ver con el método científico. Justo lo contrario de lo que pretendemos. La mayoría de los gráficos que se publican en la prensa seria son correctos y están bien pensados. En la prensa sensacionalista y en la publicidad, la calidad de los gráficos seguramente es similar a la del resto de material publicado.</p>
</div>
</div>
</section>
</section>
<section id="apéndice-3.a-software-para-representaciones-gráficas-y-análisis-estadísticos" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-3.a-software-para-representaciones-gráficas-y-análisis-estadísticos">Apéndice 3.A: Software para representaciones gráficas y análisis estadísticos</h2>
<p>Casi todos los gráficos que aparecen en este libro –y en particular los de este capítulo, excepto los de las <a href="#fig-graficos3D" class="quarto-xref">Figura&nbsp;<span>3.21</span></a> y <a href="#fig-pastel3D" class="quarto-xref"><span>3.22</span></a>– se han realizado con el software estadístico R, un lenguaje de programación gratuito y de código abierto muy utilizado en el ámbito académico. Tiene una versión base que se puede completar con una gran variedad de paquetes para realizar casi cualquier tipo de análisis o representación gráfica. El problema es que familiarizarse con él y usarlo con agilidad exige un tiempo de aprendizaje que no lo hace recomendable para cursos generales de introducción a la estadística. Además, si no se práctica se olvida rápido, por lo que el esfuerzo inicial resulta un esfuerzo poco productivo.</p>
<p>En esta línea de los lenguajes de programación, una alternativa a R es Python. Es una mejor opción para aprender a programar –o para tener un primer contacto con la programación– y también permite realizar análisis estadísticos<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>. Puede ser especialmente interesante en cursos impartidos en grados del ámbito de la ciencia o la tecnología en los que la programación con Python forma parte del plan de estudios.</p>
<p>Otra opción son los paquetes de software que utilizan el lenguaje y los algoritmos de R añadiendo una presentación con menús, de forma que el proceso de aprendizaje es muy corto y toda la energía se puede dedicar al análisis de los datos. De este tipo tenemos, entre otros<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>:</p>
<ul>
<li><p><strong>BlueSky Statistics:</strong> Tiene muchas posibilidades de análisis gráfico e incluye una gran variedad de técnicas estadísticas. Tiene un aspecto muy profesional, con una versión gratuita (más que suficiente para los objetivos de un curso introductorio) y también una versión de pago, con más servicios, para empresas.</p></li>
<li><p><strong>Jamovi:</strong> Es el que más nos gusta para un curso introductorio. Limpio y claro, prácticamente no necesita explicación. Permite realizar las representaciones gráficas más habituales y aplicar las técnicas de análisis que se incluyen en los primeros cursos. Presenta la peculiaridad de que se pueden añadir &lt;<paquetes>&gt; desarrollados por otras personas –igual que en R– lo que puede darle mucho recorrido (<a href="#fig-CapturaHCGoogle" class="quarto-xref">Figura&nbsp;<span>3.32</span></a>).</paquetes></p></li>
<li><p><strong>JASP:</strong> Es intuitivo y fácil de usar. Vale la pena tenerlo en cuenta. Con muchas posibilidades de análisis –incluyendo estadística bayesiana– que van más allá de los contenidos de un curso introductorio.</p></li>
<li><p><strong>R Commander:</strong> Ha sido durante muchos años la interfaz utilizada para facilitar el uso de R en cursos introductorios. Se ha convertido en un estándar, pero creemos que ahora existen mejores alternativas.</p></li>
</ul>
<div id="fig-CapturaJamovi" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-CapturaJamovi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0331_CapturaJamovi.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-CapturaJamovi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.31: Diagrama bivariante realizado con Jamovi.
</figcaption>
</figure>
</div>
<p>Las hojas de cálculo son otra opción que suele estar muy a mano. A veces desdeñadas en ámbitos científicos aunque con gran protagonismo en las áreas de economía y gestión. Suelen ser imbatibles para ordenar, seleccionar y filtrar datos, y como casi nunca los tenemos con la estructura adecuada para su análisis, son un buen recurso para facilitar este trabajo previo. Por otra parte, las tablas dinámicas permiten explorar y resumir fácilmente grandes volúmenes de datos, que también se pueden representar gráficamente.</p>
<p>La <a href="#fig-CapturaHCGoogle" class="quarto-xref">Figura&nbsp;<span>3.32</span></a> muestra un gráfico de burbujas construido con Google Sheets. En cualquier caso, dedicar tiempo a familiarizarse con las hojas de cálculo seguro que es un tiempo bien invertido puesto que están presentes en muchos ámbitos de la vida profesional e incluso personal.</p>
<div id="fig-CapturaHCGoogle" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-CapturaHCGoogle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0332_CapturaHCGoogle.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-CapturaHCGoogle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.32: Gráfico de burbujas realizado con la hoja de cálculo de Google.
</figcaption>
</figure>
</div>
<p>Finalmente, tenemos los paquetes de software comerciales. Algunos, también muy completos e intuitivos, ofrecen condiciones ventajosas para su uso en ámbitos académicos.</p>
</section>
<section id="apéndice-3.b-cuadros-de-mando" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="apéndice-3.b-cuadros-de-mando">Apéndice 3.B: Cuadros de mando</h2>
<p>Presentan la información obtenida de bases de datos mediante gráficos y valores clave dispuestos de manera que se visualicen integramente en la pantalla.</p>
<p>Es un instrumento pensado para que los directivos y técnicos puedan seguir la marcha de su empresa con información relevante, veraz y actualizada para tomar en cada caso las decisiones que convenga. Naturalmente, también es útil para seguir la marcha de cualquier proceso u organización, en particular puede ser una herramienta interesante para seguir la evolución de los estudiantes en un centro docente<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a>.</p>
<p>Los gráficos que utiliza pueden ser de cualquier tipo, incluyendo mapas. Los indicadores clave, también llamados KPI (de las siglas en inglés de <em>Key Performance Indicator</em>), se presentan de forma destacada. Tanto los gráficos como los indicadores pueden ser interactivos, mostrando valores globales que se pueden segmentar según interese (siempre que esté previsto, por supuesto).</p>
<div id="fig-dashboard" class="fig-normal3 quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dashboard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/f0333_dashboard.png" class="fig-normal3 img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dashboard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.33: Esquema de un cuadro de mando. (Imagen: Freepik.com).
</figcaption>
</figure>
</div>
<p>Se pueden construir cuadros de mando con una hoja de cálculo o también usando R con algunos complementos, pero seguramente la mejor opción es usar un paquete de software especializado para esta tarea como <em>Power BI</em>. Este paquete es gratuito si los datos de que se alimenta están en el mismo ordenador donde se ha instalado el programa. Esto es útil para aprender su manejo e incluso para usarlo en pequeñas organizaciones. Las grandes empresas tienen sus datos centralizados y para acceder a ellos hay que usar la versión de pago. Si se tiene interés existen tutoriales fáciles de seguir para empezar a usarlo en un tiempo relativamente breve.</p>
<p>En cualquier caso, lo importante no es tanto el software como la identificación de la información clave que debe ser visualizada y cuál es la mejor forma de hacerlo (gráfico, indicador, mapa…). Emprender la tarea de construir un cuadro de mando para monitorizar la marcha de un proceso muchas veces permite descubrir que los datos almacenados no tienen la estructura –y quizá tampoco la calidad– necesarias para extraer la información que interesa. Tomar conciencia de la importancia de la calidad de los datos y de que estén dispuestos de manera que sea posible obtener la información necesaria, puede ser una de las aportaciones más importantes de esta nueva herramienta.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><small>R y Minitab son paquetes de software estadístico.</small><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><small><a href="https://www.gapminder.org/data">Gapminder</a>. Esta página web contiene datos económicos y de desarrollo en formatos fáciles de tratar. También es una fuente de inspiración sobre cómo visualizar esa información mediante gráficos no convencionales.</small><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><small>Datos: <a href="https://www.sepe.es/HomeSepe/que-es-el-sepe/estadisticas/empleo.html">Servicio Público de Empleo Estatal (España)</a>.</small><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><small>Puede consultar la Wikipedia, con mayor detalle en inglés.</small><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><small>Valores de la renta per cápita ajustados de acuerdo con las diferencias de poder adquisitivo, en dólares USA y con los precios basados en su Índice de Precios al Consumo de 2017. <a href="https://www.gapminder.org/data/documentation/gd001">Más detalles</a></small><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><small>Otras denominaciones habituales son: diagrama circular, gráfico de sectores, diagrama de tarta o diagrama de quesitos.</small><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><small>Información detallada en la Wikipedia, buscar: Florence Nightingale.</small><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p><small>Aunque en los Juegos de París 2024, Dominica, un país con 71.500 habitantes, obtuvo una medalla de oro, y Santa Lucía, con 178.500, obtuvo una de oro y otra de plata. China debería haber obtenido casi 20.000 medallas de oro para igualar a Dominica en número de medallas por habitante.</small><a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p><small>Dona M. Wong (2010): “The Wall Street Journal. Guide to Information Graphics”.</small><a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p><small>Especialmente cuando es completado con el paquete <a href="https://pandas.pydata.org">Pandas</a>.</small><a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p><small>Una revisión y comparación de los más conocidos se encuentra <a href="https://r4stats.com/articles/software-reviews">aquí</a>.</small><a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p><small>Puede ver un ejemplo <a href="https://upcommons.upc.edu/handle/2117/356194">aquí</a> (en catalán)</small>}.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./21_sintesisNumerica.html" class="pagination-link" aria-label="Síntesis numérica de datos">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Síntesis numérica de datos</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./30_VARIABILIDAD.html" class="pagination-link" aria-label="DESCRIBIR LO ALEATORIO">
        <span class="nav-page-text">DESCRIBIR LO ALEATORIO</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>